### ISSUE TITLE
playing sound icon on the taskbar

### ISSUE THREAD

**Issue by Frambooisier** [hrkfdn/ncspot#1007]
**Is your feature request related to a problem? Please describe.**
When I have multiple Konsole terminal instances on my desktop, I dont know witch one is playing music

**Describe the solution you'd like**
it would be great if ncspot's terminal window would show "playing sound" icon on the taskbar, the same as chrome in the screenshot below.

**Describe alternatives you've considered**
**Additional context**
I imagine the sound may be generated on some kind of daemon hence the current behaviour 

![image](https://user-images.githubusercontent.com/15931041/206237939-3820d194-2cb0-43b4-90fd-afcba01976f7.png)

**Comment by hrkfdn** [comment]
Can't be done from within Terminal apps, I'm afraid. Sorry!
