### ISSUE TITLE
Write currently playing track to file

### ISSUE THREAD

**Issue by BenStigsen** [hrkfdn/ncspot#1019]
It would be cool if the currently playing track could be written to a file. This would make it possible to show the currently playing track in applications such as Open Broadcaster Software, and also make it easier to create applications that make use of this. Like updating the Discord status to say what track is currently being played.

Like `artist - title` to `currently_playing.txt`:
```
Fine-Sir-15846600650 - victorious
```

**Comment by hrkfdn** [comment]
Would #1018 help with this?

**Comment by BenStigsen** [comment]
It would definitely make it possible, but not easily. 

Another alternative, might be to change the title of the `ncspot` window.
So `ncspot - Rick Astley - Never Gonna Give You Up`, this would allow one to just grab the title of the window.

**Comment by Salt-Factory** [comment]
Sorry to comment on a closed issue, but for future reference: I struggled with using `netcat` to [show the ncspot status in Sway](https://simonvandevelde.be/posts/Show_cmus_and_ncspot_status_in_Sway.html) as it keeps the connection to the socket open, whereas I am only interested in getting the currently playing information. After fiddling around a bit, I discovered that the OpenBSD variant of netcat has a `-W` flag, which closes the connection after `x` packets. If you set it to 1, the connection closes right after receiving the currently playing song. E.g.:

```
$ nc -W 1 -U ~/.cache/ncspot/ncspot.sock
{"mode":{"Playing":{"secs_since_epoch":1673793184,"nanos_since_epoch":455175037}},"playable":{"type":"Track","id":"0LjTqBwFKfblqnuuDCH2Sw","uri":"spotify:track:0LjTqBwFKfblqnuuDCH2Sw","title":"Flat Beat - Radio Edit","track_number":4,"disc_number":1,"duration":237266,"artists":["Mr. Oizo"],"artist_ids":["0b9ukmbg0MO5eMlorcgOwz"],"album":"Flat Beat","album_id":"4rUN2CpOOBouCSnbi3MfYQ","album_artists":["Mr. Oizo"],"cover_url":"https://i.scdn.co/image/ab67616d0000b2733ba0a79c4ffdbc5d4ce3b165","url":"https://open.spotify.com/track/0LjTqBwFKfblqnuuDCH2Sw","added_at":"2023-01-04T18:30:03Z","list_index":0}}
```

You can then use `jq` to parse the json.
Should also work for the other use cases described in this issue.
Maybe I could add this info to the readme?

**Comment by hrkfdn** [comment]
Hey!
Yeah, the socket solution is more flexible but also more complex. So we should definitely document an example. Would you be so kind to submit a PR?

Nice article btw

On Sun, Jan 15, 2023, at 15:34, Simon Vandevelde wrote:
> 
> 
> Sorry to comment on a closed issue, but for future reference: I struggled with using `netcat` to show the ncspot status in Sway <https://simonvandevelde.be/posts/Show_cmus_and_ncspot_status_in_Sway.html> as it keeps the connection to the socket open, whereas I am only interested in getting the currently playing information. After fiddling around a bit, I discovered that the OpenBSD variant of netcat has a `-W` flag, which closes the connection after `x` packets. If you set it to 1, the connection closes right after receiving the currently playing song. E.g.:
> 
> `$ nc -W 1 -U ~/.cache/ncspot/ncspot.sock
> {"mode":{"Playing":{"secs_since_epoch":1673793184,"nanos_since_epoch":455175037}},"playable":{"type":"Track","id":"0LjTqBwFKfblqnuuDCH2Sw","uri":"spotify:track:0LjTqBwFKfblqnuuDCH2Sw","title":"Flat Beat - Radio Edit","track_number":4,"disc_number":1,"duration":237266,"artists":["Mr. Oizo"],"artist_ids":["0b9ukmbg0MO5eMlorcgOwz"],"album":"Flat Beat","album_id":"4rUN2CpOOBouCSnbi3MfYQ","album_artists":["Mr. Oizo"],"cover_url":"https://i.scdn.co/image/ab67616d0000b2733ba0a79c4ffdbc5d4ce3b165","url":"https://open.spotify.com/track/0LjTqBwFKfblqnuuDCH2Sw","added_at":"2023-01-04T18:30:03Z","list_index":0}}
`
