### ISSUE TITLE
Possibility to add track to playlist

### ISSUE THREAD

**Issue by syslino** [hrkfdn/ncspot#103]
Hi, thank you for this very nice software!  
I'd like to be able to add a  track to a playlist. Maybe something for the "o" menu? Maybe I'm missing something?

**Comment by hrkfdn** [comment]
Nope, that's missing indeed!

**Comment by hrkfdn** [comment]
Implemented it! Let me know if you spot something :)

**Comment by syslino** [comment]
wow, that was quick, thanks! I'll update tomorrow and report back!

**Comment by Cardosaum** [comment]
@hrkfdn , Thank you for implementing this feature!

I'd just like to question: Wouldn't be a good idea to add this feature in the documentation? 

I was only able to find this feature searching in the list of issues for this repo. I know there is the `o` entry in the README.md, but even there, it is not mentioned the option to add song to playlist.

**Comment by hrkfdn** [comment]
@Cardosaum Sure, I'll happily merge a PR with better instructions :)
