### ISSUE TITLE
ctrl+z isn't forwarded to the shell to put ncspot in the background.

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#1040]
**Describe the bug**
Applications like NeoVim forward certain keypresses to the shell so the previous functionality still works in the application. One of those things is ctrl+z which puts the app into the background, and can be undone by typing `fg` into the shell.

**To Reproduce**
In ncspot, type `ctrl+z`. The app should 'close' and go into the background. This doesn't happen as I think ncspot just ignores the keypress.

**Expected behavior**
Ncspot is put into the background.

**System:**
 - OS: Arch Linux
 - Terminal: Alacritty
 - Version: 0.12.0
 - Installed from: Arch Linux community repository

**Additional context**

**Comment by hrkfdn** [comment]
Hi @ThomasFrans, thanks for the report. This is now possible when building with the ncurses backend. By default ncspot uses `termion_backend` for maximum platform compatibility, but on UNIX systems `pancurses_backend` is a solid choice.
