### ISSUE TITLE
Prevent clippy warnings by integrating into CI.

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#1051]
**Is your feature request related to a problem? Please describe.**
I was wondering whether there is a way to prevent accidental commits that aren't free of clippy warnings by having clippy check the code in CI. This would obviously not help against updates to the clippy database of checks if there was already code with those errors in the codebase, but it could at least notify that there are errors in new commits. Maybe it's an idea to work with a set toolchain, although that would force all contributors to download the toolchain next to their stable version.

**Describe the solution you'd like**
In a personal project I just added clippy to CI with the following YAML and from then on it would prevent any more commits that already contain faulty code.

```yaml
      - name: Check Code Quality
        run: cargo clippy --all-targets -- -D warnings
```

**Describe alternatives you've considered**
There could be better ways to do this. Ultimately I'm just proposing to find a way to prevent clippy warnings from being committed as that keeps the codebase cleaner and integrating it into CI somehow would enforce that. It would prevent those small "fix clippy warnings" commits :p

**Comment by hrkfdn** [comment]
Sounds reasonable to me, not sure if we are 100% warning free in the CI builds at the moment (due to feature flags), but I think it's worth pursuing that.
