### ISSUE TITLE
ncspot doesnt look like it should

### ISSUE THREAD

**Issue by nB82DXcx8L2jrXyw** [hrkfdn/ncspot#107]
i really like the idea of ncspot, and i would really like to be able to use it, but as it is right now, i cant really enjoy it.

am i missing something here? i have tried different terminals with different fonts but nothing seems to fix this
![ncspot](https://user-images.githubusercontent.com/56771914/69143258-d0bcea00-0ac8-11ea-95a1-92db18f65f31.png)

**Comment by hrkfdn** [comment]
Mmhh.. what OS is this?

You could try a different curses backend or turn off nerdfont.

**Comment by nB82DXcx8L2jrXyw** [comment]
> Mmhh.. what OS is this? 

im running arch 
> What is your `$TERM` set to?

`user@archdt:~$ printenv | grep $TERM`
`TERM=rxvt-unicode-256color`

> You could try a different curses backend or turn off nerdfont.

what does nerdfont mean? the font i have in my terminal is inconsolata, do you have any suggestions on what would work if thats the problem?

**Comment by hrkfdn** [comment]
I see. What is your locale set to? You will probably need to use a UTF-8 locale, e.g. try setting `LC_CTYPE=en_US.UTF-8`.

**Comment by nB82DXcx8L2jrXyw** [comment]
> I see. What is your locale set to? You will probably need to use a UTF-8 locale, e.g. try setting `LC_CTYPE=en_US.UTF-8`.

before my previous post it was set to `sv_SE.UFT-8`, but after writing that post i tried set it to `en_US.UFT-8`, which didnt make any difference. but i tried your command too and its still the same :(

**Comment by hrkfdn** [comment]
Hmm, I would love to help you, but I have no idea how to reproduce this. In my urxvt with `TERM=rxvt-unicode-256color` and `LANG=en_US.UTF-8` it looks fine. Urxvt.font is set to `-*-clean-medium-r-normal-*-12-*-*-*-*-*-*-*`

**Comment by nB82DXcx8L2jrXyw** [comment]
> Hmm, I would love to help you, but I have no idea how to reproduce this. In my urxvt with `TERM=rxvt-unicode-256color` and `LANG=en_US.UTF-8` it looks fine. Urxvt.font is set to `-*-clean-medium-r-normal-*-12-*-*-*-*-*-*-*`

i really appreciate your effort trying to help me. unfortunately i dont have any other device atm to try on.

**Comment by nB82DXcx8L2jrXyw** [comment]
@hrkfdn i've just figured out this seems to be a rust problem, the rust tui's i've tried all have the same problem. i just wanted to get back to you with this info just so that u know its not specific to your application!

**Comment by codabrink** [comment]
I had this issue on the latest Manjaro. I think this may be a Manjaro bug. It's not setting a locale.

To fix this issue for me I uncommented `en_US.UTF-8 UTF-8` in `/etc/locale.gen`, ran `sudo locale-gen`, and and restarted.
