### ISSUE TITLE
(Some) Navigation Keys not working in context menu

### ISSUE THREAD

**Issue by zenhaeus** [hrkfdn/ncspot#108]
When I open the context menu on a song the navigation keys that I use in the main screens are not working (j, k, Backspace). Is this intentional?

**Comment by Zocker1999NET** [comment]
@hrkfdn As I have not worked with ncurses yet, in your opinion, is this is a bug which can be solved in this project or should it be considered to be a bug of ncurses?

**Comment by dann-merlin** [comment]
Same goes for the help menu.
