### ISSUE TITLE
Support using proxies

### ISSUE THREAD

**Issue by freijon** [hrkfdn/ncspot#109]
I'm trying to use ncspot on Windows, but we have a corporate firewall that goes through a proxy.
I tried setting the environment variables **https_proxy** and **http_proxy**, with no luck. 

From the librespot wiki I see that there is the following option:

Option |   | proxy | Use a proxy for resolving the access point. Proxy should be an HTTP proxy in the form http://ip:port, and can also be passed using the HTTP_PROXY environment variable.
-- | -- | -- | --

However, it doesn't seem that I can control how librespot is used to connect to Spotify

Is there anything else needed on the ncspot side to make the app work with proxies?

**Comment by hrkfdn** [comment]
You should now be able to set a proxy in the config file :)

**Comment by freijon** [comment]
That was quick, thanks!

I gave it a try and set the proxy in the config.toml file. Unfortunately, it doesn't seem to work. After several seconds I get this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Hyper(Error(Connect, Os { code: 10060, kind: Timed
Out, message: "A connection attempt failed because the connected party did not properly respond after a period of time, or estab
lished connection failed because connected host has failed to respond." })), "https://api.spotify.com/v1/me/")', src\libcore\res
ult.rs:1165:5
```
