### ISSUE TITLE
Basic playlist support

### ISSUE THREAD

**Issue by hrkfdn** [hrkfdn/ncspot#11]
Implement loading/saving of playlists. Basic features that we want:

- [x] ~As Spotify supports playlist folders, we need a way to hierarchically navigate through folders (maybe with [cursive_tree_view](https://github.com/BonsaiDen/cursive_tree_view)?)~ ([the API doesn't offer folder information](https://github.com/spotify/web-api/issues/38#issuecomment-396925978))
- [x] Load and display playlists
- [x] Playlists can be queued
- [x] Playlists should only be loaded on start-up
- [x] .. and if explicitly requested by user
- [x] Cache loaded playlists for next startup. Use `snapshot_id` field to check if a cached playlist's tracklist needs to be updated.
- [x] Queues can be saved to playlists
- [x] Playlists can be deleted

The playlist view should be an extra screen (like Search/Queue).

**Comment by norcalli** [comment]
You could take a look at my branch from an older version I made on the day you released it where I implemented a tree view for playlists. I included cursive-tree-view since I made some changes, but you can probably work around it (and also one of them was merged). https://github.com/norcalli/ncspot

**Comment by barzamin** [comment]
Ideally there'd be some way of accessing your "saved songs" library as a playlist, too.

**Comment by hrkfdn** [comment]
@norcalli Some solid ideas in there. The codebase has changed quite a bit, but I might implement some of those ideas.

**Comment by norcalli** [comment]
@barzamin "Saved songs" has a special endpoint, so it is definitely accessible. It's probably best served on a separate screen with one long playlist and the ability to search entries in it. Which reminds me, that I was going to add searching within playlists after pre-caching all of the entries. I have quite a lot of songs, but even still, 3000 entries is not that much space in memory on a modern computer.

**Comment by norcalli** [comment]
@hrkfdn oh yeah one thing that took the longest to implement that I forgot to add was to immediately play a song when you do an "append to queue" action if nothing is currently playing (as in a stopped state vs play/pause).

**Comment by im-n1** [comment]
Not sure if this fits in here but its related to playlists.
I'm missing a feature where I can browse tracks of a playlist. Now I can only queue whole playlist not certain tracks.

**Comment by hrkfdn** [comment]
@im-n1 It's on my list :)

**Comment by Ads20000** [comment]
Is there any way of using https://github.com/mikez/spotify-folders ( referenced at https://github.com/spotify/web-api/issues/38#issuecomment-431600563 ) to get playlist folders to show up in ncspot? Could ncspot grow a feature to import the output of spotify-folders or something (I'm not a dev so sorry if I'm speaking no sense!)
