### ISSUE TITLE
ncspot using a lot of CPU in macOS 10.13.6 with PortAudio

### ISSUE THREAD

**Issue by arponero** [hrkfdn/ncspot#110]
Hi all,

After cloning the last version on github and running:
`cargo run --no-default-features --features portaudio_backend,cursive/pancurses-backend` the ncspot application starts fine. Just after start playing any song, the CPU goes to almost 100% and then, after a couple of seconds, goes down to around 30%, which keeps very constant.

I would appreciate any advice to fix this issue.

Best,
Jaime

**Comment by hrkfdn** [comment]
`cargo run` builds a debug build by default. Try passing `--release`.

**Comment by arponero** [comment]
> Hey Jaime,
> 
> `cargo run` builds a debug build by default. Try passing `--release`.

Niiiiice, that was the problem! Now the CPU is around 3%, which is much more reasonable.

Thank you for the support, and thank you for this really nice work!

Best,
Jaime
