### ISSUE TITLE
Wrong D-Bus Object Path

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#1103]
**Describe the bug**
I'm not sure if this is a bug with ncspot or with d-spy but d-spy does correctly report the mpris implementation for FireFox, so I think it's an issue with the introspection implementation of ncspot. The actual object path can correctly be used at `/org/mpris/MediaPlayer2`, but the introspection returns `/org/mpris/MediaPlayer2/org/mpris/MediaPlayer2` as object path. At least that's what I think this is (I just started playing around with D-Bus today, that's how I noticed it).

**To Reproduce**
1. Open ncspot
2. Open d-spy
3. Go to the ncspot service
4. Look at the object path (compared to the one reported by other media players and the one from the mpris specification)

**Expected behavior**
I think it should report `/org/mpris/MediaPlayer2`.

**Screenshots**
![image](https://user-images.githubusercontent.com/48214567/228350485-c989036a-f66b-430b-ac91-721bcc21a0f9.png)

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Alacritty
 - Version: 12.0 
 - Installed from: Pacman

**Comment by hrkfdn** [comment]
Yeah, can definitely reproduce this. I have spent the whole evening trying to spot the culprit but I can't find it. I've compared it to other MPRIS DBus implementations but no idea how the object path ends up like that :confused:

**Comment by ThomasFrans** [comment]
Same thing here. I've spent about 2 hours looking into this and I can't find what it is. It's such a weird issue because it literally adds the same name twice. If you edit the name, it takes the new name and adds it twice (I thought maybe dbus-rs was doing some magic by using the .desktop file and one of the paths was automatically generated, but that isn't true). Maybe mark this one as help wanted?

**Comment by hrkfdn** [comment]
I just took this as a cue to redo the implementation :smile:

It was on my list anyway and `zbus` looks quite nice!

**Comment by ThomasFrans** [comment]
I was going to add that I considered rewriting the mpris code in the previous comment 😄 It could use a rewrite indeed.

Anyways, I've heard that there are problems with zbus on the BSD's. I don't know the specifics of it, but it might be worth looking into that...

**Comment by hrkfdn** [comment]
Oh thanks, that's a very good point!

**Comment by ThomasFrans** [comment]
It might have been those then. Like I said, I don't know any specific details. Someone on another project where I wanted to propose a feature using D-Bus asked me not to use zbus as it had problems on BSD. That's a half year ago I think.

**Comment by ThomasFrans** [comment]
Just for reference: https://github.com/Builditluc/wiki-tui/issues/49#issuecomment-1178877946

(Haven't implemented that search provider yet... :grimacing: )

**Comment by hrkfdn** [comment]
Hmm okay, thanks. I was able to build the crate on my OpenBSD machine just now. Maybe the issue was fixed or it only happens on NetBSD.
