### ISSUE TITLE
The first 17 songs from my Liked playlist are not appearing in ncspot

### ISSUE THREAD

**Issue by colemickens** [hrkfdn/ncspot#1109]
**Describe the bug**

I haven't used `ncspot` on this computer before, so I don't think it's a caching issue.

Screenshot appears below

**To Reproduce**
1. Use `ncspot`
2. Look for keybindings on the readme, wiki, finally look in `doc/`
3. Realize 'o' is how to navigate into a playlist.
4. Notice that it's not accurate.

**Expected behavior**
The playlist to load correctly.

**Screenshots**
![screenshot-1680485018](https://user-images.githubusercontent.com/327028/229391617-3ed5df81-e397-42e1-9a5b-6463e742cce9.png)

Note that ncspot's view of the playlist starts at what Spotify shows as Track 18.
Sorry about the screenshot, I promise it's on "Spotify Liked Songs" and scrolled to the top.

**System (please complete the following information):**
 - OS: NixOS
 - Terminal: alacritty
 - Version: 0.13.0
 - Installed from: nixpkgs

**Backtrace/Debug log**
n/a

**Additional context**
n/a

**Comment by Bettehem** [comment]
If you have just recently added these tracks to your library and haven't reopened ncspot or refreshed ncspot, it could explain why you don't see the tracks.
You could try pressing Shift+U in ncspot which will update your library or just restarting the program. You should see something like `[U]` at the bottom right of the window while it's fetching updates and when it disappears, you should have the latest changes to your library

**Comment by colemickens** [comment]
As I mentioned, I've not used Spotify on this computer previously. I also already tried refreshing, and did so again just now. It still looks the same.

**Comment by colemickens** [comment]
Maybe Spotify changed their API? These tracks seems to show under "Tracks" but not m liked songs?

**Comment by colemickens** [comment]
Oh, I'm dumb, apparently I have an old copy of my Liked tracks listed as "Spotify Liked Songs".
