### ISSUE TITLE
Alphabetic sorting of Albums

### ISSUE THREAD

**Issue by d-vb** [hrkfdn/ncspot#111]
Currently in Library/Albums items don't seem to be sorted at all. It would be nice to sort albums by 1. artist, 2. album year, 3. album name. I think this is also the default sorting in Spotify.

**Comment by hrkfdn** [comment]
At the moment the order in which the items were sent from the server is preserved, which I'm guessing is chronological based on the time the items were saved. The ordering you propose makes much more sense, though.

**Comment by hrkfdn** [comment]
I have added sorting. It currently only uses the first album artist to keep the order consistent. Let me know what you think.

**Comment by d-vb** [comment]
Thanks, that's a big improvement.
