### ISSUE TITLE
Missing crate "sys" when uses cargo build

### ISSUE THREAD

**Issue by bocWang** [hrkfdn/ncspot#1112]
I use cargo build --release and get this bug:

 Compiling hyper-tls v0.5.0
   Compiling nix v0.26.2
   Compiling uds_windows v1.0.2
   Compiling ordered-stream v0.2.0
   Compiling clipboard-win v2.2.0
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\lenovo\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?
   |
   = help: consider adding `extern crate sys` to use the `sys` crate

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\lenovo\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:27:9
   |
27 | pub use sys::tty::{is_tty, get_tty};
   |         ^^^ maybe a missing crate `sys`?
   = help: consider adding `extern crate sys` to use the `sys` crate

error[E0433]: failed to resolve: maybe a missing crate `sys`?
 --> C:\Users\lenovo\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:5:5
  |
5 | use sys::tty::get_tty;
  |     ^^^ maybe a missing crate `sys`?
  |
  = help: consider adding `extern crate sys` to use the `sys` crate

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\lenovo\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:28:5
   |
28 | use sys::attr::{get_terminal_attr, raw_terminal_attr, set_terminal_attr};
   |     ^^^ maybe a missing crate `sys`?
   |
   = help: consider adding `extern crate sys` to use the `sys` crate

error[E0432]: unresolved import `sys`
  --> C:\Users\lenovo\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:29:5
   |
29 | use sys::Termios;
   |     ^^^ maybe a missing crate `sys`?
   |
   = help: consider adding `extern crate sys` to use the `sys` crate

   Compiling hex v0.4.3
   Compiling platform-dirs v0.3.0
   Compiling cursive_buffered_backend v0.6.1
   Compiling notify-rust v4.8.0
   Compiling clipboard v0.5.0
   Compiling reqwest v0.11.16
Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `termion` due to 5 previous errors
warning: build failed, waiting for other jobs to finish...

It looks like there's a missing sys crate，how can I do？

**Comment by dirktinno** [comment]
I think I figured this out, the crate termion is only supported on *nix systems, so on Windows it can't find that sys library. Basically, no Windows support as of right now as ncspot depends on that.

**Comment by Bettehem** [comment]
You need to specify the features used when compiling on windows, see the instructions here:
https://github.com/hrkfdn/ncspot/blob/main/doc/developers.md#compiling
