### ISSUE TITLE
future-incompat-report

### ISSUE THREAD

**Issue by 0323pin** [hrkfdn/ncspot#1114]
**Describe the bug**
Building 0.13.1 with Rust 1.68.2

You might already be aware of this but leaving it here FYI,
```
warning: the following packages contain code that will be rejected by a future version of Rust: rustc-serialize v0.3.24
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

**Comment by hrkfdn** [comment]
Thanks :), I'm aware, but it requires a new `chrono` release which isn't out yet. Details can be found here: https://github.com/chronotope/chrono/issues/865

**Comment by 0323pin** [comment]
I thought you'd be aware. Thought, are you sure is only `chrono`, https://github.com/aome510/spotify-player/commit/dc36b071f782fc3ded959e7f5c6c059531eeaf0e ?

Didn't dig into this at all so, I might be wrong.

**Comment by hrkfdn** [comment]
Ah, could be. In any case they'd have to update/release first :( I'll keep observing! :)

**Comment by 0323pin** [comment]
Yeah :(

Anyway, for now all is good. Package updated on NetBSD, http://mail-index.netbsd.org/pkgsrc-changes/2023/04/06/msg271969.html

:)

**Comment by hrkfdn** [comment]
I believe this is not an issue anymore as now there is no dependency on `rustc-serialize`.
