### ISSUE TITLE
Stuttering on Windows 11

### ISSUE THREAD

**Issue by aayushborkar14** [hrkfdn/ncspot#1117]
**Describe the bug**
While playing any song, a stuttering/cracking sound occurs every few seconds.

**To Reproduce**
1. Play any song
2. Listen to it

**Expected behavior**
No stuttering is expected. The official Spotify client works fine.

**System (please complete the following information):**
 - OS: Windows 11
 - Terminal: Windows Terminal (PowerShell 7.3.3)
 - Version: 0.13.1
 - Installed from: zip from releases

**Additional context**
While playing on speaker no stuttering is heard (or might just not be noticeable).
The issue only occurs when using headphones., and that too only on one side at a time (L/R).
No stuttering with official client though.

**Comment by benmanone** [comment]
Same for me on MacOS. Seems to be something to do with librespot.

**Comment by bogdan-calapod** [comment]
Are you running the Windows executable directly, or running the Linux version via WSL ? I don't have any problems in the former case, but do experience crackling and pauses on the latter one.
