### ISSUE TITLE
Playerctl support

### ISSUE THREAD

**Issue by shyim** [hrkfdn/ncspot#112]
Toggle things with https://github.com/altdesktop/playerctl

```
playerctl pause
No players found
```

**Comment by hrkfdn** [comment]
`playerctl` should work, as it uses MPRIS which is supported by ncspot. Did you compile ncspot with the mpris feature enabled?

**Comment by shyim** [comment]
Okay its not enabled in Nixos by default. Sorry :see_no_evil:
