### ISSUE TITLE
Credentials related question

### ISSUE THREAD

**Issue by kirk781** [hrkfdn/ncspot#1124]
ncspot, atleast on Linux, stores the credentials in a OAuth generated file at /.cache/ncspot/librespot/credentials.json file. What I am intrigued about; and this might not be strictly related to ncspot in general; is how many times that OAuth credentials be used? Say, ncspot on my PC is already using it and someone tries to utilize it to authorize via my Spotify Account via another login, will it work a second time as well?

**Comment by hrkfdn** [comment]
Not sure if I fully understood, but that token is not limited to a single usage, i.e. I can run multiple ncspot instances on my computer at the same time.
