### ISSUE TITLE
High quality streaming

### ISSUE THREAD

**Issue by KennethAshley** [hrkfdn/ncspot#113]
First off i'd like to say great work! ncspot has replaces the high usage Spotify app for me.

The only thing i'd like to know is what is the quality that is streamed by ncspot? I'd really like to be able to set the quality to the highest level possible. 

Thanks!

**Comment by hrkfdn** [comment]
Hey Kenneth,

ncspot streams at the maximum bitrate by default :)

**Comment by KennethAshley** [comment]
You are my hero. Thanks
