### ISSUE TITLE
ncspot bails out with "Channel closed" instead of  playing any song

### ISSUE THREAD

**Issue by hanslub42** [hrkfdn/ncspot#1139]
When running the newest `ncspot` (`0.13.1`), the program starts up normally, but when selecting any song to play, it bails out with `Error: "channel closed"`

The problem disappears when I build from any revision that is earlier than b0db0da ("Rewrite MPRIS implementation using zbus")

When comparing debug logs (obtained with `-d <logfile>`) between the working (i.e. pre- b0db0da)  and non-working versions there is no readily apparent difference, except that with the faulty `ncspot` the log suddenly stops after the second line below:

```
[2023-05-01][23:36:04] [librespot_playback::player] [INFO] <Dufay: Nuper rosarum flores> (407306 ms) loaded
[2023-05-01][23:36:04] [ncspot] [TRACE] event received: Paused(3.381s)
[2023-05-01][23:39:19] [ncspot] [INFO] Using cached credentials
```

System: Linux (Gentoo)
installed with `git clone` and then `cargo build`
running dbus 1.15.4

(Apropos `dbus`: `dbus-monitor` shows quite a bit of activity with the working `ncspot` version, but remains completely silent with the non-working one)

**Comment by hanslub42** [comment]
This is probably a configuration problem on my part: 

```bash
[hlub@tatra ((b0db0da...) *)] .../target/debug > ./ncspot       
Connecting to Spotify..
Error: "channel closed"
[hlub@tatra ((b0db0da...) *)] .../target/debug > echo $DBUS_SESSION_BUS_ADDRESS

[hlub@tatra ((b0db0da...) *)] .../target/debug > dbus-launch zsh               
[hlub@tatra ((b0db0da...) *)] .../target/debug > echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/tmp/dbus-wOsKxEpCQg,guid=69965afc7a16ff380f806d0764510779
[hlub@tatra ((b0db0da...) *)] .../target/debug > ./ncspot                      
Connecting to Spotify..
# Plays music
```

Closing.

**Comment by hrkfdn** [comment]
Thanks for the report. While you're right that the missing DBus session was the problem here, I think ncspot should handle it without crashing. I have committed a small change that should help with this.

**Comment by hanslub42** [comment]
Thanks! I can confirm that this works even without a valid $DBUS_SESSION_BUS_ADDRESS
