### ISSUE TITLE
cargo install fails, could not compile

### ISSUE THREAD

**Issue by cgahr** [hrkfdn/ncspot#1146]
EDIT: running `cargo install ncspot --locked' fixes the issue, thanks @XK9274 

**Describe the bug**
running `cargo install ncspot` fails with the following error:

```
   Compiling ncspot v0.13.1
error[E0599]: no method named `as_millis` found for struct `Duration` in the current scope
  --> /home/cgahr/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.1/src/model/episode.rs:36:40
   |
36 |             duration: episode.duration.as_millis() as u32,
   |                                        ^^^^^^^^^ method not found in `Duration`

error[E0599]: no method named `as_millis` found for struct `Duration` in the current scope
  --> /home/cgahr/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.1/src/model/episode.rs:52:40
   |
52 |             duration: episode.duration.as_millis() as u32,
   |                                        ^^^^^^^^^ method not found in `Duration`

error[E0599]: no method named `as_millis` found for struct `Duration` in the current scope
  --> /home/cgahr/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.1/src/model/track.rs:62:38
   |
62 |             duration: track.duration.as_millis() as u32,
   |                                      ^^^^^^^^^ method not found in `Duration`

error[E0599]: no method named `as_millis` found for struct `Duration` in the current scope
  --> /home/cgahr/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.1/src/model/track.rs:99:38
   |
99 |             duration: track.duration.as_millis() as u32,
   |                                      ^^^^^^^^^ method not found in `Duration`

error[E0599]: no method named `as_millis` found for struct `Duration` in the current scope
   --> /home/cgahr/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.1/src/model/track.rs:138:38
    |
138 |             duration: track.duration.as_millis() as u32,
    |                                      ^^^^^^^^^ method not found in `Duration`

error[E0308]: mismatched types
   --> /home/cgahr/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.1/src/spotify_api.rs:162:17
    |
159 |             api.playlist_add_items(
    |                 ------------------ arguments to this method are incorrect
...
162 |                 position,
    |                 ^^^^^^^^ expected struct `Duration`, found `i32`
    |
    = note: expected enum `std::option::Option<chrono::Duration>`
               found enum `std::option::Option<i32>`
note: associated function defined here
   --> /home/cgahr/.cargo/registry/src/github.com-1ecc6299db9ec823/rspotify-0.11.7/src/clients/oauth.rs:300:14
    |
300 |     async fn playlist_add_items<'a>(
    |              ^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `ncspot` due to 6 previous errors
error: failed to compile `ncspot v0.13.1`, intermediate artifacts can be found at `/tmp/cargo-installHFR8eF`
```

**To Reproduce**
run `cargo install ncspot`

**Expected behavior**
install `ncspot`

**System (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Terminal: zsh
 - Version: v0.13.1
 - Installed from: cargo

**Comment by XK9274** [comment]
I had this recently too and thought it was my compile, I tried a lot of things and i think what fixed it was by adding --locked to the end of the cargo build:

```cargo install ncspot --locked```

**Comment by n3f** [comment]
Had the same issue (but on macos), and I deleted a bunch of files (`rm -rf target xtask misc images doc Cargo.lock Cargo.toml`) and ran `git reset --hard` and it worked. 🤷 YMMV

**Comment by lelajels** [comment]
I'm getting the same errors while updating **ncspot** via cargo install on Fedora 38.

> I had this recently too and thought it was my compile, I tried a lot of things and i think what fixed it was by adding --locked to the end of the cargo build:
> 
> `cargo install ncspot --locked`

@XK9274 Thanks for this workaround. That helps to get the installation done for sure. 

The compilation process complains about a few packages though. I'm not sure if the warnings below are useful for the resolution of this issue but I'm posting them here just in case:

`warning: package crossbeam-channel v0.5.7 in Cargo.lock is yanked in registry crates-io, consider running without --locked`
`warning: package enumflags2 v0.7.6 in Cargo.lock is yanked in registry crates-io, consider running without --locked`
`warning: the following packages contain code that will be rejected by a future version of Rust: rustc-serialize v0.3.24`

**Comment by XK9274** [comment]
> I'm getting the same errors while updating **ncspot** via cargo install on Fedora 38.
> 
> > I had this recently too and thought it was my compile, I tried a lot of things and i think what fixed it was by adding --locked to the end of the cargo build:
> > 
> > `cargo install ncspot --locked`
> 
> @XK9274 Thanks for this workaround. That helps to get the installation done for sure. 
> 
> The compilation process complains about a few packages though. I'm not sure if the warnings below are useful for the resolution of this issue but I'm posting them here just in case:
> 
> `warning: package crossbeam-channel v0.5.7 in Cargo.lock is yanked in registry crates-io, consider running without --locked`
> `warning: package enumflags2 v0.7.6 in Cargo.lock is yanked in registry crates-io, consider running without --locked`
> `warning: the following packages contain code that will be rejected by a future version of Rust: rustc-serialize v0.3.24`

Hey no worries glad that worked! I get those errors now too but I think they're unrelated to the original issue. Looks like the original errors are something to do with chrono but there's not much out there that I could find re: a resolution.

**Comment by cgahr** [comment]
running `cargo install ncspot --locked' fixes the issue, thanks @XK9274
