### ISSUE TITLE
Volume control from ncspot

### ISSUE THREAD

**Issue by tsujp** [hrkfdn/ncspot#115]
Would it be possible to add volume control from within ncspot itself?

**Comment by hrkfdn** [comment]
Good idea, I just implemented this. Use `-` or `+` to decrease/increase the volume.

**Comment by tsujp** [comment]
@hrkfdn fantastic! Would you be able commit the current stable codebase and tag for release? Currently the highest version is `0.1.1` from November 24.

**Comment by tsujp** [comment]
@hrkfdn I just changed to the ncxspot-git AUR package, and it does indeed change volume but it's not linear or there is a problem on my end? I'm using alsa and pulseaudio and from ~100-8% there is a difference but it's almost nothing, then from 0% to 7% it ramps quite a lot. I'm still checking other things but are you able to confirm/deny sanity?

**Comment by tsujp** [comment]
I have no Rust development environment setup here as I have never done anything involving that language, but since it's topical to `+` and `-` for volume control - would it be possible to have an option or default behaviour that maps `=` to `+` as well so that the keys beside `0` on the number row also work without having to use `shift`?

**Comment by hrkfdn** [comment]
Could you check if it's better?

Regarding the mapping I'm hoping this can be adjusted by user-changeable bindings soon. I can see how having to use Shift is a nuisance, on the other and `+` and `-` make a lot of sense. Hmm.. :thinking:

**Comment by tsujp** [comment]
I can give it a check later today. With regards to `+` and `-` it makes perfect sense, it's only because my keyboard as it stands does not have a number pad, I suppose it'd also stand for laptop keyboards as well. That being said too, how often does one really need to change volume specifically for `ncspot`, most of the time you either have your background, foreground music levels and then are adjusting master. More of a QoL thing.

**Comment by tsujp** [comment]
@hrkfdn much better control, 50 to 100% has a nice range, sub 50% is almost unnecessary as once you get to about ~30% its very, very quiet essentially muted for all practical purposes.
