### ISSUE TITLE
would it be possible to implement a fifo output like mpd has?

### ISSUE THREAD

**Issue by o0mak0o** [hrkfdn/ncspot#116]
mpd has the option to output the audiostream into a file via fifo
```
audio_output {
	type                    "fifo"
	name                    "my_fifo"
	path                    "/tmp/mpd.fifo"
	format                  "44100:16:2"
}
```
cli-visualizer makes use of this, there is also an option to use alsa instead but this seems to be somewhat experimental by now. I would really love to use cli-visualizer in combination with ncspot. So I was wondering what it would take to implement this in ncspot?

**Comment by tsujp** [comment]
Would this also be useful for something like Polybar to get the currently playing track, and progress on display there as a module?

**Comment by o0mak0o** [comment]
> Would this also be useful for something like Polybar to get the currently playing track, and progress on display there as a module?
If I understand this article correctly, then yes this should also be useful for polybar.
https://github.com/polybar/polybar/wiki/Inter-process-messaging

**Comment by hrkfdn** [comment]
Hey there,

those would be too different pipes. One for metadata and the other for raw audio data. The latter is on my list, the former I'm a little uncertain of. While I understand the need to pipe it into `cli-visualizer`, I don't want to encourage ripping Spotify audio content. Another problem is that librespot only allows one playback backend at the same time.

**Comment by o0mak0o** [comment]
Hello, thanks for the quick response. I understand your reasoning behind not wanting to encourage ripping Spotify audio content. Case close, I will try to get it to work with alsa :)

**Comment by pniedzwiedzinski** [comment]
@mak1A4 it works with alsa?

**Comment by hrkfdn** [comment]
@mak1A4 There is now a backend setting which allows you to use the `pipe` and `subprocess` backend. Maybe this is of use to you.

**Comment by Barbarossa93** [comment]
@hrkfdn could you elaborate on how to use the `pipe` or `subprocess` backends? I'm unsure of how this would work with creating a fifo file

**Comment by hrkfdn** [comment]
@Barbarossa93  `pipe` will pipe the raw audio to the file specified in `backend_device` (file needs to be created before). `subprocess` will open a child process set in `backend_device` and pipe the audio output to this process.

**Comment by Barbarossa93** [comment]
Thanks, that helps immensely. Would you happen to be aware of a way to duplicate a stream? I tried using the `subprocess` backend with `tee /tmp/pipe1.fifo /tmp/pipe2.fifo` as the backend device and unfortunately `tee` is unable to duplicate the stream quickly enough (i.e., output is garbled for both pipe listeners compared to just one pipe and listener).

**Comment by hrkfdn** [comment]
@Barbarossa93 Hey, sorry, never done that. Alternatively, you could try piping it to a file and then `tailing it to another, but `tail` would have to be running before playback or you may miss parts. Also just an idea, never tried this.

**Comment by Bettehem** [comment]
I have been using the current cli-visualizer with pulseaudio and JACK and it seems to be working fine. I had to modify the cli-visualizer config file first for it to work though
