### ISSUE TITLE
Unable to login on free account.

### ISSUE THREAD

**Issue by SyedFasiuddin** [hrkfdn/ncspot#1164]
I just brew installed it and tried to login, I do not have premium account and I get this on the TUI and the following on the terminal, I want to know why this limitation exists.

                  ┌────────────────────────────────────────────────────┐
                  │ Connection error:                                  │
                  │ Login failed with reason: Premium account required │
                  │                                                    │
                  │                                               <Ok> │
                  └────────────────────────────────────────────────────┘

```
~ ncspot
Error: "Didn't obtain any credentials"
```

**Comment by hrkfdn** [comment]
Hey, see also: https://github.com/librespot-org/librespot/issues/261
