### ISSUE TITLE
Opening a second instance of ncspot results in a crash

### ISSUE THREAD

**Issue by jackkinsey** [hrkfdn/ncspot#1183]
**Describe the bug**
Opening ncspot when an instance is already running results in a crash with the error:
```
Error: "channel closed"
```

**To Reproduce**
1. Run ncspot
2. Open another terminal and run it again

**Expected behavior**
A better error message would be less confusing; it took me several minutes to realize this was the issue (I had forgotten I already had ncspot running in another workspace...)

**System (please complete the following information):**
 - Linux
 - Version: 0.13.1
 - Installed from: AUR

**Comment by hrkfdn** [comment]
Does this also happen with 0.13.2? If so, could you provide a backtrace?

**Comment by jackkinsey** [comment]
Ah, indeed it does not. Sorry, should've thought to update first! Thanks.
