### ISSUE TITLE
Proxy connection doesn't work

### ISSUE THREAD

**Issue by freijon** [hrkfdn/ncspot#119]
On Windows I set a HTTP proxy in config.toml. Loggin in seems to work, but then a black window appears which doesn't respond. After a while, this output shows up (also see the [output log](https://gist.githubusercontent.com/freijon/b69d68ac70e85226b7de36f846daa182/raw/6a05722f43204c555370dd6f0f053517b04f3c5a/gistfile1.txt)):

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Hyper(Error(Connect, Os { code: 10060, kind: TimedOut, message: "A co
nnection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to
respond." })), "https://api.spotify.com/v1/me/")', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:61
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:373
  12: rust_begin_unwind
             at src\libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src\libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src\libcore/result.rs:1165
  15: rspotify::spotify::client::Spotify::internal_call
  16: rspotify::spotify::client::Spotify::get
  17: rspotify::spotify::client::Spotify::me
  18: rspotify::spotify::client::Spotify::current_user
  19: ncspot::spotify::Spotify::current_user
  20: ncspot::library::Library::new
  21: ncspot::main
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:48
  24: std::panicking::try::do_call
             at src\libstd/panicking.rs:287
  25: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:78
  26: std::panicking::try
             at src\libstd/panicking.rs:265
  27: std::panic::catch_unwind
             at src\libstd/panic.rs:396
  28: std::rt::lang_start_internal
             at src\libstd/rt.rs:47
  29: main
  30: _tmainCRTStartup
  31: mainCRTStartup
  32: wvline_set
  33: wvline_set
```

**Comment by hrkfdn** [comment]
That error message just states a timeout. Are you sure your proxy settings are correct?

**Comment by freijon** [comment]
Yes, as you can see in the log (see gist) it seems that the authentication works and an access token is handed out by Spotify (these steps all need a network connection afaik). But some other network task seems to fail (timeout) afterwards.

**Comment by hrkfdn** [comment]
Hmm, you're right. The proxy is not set for the rspotify crate, which queries the Spotify HTTP API for metadata resolution (playlists, track/album/artist info, etc.). Unfortunately rspotify doesn't expose an API to set the proxy and only allows setting the proxy via environment variables for now.

We could write the proxy settings from configuration into the respective env variables (`HTTP_PROXY` or `HTTPS_PROXY`), but this will override system proxy settings, which should probably take precedence. It's a little messy, but can be worked around.

**Comment by nymann** [comment]
I would advise against overwriting system proxy env vars, there should not be a need for this if it's already set by the user.

**Comment by hrkfdn** [comment]
It would only be set within the execution environment of ncspot and only if it's not already set.

In the case of system proxy environment vars already being set, they would have priority, e.g. as described in https://github.com/hrkfdn/ncspot/issues/118. It's the only way this can be solved with the current interface rspotify provides.

The alternative is a change in the rspotify API.

**Comment by freijon** [comment]
In my case I had both ENV vars set accordingly, still it didn't work and caused the timeout. But that was on Windows, not sure if that makes a difference...
