### ISSUE TITLE
Enable link time optimization for smaller builds

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#1192]
**Is your feature request related to a problem? Please describe.**
ncspot release builds are bigger than I would expect them to be. 20MB isn't gigantic, but it's bigger than I would expect, considering Alacritty for example only uses 6MB. Alacritty probably does a lot of dynamic linking so it might not be the best example, but 20MB still feels rather big.

**Describe the solution you'd like**
A pretty good solution is to enable LTO during compilation. It drastically shrinks the binary from 21MB down to 14MB. Again, 21MB isn't that big, but most of the time ncspot is shipped as a binary which means the longer compile times would only be a drawback during the single compilation to create the package. It would only be beneficial for actual users themselves.

There is also "thin" lto which decreases the size to 17MB instead of 14MB. The linking time isn't that much shorter, so I don't think "thin" would make that much sense.

**Additional context**
I created a PR before that suggested changes to the build profiles and this was one of them. The PR was closed as it also removed the debug info in release builds, which was something that wasn't wanted. That's why I'm making this separate issue to discuss LTO, as I think it would only have a positive impact for release builds without any drawbacks.

I know I might be crazy to complain about 7MB, but when the program is already written in a well optimized, compiled language, it might as well go all the way and try to be as efficient as possible, especially considering the size decrease is completely free :smile:

**Comment by hrkfdn** [comment]
I think if this can be done without adding to much complexity to the build process or without losing the debug symbols, it's okay. I'm also wondering how many even use the release builds, I'd imagine a lot of people use distribution builds or compile themselves, but not sure..

**Comment by ThomasFrans** [comment]
Since lto is enabled under the release profile, everyone should benefit from it, as it will work whenever ncspot is compiled using the release profile. Distribution builds would automatically contain the smaller binary. I also made sure to add an extra 'optimized' profile so people can choose to 'opt out' of these options, as they increase linking times considerably (3x on my pc).
