### ISSUE TITLE
Context menu opens after significant delay

### ISSUE THREAD

**Issue by FlynnD273** [hrkfdn/ncspot#1225]
**Describe the bug**
When I press O or S-O or right-click, the context menu for a track takes about a second to appear. I'm not sure if this is just an issue with my computer or not though. It doesn't seem to be an issue with the terminal emulator, I tried both Kitty with Tmux and gnome-terminal. The behaviour remained consistent between the two. 

**To Reproduce**
1. Press O while selecting a track. 

**Expected behavior**
The context menu opens immediately

**System (please complete the following information):**
 - OS: Linux (Ubuntu on Gnome)
 - Terminal: Kitty
 - Version: master branch
 - Installed from: built from source

**Comment by hrkfdn** [comment]
Hey! Thanks for the report. I have merged a fix in `main` which should speed things up, can you confirm this?

**Comment by FlynnD273** [comment]
Yup! There's still a slight delay but that's to be expected when fetching stuff from the internet. It's significantly faster now though.

**Comment by rizzini** [comment]
I came here to find out if there's some open issue on the matter. Apparently, the delay was a bit worse a while ago. Is there any plan to make the delay disappear altogether?
