### ISSUE TITLE
Sign out All on Spotify Website Crash

### ISSUE THREAD

**Issue by 123outerme** [hrkfdn/ncspot#1253]
**Describe the bug**
I signed out all logins of my Spotify account via their website while ncspot was currently running. When this happened, my shell entirely broke. After every attempted input into the terminal it would say "/usr/bin/bash: input/output error". When I rebooted my system it failed to boot. I ended up having to reinstall my entire OS, which turned out OK since I was just testing on it and didn't lose anything.

**To Reproduce**
1. Launch ncspot, sign into your account
2. Open up Account Settings on the Spotify website (click on your profile picture > Account)
3. Click "Sign Out Everywhere"
4. Exit ncspot and attempt to run any command in the terminal

**Expected behavior**
I'm not sure how it should be handled when the user is signed out while ncspot is running, this depends on how it accesses the API, but maybe on the next API call it should exit the current view and return to the login screen.

**Screenshots**
N/A; I couldn't take any after the terminal crashed.

**System (please complete the following information):**
 - OS: EndeavourOS Arch Linux
 - Terminal: Konsole
 - Version: 0.13.2-3
 - Installed from: pacman

**Backtrace/Debug log**
Unfortunately I don't have any again since the OS died after doing this.

**Additional context**
The only other thing that I did between the steps to reproduce is I installed another package (zsh) from pacman, but that should absolutely not have destroyed my system.

**Comment by Bettehem** [comment]
If you removed the shell you used before you installed zsh and didn't set zsh as your new shell, that would explain your shell not working. As far as I know, ncspot doesn't even have the permissions to change any files on your system to make it unusable
