### ISSUE TITLE
After a few songs ncspot pauses and refuses to resume

### ISSUE THREAD

**Issue by comblock** [hrkfdn/ncspot#1256]
**Describe the bug**
After 1 or 2 songs ncspot pauses at the start of the next song and cannot be unpaused (not even by running :pause or :toggleplayback). After stopping playback it's impossible to start playing a song.

**To Reproduce**
¯\\_(ツ)_/¯

**Expected behavior**
For ncspot to keep playing songs in the playlist/queue/

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Kitty
 - Version: ncspot 0.13.2
 - Installed from: AUR

**Comment by comblock** [comment]
I think this might be due to the wifi connection dropping temporarily.

**Comment by ThomasFrans** [comment]
I've noticed this before when using a VPN while playing music from ncspot. When I would toggle the VPN, ncspot would stop playback after a while with no way to start it again. Therefore I also suspect it doesn't handle (some) network changes correctly.

**Comment by comblock** [comment]
I think the reconnect command was created to solve this issue, it would be nice if ncspot could automatically run it when the internet connection is back, so you wouldn't need to do it yourself.
