### ISSUE TITLE
ncspot sometimes exits after being paused

### ISSUE THREAD

**Issue by eprst** [hrkfdn/ncspot#1257]
Sometimes ncspot abruptly exits when I'm trying to resume playing. Usual sequence it:
- put it on pause
- let it sit there for a while. Big delay seems to be essential
- unpause it. It plays a couple seconds and stops
- try to unpause it again - it exists, no crash though

I don't have a good way to reproduce, but happens quite consistently.

**System (please complete the following information):**
 - OS: Gentoo Linux
 - Terminal: Konsole, urxvt
 - Version: current `master`: `bd80670345f7d31f660caf4fe8c60e4fa8e7f9b1`, `0.13.4`
 - Installed from: `cargo`

**Backtrace/Debug log**
[ncspot.log.gz](https://github.com/hrkfdn/ncspot/files/12384468/ncspot.log.gz)

**Comment by eprst** [comment]
Got a stacktrace, I think it looks similar to what's reported in https://github.com/hrkfdn/ncspot/issues/993

```
   0: ncspot::panic::register_backtrace_panic_handler::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: ncspot::spotify::Spotify::send_worker
   8: ncspot::queue::Queue::toggleplayback
   9: ncspot::commands::CommandManager::handle_default_commands
  10: ncspot::commands::CommandManager::handle
  11: cursive_core::event::Callback::from_fn::{{closure}}
  12: cursive_core::cursive::Cursive::on_event
  13: cursive_core::cursive_run::CursiveRunner<C>::step
  14: ncspot::main
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: main
  17: <unknown>
  18: __libc_start_main
  19: _start
 
panicked at 'can't send message to worker: SendError { .. }', src/spotify.rs:342:48
```

**Comment by hrkfdn** [comment]
Hey! I have pushed something that may alleviate this issue, in particular with the crashes. It's possible the user action (i.e. toggling playback) can not be processed so you may have to retrigger it. Would be happy to hear whether this changes things for you.

**Comment by eprst** [comment]
Hi. Picked up your fix, now it doesn't crash, but doesn't play either. Here's output from the new logging:
```
[2023-08-29][14:31:32] [ncspot::spotify] [INFO] sending command to worker: Pause
[2023-08-29][14:31:32] [ncspot::spotify] [ERROR] can't send command to spotify worker: channel closed, dropping command
[2023-08-29][14:31:32] [cursive_buffered_backend] [DEBUG] output_all_to_backend started
[2023-08-29][14:31:32] [cursive_buffered_backend] [DEBUG] output_all_to_backend finished
[2023-08-29][14:31:33] [ncspot::spotify] [INFO] pause()
[2023-08-29][14:31:33] [ncspot::spotify] [INFO] sending command to worker: Pause
[2023-08-29][14:31:33] [ncspot::spotify] [ERROR] can't send command to spotify worker: channel closed, dropping command
```
looks like librespot closes channel when paused for a long while?

**Comment by hrkfdn** [comment]
Do you have more logs? Somehow your Spotify session expires (that's normal) but doesn't properly get renewed.

**Comment by eprst** [comment]
Sure, here's full log from the same session.
[ncspot.log.gz](https://github.com/hrkfdn/ncspot/files/12469732/ncspot.log.gz)

**Comment by eprst** [comment]
OK, I'm not a Rust programmer, but here's what I think is happening:

- `MprisManager` uses `ASYNC_RUNTIME.spawn` to start `serve`, which then runs on the tokio even loop
- it awaits for the `metadata_changed`
- which calls `MprisPlayer::metadata` -> `WebApi::track` -> `WebApi::update_token`
- and there we get to `ASYNC_RUNTIME.block_on`

which panics inside tokio's `runtime.rs` because `Cannot start a runtime from within a runtime`

looks to me like `update_token` should be non-blocking. For that matter, `thread::sleep` in `api_with_retry` seems fishy too.

**Comment by eprst** [comment]
Looks like the issue was fixed by https://github.com/hrkfdn/ncspot/commit/cb96f46e51161fc45cec154be2f587ec09ec46db

**Comment by ThomasFrans** [comment]
I heavily doubt that cb96f46 fixed it. Functionally it shouldn't have changed anything. The PR was only meant to make the code a tiny bit simpler. Or maybe through sheer luck and without knowing how, I managed to solve something. That's also possible :smile:

**Comment by eprst** [comment]
@ThomasFrans see my analysis in https://github.com/hrkfdn/ncspot/issues/1257#issuecomment-1707439071. Your change removed `ASYNC_RUNTIME.block_on` call from `update_token`. 
I can't reproduce this issue anymore. At least as initially described.

Something is till off though: if I suspend my PC, then resume after a while, then start playing (plays!), then ask for the next track - ncspot unregisters mpris and stops responding. No backtraces or crashes. I will probably file a separate issue once I have a good description
