### ISSUE TITLE
Allow to cancel search when in search mode

### ISSUE THREAD

**Issue by emanrdesu** [hrkfdn/ncspot#132]
I always have to type some random string to be able to go back to library or queue
For example, typing escape should bring you back to the previous screen you were at, or just library if that's too complicated

**Comment by hrkfdn** [comment]
You should be able to jump out of the text edit field with arrow keys. Maybe an additional `TAB` or `ESC` binding to remove focus would be an alternative?

**Comment by hrkfdn** [comment]
You should now be able to toggle the search input focus with `TAB` or `ESC` :)
