### ISSUE TITLE
Hitting Enter on a track search result fills the queue with all results, and removes all other items

### ISSUE THREAD

**Issue by AndydeCleyre** [hrkfdn/ncspot#134]
If I search for a track, find it in the results, move over it, and hit Enter, ALL of the results are added to my queue . . . and everything else in the queue vanishes.

It's possible this is desired behavior, but it was highly unexpected for me. Is it working as intended? If so, I think the in-app doc for the Enter key ought to be expanded from the current:

> `Enter -> play`

to something with a little more detail.

**Comment by hrkfdn** [comment]
This is desired behaviour, matching that of the official Spotify client.

**Comment by AndydeCleyre** [comment]
> matching that of the official Spotify client.

I must be misunderstanding. Using official client `1.1.10.546`, this is what happens:

- I add a bunch of songs to my queue
- I hit play
- The first song in the queue starts playing
- I search for another song
- I double click on the search result
- That result starts playing, discarding the previously playing song
- The remainder of the queue remains intact, and plays in sequence after the current one

Notably, only the result I selected enters the queue/plays (not all the results), and the remainder of my queue is not discarded.

**Comment by hrkfdn** [comment]
I believe what you are describing is tracked in #69?

**Comment by AndydeCleyre** [comment]
Hmm, maybe. 

You're saying that ncspot's "Queue" ("NQ") maps to Spotify's "Next Up" ("SNU"), rather than Spotify's "Queue" ("SQ")?

AFAICT in ncspot I can non-destructively add to NQ with spacebar, which is something that only makes sense for SQ, not SNU.

**Comment by hrkfdn** [comment]
Closing this, as this is currently desired behavior. A design closer to Spotify is tracked in #69, but work has stalled for now.
