### ISSUE TITLE
Application doesn't play sounds

### ISSUE THREAD

**Issue by matheuscandido** [hrkfdn/ncspot#138]
I installed all the Debian-based systems' dependencies, installed ncspot through snap on Ubuntu 19.10, logged in with my premium spotify account and it doesn't play any sound on my computer. I already checked all the noob options like volume and so on but it simply doesn't play sounds. Does anyone know what could it be? What other information could I provide to help solving the problem?

**Comment by IjonFryderyk** [comment]
I have the same problem.

**Comment by hrkfdn** [comment]
Hi, unfortunately I don't maintain the snap package so I can't help you out with it. I'm sorry!

**Comment by 0atman** [comment]
For anyone seeing this, I installed today:

Snap package - no sound
`cargo build ncspot` - works perfectly.

Fix for ubuntu: install the deps in the readme, run `cargo build ncspot`. Then run `~/.cargo/bin/ncspot`
