### ISSUE TITLE
Persist state between sessions

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [hrkfdn/ncspot#1393]
I would like NCspot to persist state, like volume and the song being played, between sessions. Specifically, I always set the volume of my music a bit lower than the rest of the apps, and I would like that setting to be persisted between sessions so that the volume is not too loud when I open the app.

**Comment by hrkfdn** [comment]
Odd, it should already do this.. 🤔

**Comment by TeaDrinkingProgrammer** [comment]
I would like to supply a log, but it contains all sorts of tokens and usernames

**Comment by ThomasFrans** [comment]
When I use `ctrl+c` to exit, state isn't saved either. When I use the other methods (`q`, `:exit`, close terminal...) it does save.

**Comment by TeaDrinkingProgrammer** [comment]
That makes a lot of sense 😅. Thank you!

**Comment by ThomasFrans** [comment]
I'll still add an issue to track this as it would be a nice to have, even if it would probably only work on Unix-like systems (I have no clue how `ctrl+c` works on Windows).
