### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by BenStigsen** [hrkfdn/ncspot#1419]
I'm uncertain as to the status of the Flatpak version.
It says that it was built 5 days ago, _but_, it also says that it's version 1.0.0 instead of the 1.1.0 version.

![image](https://github.com/hrkfdn/ncspot/assets/24865450/d34dabdd-f989-4b0f-9caf-3a164bf9bc9d)

I can see here that the build failed: https://github.com/flathub/io.github.hrkfdn.ncspot/pull/27

Love the application still. Thank you for saving my RAM.

**Comment by hrkfdn** [comment]
Looks like Flathub's Cargo is too old for this change: https://github.com/hrkfdn/ncspot/commit/2a4178e069402160143f2c7c79c77b73508cb24d

**Comment by thorpelawrence** [comment]
Hi, I have been maintaining the flathub repo you linked, but unfortunately haven't had much time to look into the reason the build is failing, or how to update the version of cargo in flatpak/flathub builders, if it's even possible.

**Comment by thorpelawrence** [comment]
Looks like v1.1.0 is published. Might take some time for their site to update. Turns out I missed something obvious.

**Comment by BenStigsen** [comment]
Thank you for fixing it!
