### ISSUE TITLE
Timed out reading response

### ISSUE THREAD

**Issue by PrebenL** [hrkfdn/ncspot#1428]
**Describe the bug**
Seems like information is not getting fetched from the spotify api, lots of timeouts in debug log:

`[2024-03-29][15:44:00] [ncspot::spotify_api] [DEBUG] http error: Transport(Transport { kind: Io, message: None, url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.spotify.com")), port: None, path: "/v1/me/tracks", query: Some("market=from_token&limit=50&offset=0"), fragment: None }), source: Some(Custom { kind: TimedOut, error: "timed out reading response" }) })`

Credentials are checked and correct. No connectivity issues either.

**To Reproduce**
1. Start ncspot-bin

**Expected behavior**
Working normally, and succesfully loading playlists/tracks/etc/..

**Screenshots**
![Mar29::155128](https://github.com/hrkfdn/ncspot/assets/84629067/14a2be86-4e5b-4ccd-a2f4-87a1a9f9162d)

**System (please complete the following information):**
 - OS: Linux
 - Terminal: Alacritty
 - Version: 1.1.0-1
 - Installed from: AUR

**Backtrace/Debug log**
[backtrace.log](https://github.com/hrkfdn/ncspot/files/14805443/backtrace.log)

**Additional context**

**Comment by aragonnetje6** [comment]
experiencing this same issue, on latest linux mint, kitty terminal, installed through cargo, both release version and latest git commit

**Comment by PrebenL** [comment]
Can anyone at least reply if this a known issue?

**Comment by PrebenL** [comment]
Turns out, my system was preferring ipv6 connections instead of ipv4 which solved my issue.

**Comment by aragonnetje6** [comment]
confirmed that the issue is the same here.
I feel like it's still a bug that connection fails if no ipv6 connection can be made, but ipv4 would work.
