### ISSUE TITLE
No sound after snap package installation

### ISSUE THREAD

**Issue by BlueskyFR** [hrkfdn/ncspot#144]
Hi!

I am really hyped by your work, but after the installation of the package via snap, no sound can be heard when using your app!
I know that you are not the maintainer of the snap package but maybe there is a way to contact the person in charge of it? I really want to use it ^^

Thanks in advance.

**Comment by AlwaysLivid** [comment]
Also noticed that one myself on Arch Linux. Thought it was some sort of an obscure configuration issue, so I didn't report it.

**Comment by hrkfdn** [comment]
Hey, the snap package was a third party contribution: https://github.com/hrkfdn/ncspot/pull/126

Maybe they can help you. Please contact them instead :)

**Comment by BlueskyFR** [comment]
I also tried installing directly the release through cargo but it tried to
build it instead of simply installing it. Is there any way to install
ncspot without snap and without building it at all ? I do not want to
install Rust just for ncspot ^^

**Comment by 0atman** [comment]
For anyone seeing this, I installed today:

Snap package - no sound
`cargo build ncspot` - works perfectly.

Fix for ubuntu: install the deps in the readme, run `cargo build ncspot`. Then run `~/.cargo/bin/ncspot`

**Comment by BlueskyFR** [comment]
@0atman the problem is that I don't want to install Rust and cargo just for ncspot...

**Comment by 0atman** [comment]
I agree that is indeed your problem :wink: 

My ignorant assumption, is that it'll only take 200MB to build:
```
$ du -h ~/.cargo
[...]
204M    .cargo
```

The exe itself is 20MB, and seems (using `ldd`) to only be dynamically linked to the apt dependencies, which you'd need for the snap install anyway.

You could statically compile the exe, and then remove the dependencies, cargo and all, and you'd end up with the smallest possible install. If you do this, share it with me please! :laughing: 

Good luck!

**Comment by BlueskyFR** [comment]
I'll try this thanks :)

**Comment by IjonFryderyk** [comment]
@0atman it's not a fix. The snap package remains broken.

**Comment by BlueskyFR** [comment]
@IjonFryderyk then you can consider it as fix that only applies to your PC.
Btw he said the fix was for Ubuntu, not for the snap package.

**Comment by BlueskyFR** [comment]
A did a couple a researchs and found this which tries to fix the pulseaudio issue: https://github.com/ubuntu/snapcraft-desktop-helpers/pull/91
I will try it when I have time and I'll let you know if it works.

**Comment by ZirconCode** [comment]
Just for anyone else out there:

```
sudo apt install libpulse-dev libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
sudo apt install libdbus-1-dev
sudo apt install cargo
git clone https://github.com/hrkfdn/ncspot
cd ncspot
cargo build
```

Last line of cargo build command will tell you where it went. It takes long but it works on ubuntu 18.04. Sound issue present specifically in i3.

**Comment by rmacas** [comment]
Ubuntu 20.04 + i3 + ncspot with cargo build  - sound works.
Ubuntu 16.04 + i3 + ncspot with cargo build - no sound with no issues during installation.

Does anyone have any suggestions why it does not work on Ubuntu 16.04? Ubuntu 16.04 snap app has working sound on Unity but no sound on I3. Also, Ubuntu 16.04 and 20.04 are installed on totally different machines so don't know if it's reasonable to compare them.

**Comment by BlueskyFR** [comment]
Try building it yourself and you'll have no problem. The snap package has a
problem.

**Comment by rmacas** [comment]
Hi BlueskyFR, I did build it with cargo but it still does *not* work on Ubuntu 16.04 + i3. It works on Ubuntu 16.04 + Unity.
