### ISSUE TITLE
Remember volume settings from one invocation to the next

### ISSUE THREAD

**Issue by drhayes** [hrkfdn/ncspot#146]
When I start `ncspot` it always defaults back to %100 volume. I then have to press <kbd>-</kbd> 35 times to get it back to 65%. Can it either remember what I set it to last time or (even better) pick it up from the config?

**Comment by hrkfdn** [comment]
Merged a contribution that addresses this: https://github.com/hrkfdn/ncspot/pull/127

Could you test this and see if it helps?

**Comment by drhayes** [comment]
Oh sweet. I did a `cargo install` originally, but  I'll try pulling from source later today. Thanks!

**Comment by drhayes** [comment]
Hey, so I'm a `cargo` newbie. If I cloned the repo, run `cargo build --release` and then run `ncspot`... did I update my binary? `which ncspot` yields `~/.cargo/bin/ncspot`. If this kind of support is too much, I can wait for a release and pick up the changes then.

**Comment by hrkfdn** [comment]
Try `cargo install --release`. It will do the build and copy the binary to
said path.

**Comment by drhayes** [comment]
Oh no! Turns out I don't get notified about issues I've closed. This worked for me, except my version of cargo insisted `cargo install --release` isn't a thing. I had to `cargo install --path .` from my working copy.

But... thanks! Works for me now!
