### ISSUE TITLE
Config (file)

### ISSUE THREAD

**Issue by im-n1** [hrkfdn/ncspot#15]
I would like to kick off the config question where we can put key bindings, credentials, etc.

Are there any plans? Can I humbly vote for INI/Toml config file? I might help with some code.

**Comment by hrkfdn** [comment]
There is a config file that contains the Spotify credentials (`~/.config/ncspot`), it's in TOML.

**Comment by im-n1** [comment]
Yes but the location is hardcoded. It would be cool to have multiple config files so the app would support multiple accounts.

**Comment by norcalli** [comment]
@im-n1 the typical way to do this would be to have multiple profiles in a single config file, or accepting the config file via a switch like `--config`, but I think most people only have 1 spotify account anyway.

**Comment by im-n1** [comment]
True. Would be cool if I could modify keyboard bindings.

**Comment by pard68** [comment]
@hrkfdn I am looking at the src, hoping to make a patch to allow for non-standard keys to be bound via the config file. I cannot find the location where 'return', 'space', or 'd' are in src.

**Comment by GZYproduction** [comment]
Will also have a look. Accidentally deleted tracks from my Library by pressing `s` (several times :sweat_smile:). 
`shift + s` or `ctrl + s` for adding Tracks would be a much saver alternative.

**Comment by GZYproduction** [comment]
Will also take a look. I accidentally deleted some tracks from my library by pressing `s` (several times :sweat_smile:) 
I thought by changing the binding for deleting tracks to `del` or some combination it would be much saver.

**Comment by hrkfdn** [comment]
I have reworked the bindings a little bit. Please let me know what you think!
