### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by BrainReader** [hrkfdn/ncspot#1504]
**Describe the bug**

**To Reproduce**
1. Install
2. Try to sign in
3. Sign in fails and it displays bad credentials

**Expected behavior**
It is supposed to not fail and log me in

**System (please complete the following information):**
 - OS: Fedora 40 running xfce
 - Terminal: xfce Terminal
 - Version: 1.1.2
 - Installed from: Flathub

**Additional context**

I am able to log in to the web version of Spotify

The app is running fine on my laptop running OpenSUSE Tumbleweed (installed through the GNOME Terminal using flatpak). It is also running fine on my phone (installed through Termux running unofficial Lineage GSI). I decided to copy the files from ~/.var/app from my laptop to my PC running Fedora 40 and it skipped the login screen and it went straight to my library.

I was switching from EndeavourOS to Fedora so I had to install the app again. It was working fine on EndeavourOS. I have it installed on Windows 10, but I haven't used it in a while.

**Comment by BrainReader** [comment]
Update, the Windows version displaying the Bad credentials error on launching from both powershell and cmd,

**Comment by joelsleeba** [comment]
I have the same issue in archlinux

**Comment by BrainReader** [comment]
The workaround where I copied a working version of ncspot no longer works. I cannot log into ncspot on my laptop or phone.

**Comment by rosorio** [comment]
This seems to be a general issue affecting many spotify OSS clients

https://github.com/librespot-org/librespot/issues/1308
https://github.com/librespot-org/librespot-java/issues/921
https://github.com/kokarare1212/librespot-python/issues/277
https://github.com/Spotifyd/spotifyd/issues/1293

**Comment by dabalroman** [comment]
Spotify disabled the ability to login in to their API using login and password. 
All devices based on that API utility will no longer work, we are left with zeroconf (discovery).

Check out https://github.com/Spotifyd/spotifyd/issues/1293, the author of spotifyd created a small app that enables creating credentials when default zeroconf fails. 

Unfortunately, there is no way to tell how long the credentials created via zeroconf will last in practice.
