### ISSUE TITLE
THe app refuses to play most of my songs, skipping over them until stopping on specific ones

### ISSUE THREAD

**Issue by t3chno8uddha** [hrkfdn/ncspot#1510]
Not much else I can describe. The only thing I did was use [librespot-auth](https://github.dev/dspearson/librespot-auth) to generate the authentication file and that was it.

**To Reproduce**
1. Press enter on a song
2. See the app skip over track until it reaches specific ones

**Expected behavior**
Pressing enter playing the selected song

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Same behaviour in all terminals
  - Version: 1.1.0
 - Installed from: The official arch repository

**Backtrace/Debug log**
Please attach a debug log and backtrace if ncspot has crashed.

**Comment by tajnymag** [comment]
Seems to be caused by librespot. Spotify-player acts the same.

Librespot issue: https://github.com/librespot-org/librespot/issues/1322

**Comment by hrkfdn** [comment]
Does this still occur with the current `main` branch?

**Comment by t3chno8uddha** [comment]
Very sorry for the delayed response. No, it seems stable now. Thank you!
