### ISSUE TITLE
Warning when installing ncspot: bytemuck v1.16.1 is yanked in crates.io registry

### ISSUE THREAD

**Issue by fam007e** [hrkfdn/ncspot#1517]
When trying to install `ncspot` using `cargo install --locked`, the process warns that the package `bytemuck v1.16.1` is yanked from the `crates.io` registry. The installation proceeds but suggests running without the `--locked` flag, which is not ideal for ensuring reproducible builds.

**To Reproduce**
1. Clone the official `ncspot` repository.
2. Run the following command: `cargo install --locked ncspot`.
3. Observe the warning about the `bytemuck` package being yanked.

**Expected behavior**
The installation should succeed without warnings, or the `Cargo.lock` should be updated to avoid installing yanked packages.

**System:**
- OS: Arch Linux
- Terminal: Kitty
- Version: `ncspot v1.1.2`
- Installed from: `cargo`

**Backtrace/Debug log**
N/A

**Additional context**
The package `bytemuck v1.16.1` is yanked in the `crates.io` registry. Running `cargo install --locked` results in a warning:

**Comment by hrkfdn** [comment]
Thanks, this should be fixed in `main`/with the new release.
