### ISSUE TITLE
Open artist views from an artist entry

### ISSUE THREAD

**Issue by tulipszs** [hrkfdn/ncspot#152]
What is (or will be) the workflow for opening the selected artist's artist view? 

Under the artist section of search results or related artists, I am unable to open scroll to artists and use "A" to open the selected artist. 

This is a feature request, I do not believe this is a bug.

**Comment by BachoSeven** [comment]
I think you need to use "o" when trying to select the artist view from the artist section of a search result

**Comment by tulipszs** [comment]
Awesome, thanks!
