### ISSUE TITLE
Request: Podcasts

### ISSUE THREAD

**Issue by abdrysdale** [hrkfdn/ncspot#153]
It would be great if you could also play podcasts along with a menu option for podcasts too.

**Comment by hrkfdn** [comment]
Hi there, would love to be able to play podcasts as well, unfortunately the web API does not expose them, yet: https://github.com/spotify/web-api/issues/551

**Comment by liamcloss** [comment]
Is this any more viable now the web-api has 'some' endpoints?

**Comment by hrkfdn** [comment]
Sure is! Just needs to be implemented in rspotify.
