### ISSUE TITLE
ncspot exits immediately with code 101

### ISSUE THREAD

**Issue by rcorre** [hrkfdn/ncspot#1540]
**Describe the bug**

When I run `ncspot`, it briefly clears the terminal, then exits with code `101`. There is no obvious error printed. I've previously been running `ncspot` a lot on this laptop, so this is a new symptom.

**To Reproduce**
1. Run `ncspot`

**Expected behavior**
ncspot starts

**Screenshots**

**System (please complete the following information):**
 - OS: linux
 - Terminal: foot
 - Version: ncspot 1.1.2
 - Installed from: Arch repos

**Backtrace/Debug log**
Please attach a debug log and backtrace if ncspot has crashed.

Instructions on how to capture debug logs: https://github.com/hrkfdn/ncspot#debugging

That link is broken, but I ran `ncspot` with the `-d` flag.

[ncspot.txt](https://github.com/user-attachments/files/17528117/ncspot.txt)

**Additional context**

**Comment by mrsteve0924** [comment]
same here.  sometimes it lets me enter my spotify credentials, but it just fails saying the creds are invalid.

**Comment by tomasswaier** [comment]
Same here . Has been happening since last week . Exits with this as last 3 lines in debug "[2024-10-23][18:57:41] [ncspot::ui::pagination] [DEBUG] fetched first page, items: 50, total: 53
[2024-10-23][18:57:41] [ncspot::ui::cover] [DEBUG] Determined window dimensions: 0x0, 0x0
[2024-10-23][18:57:41] [ncspot::ipc] [INFO] removed socket at "/run/user/1000/ncspot/ncspot.sock"
" .

**Comment by rcorre** [comment]
I tried on my desktop. There I see the login prompt but I get "credentials invalid".

**Comment by mrsteve0924** [comment]
i downgraded to ncspot version 1.1.0 and is working again. 

looks like arch updated to 1.1.2 last week which resulted in this issue, but repos havent been updated to latest 1.2 version, which might fix the issue.

**Comment by rcorre** [comment]
Note that if you're getting "invalid credentials", don't keep trying. Spotify will eventually lock you out and force a password reset.

**Comment by hrkfdn** [comment]
There is a fix for album cover support in `main`, could you check if it helps?

**Comment by hrkfdn** [comment]
Fixed with #1542 + released via ncspot 1.2.1

**Comment by rcorre** [comment]
That worked, thanks!
