### ISSUE TITLE
Suspicious activity emails and forced password reset

### ISSUE THREAD

**Issue by nonetrix** [hrkfdn/ncspot#1547]
**Describe the bug**
If I use this program too long I get a email forcing me to reset my password

**To Reproduce**
1. Login
2. Play some music
3. Exist wrong
4. Spotify angy
5. Forced to reset password

**Expected behavior**
Spotify not do that

**Screenshots**
![satty-20241105-22:30:32](https://github.com/user-attachments/assets/a4dee1b5-4fd2-4665-b671-cb1fea14777a)

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Alacritty
 - Version: https://github.com/hrkfdn/ncspot/commit/a3b7b65c30436ff294879165ba95eff131fb6853
 - Installed from: AUR

**Backtrace/Debug log**
```
Connection error: Permission denied { Login failed with reason: Bad credentials }
To login you need to perform OAuth2 authorization using your web browser

Browse to: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by schooldanlp6** [comment]
yes this is because spotify thinks 3rd party clients are a thread this is normal but should happen only once

**Comment by hrkfdn** [comment]
I'm wondering if it's related to fa298f4f44a66d5039749f589185ab61fefbcbdf. If anyone who's affected could revert that commit and test it, that would be really helpful.

**Comment by hrkfdn** [comment]
Or alternatively, test if it also occurs with version 1.2.0.

**Comment by cybrox** [comment]
Thanks for the suggestion @hrkfdn. I cloned the repo, checked out `v1.2.0` (`bfa5653`) and built it using `cargo build` (using a debug build for now).

Login redirect worked fine so far and I can use ncspot. I'll let you know if the "Suspicious Activity" emails start again in the following days.

**Comment by cybrox** [comment]
After 3 days, no issues. - Before, the e-mail would arrive within 12-24 hours and I would be forced to reset the password.

I'll report back again after 1-2 weeks of use but so far it really looks like `1.2.0` does not have this issue.

**Comment by cybrox** [comment]
@hrkfdn After 2 weeks of use, still no issues with forced password resets.

I think it's save to say that `1.2.0` does not cause this issue.

**Comment by hrkfdn** [comment]
Thanks, will revert then. It's a bit unfortunate as this was the only way for me to get any metrics, but so be it.

**Comment by heckenscherenmann** [comment]
I am getting the same behavior that @cybrox initially reported, with my password getting reset every few days when using ncspot. I am also on Linux and constantly using a VPN. But before I was using ncspot I used the Spotify web interface and the resets did not happen.
