### ISSUE TITLE
Ability to open shared tracks

### ISSUE THREAD

**Issue by ltning** [hrkfdn/ncspot#155]
I'm getting links from colleagues and friends of the form 'https://open.spotify.com/album/3mpabcdef382e79yhif34e' (random non-working sample), I would very much like to be able to open those in ncspot. Either through a "open URL" or passing it on a pipe or whatever.

Any takers? :)

**Comment by hrkfdn** [comment]
Possibly related to https://github.com/hrkfdn/ncspot/issues/97

**Comment by Bettehem** [comment]
I'll look into this. Shouldn't be too hard to add so you can use the MPRIS openUri function to open a shared link too.
In the meanwhile if you want to open a shared track in ncspot, you first have to convert the link to a URI:
`https://open.spotify.com/album/3mpabcdef382e79yhif34e` -> `spotify:album:3mpabcdef382e79yhif34e`
Then use something like [playerctl](https://github.com/altdesktop/playerctl) to open it by running `playerctl -p ncspot open spotify:album:3mpabcdef382e79yhif34e`

**Comment by hrkfdn** [comment]
This is now implemented via MPRIS and CTRL-V shortcut. Closing issue.
