### ISSUE TITLE
`Backspace`usage

### ISSUE THREAD

**Issue by daniel-vera-g** [hrkfdn/ncspot#157]
Note: There was already an issue about this(#154) and I use this as example, because I find it rather intuitive. I am also not sure if #108 is related, as I have not found any use for the `Backspace` command.

Example:

After hitting `?` I am in the help screen.

To exit I suppose to do `Backspace` as 

> Backspace closes the current view

but actually nothing happens.

I only get back through the `F1-F3` keys.

In which context is `Backspace` supposed to work ?

Regarding f.ex the help Screen I would either propose `Escape` or as referenced `Backspace` to exit.

**Comment by hrkfdn** [comment]
The help screen is an actual screen, like the search, queue, etc. These can not be closed. Backspace is for closing detail views such as an album/artist view opened with `o`.

**Comment by daniel-vera-g** [comment]
> The help screen is an actual screen, like the search, queue, etc. These can not be closed. Backspace is for closing detail views such as an album/artist view opened with `o`.

Ok, thanks for the clarification.  
I would have found it more intuitive to toggle the help screen with `?` as in a lot of other popular `cli` programms.
Nevertheless, I could understand your decision to leave it as it is.

Regardless of it, I would propose a better documentation of the distinction between a `view` and a `screen`. It would probably help to get the distinction more clear and describe the navigation better.
If you don't mind, I would make a small PR to make this clearer in the README.

**Comment by hrkfdn** [comment]
I could make the help screen a view that is pushed like the detail views (which also have the arrow back top left to indicate this). It could then be closed by `backspace` or by selecting one of the screens per `Fn` keys. Is that a compromise? :)

**Comment by daniel-vera-g** [comment]
> I could make the help screen a view that is pushed like the detail views (which also have the arrow back top left to indicate this). It could then be closed by `backspace` or by selecting one of the screens per `Fn` keys. Is that a compromise? :)

That sounds good 👍
Could live with it :)

**Comment by hrkfdn** [comment]
Just pushed a commit for this, let me know if it's better this way.

**Comment by daniel-vera-g** [comment]
> Just pushed a commit for this, let me know if it's better this way.

Hey, sorry for the late reply.
Your fix works as expected. Thanks for your work, looking forward for upcoming features :top:
