### ISSUE TITLE
Continuous audio stream not a new one for each song

### ISSUE THREAD

**Issue by noobadmin** [hrkfdn/ncspot#158]
Hi! I love this! However, I've got this one issue...
Currently each song starts as a new audio stream / pipe (sorry if I lack correct terminology) - I dont think its standard behavior and it bugs me. I have this in pulse conf: load-module module-stream-restore restore_device=false. I have this option there so that I dont have to remember and double check what the last used output was whenever I need to play audio (I've got a couple of airplay speakers at home.). Now to the isssue, at this point I basically need to switch the output after each song as the next one always starts from default output. I know I could just restore_device=true, but the setting serves it's purpose and doesn't cause an issue in other applications.

**Comment by noobadmin** [comment]
Issue persists even with restore_device=true

**Comment by hrkfdn** [comment]
Hey there! Which playback backend are you using? I'm guessing this is a problem in the PulseAudio backend from librespot. If this problem also occurs with spotifyd or librespot when using the PulseAudio backend, it may be worth reporting it upstream, as I only have very limited control over how the backends use audio devices.

**Comment by hrkfdn** [comment]
Unfortunately, this can not be fixed in ncspot, as the backend's device behavior is out of ncspot's control. It needs to be addressed within librespot.
