### ISSUE TITLE
Playback is stopped on deleting the last track in queue

### ISSUE THREAD

**Issue by KarlZeilhofer** [hrkfdn/ncspot#159]
# Steps
* add some tracks to the queue
* start playback at first track
* go down with cursor keys to last track in queue
* hit d for delete
* playback stopes

# Related
Similar happens, when a track is added more than once to the queue, and the second instance is deleted, when the first instance is currently played (and is not the last track in the queue). 

# Version 
0.1.2 on Linux Mint 19.2, self compiled.

**Comment by hrkfdn** [comment]
Thanks for the report, should be fixed now

**Comment by KarlZeilhofer** [comment]
great, thanks!
