### ISSUE TITLE
"New login to Spotify" email

### ISSUE THREAD

**Issue by montvid** [hrkfdn/ncspot#160]
Hi, thanks for the wonderful player that uses librespot! I am having "New login to Spotify" email every time? I start ncspot 0.1.2. So far 3 emails today. Is there a way to stop the emails coming? Spotify thinks that my account is being hijacked or something... I don't get these kind of emails by using librespot.

**Comment by hrkfdn** [comment]
Are you using a Spotify account to login or Facebook? I'm not getting these mails (Spotify account).

**Comment by M7S** [comment]
I do get them using Śpotify account. I installed ncspot using snap, could that have anything to do with it?

**Comment by montvid** [comment]
I compiled ncspot 0.1.2 and librespot from crates.io. Using Spotify account. Just started the player and got an email from Spotify again.
 Maybe it would be a good idea to check with librespot guys I remember they had a way not to get flagged by Spotify.

**Comment by marcinzelent** [comment]
I get 2 emails every time I start ncspot. Compiled from source, Spotify account.

**Comment by AntiGuide** [comment]
I get these mails too. Installed as snap on Ubuntu with a Spotify-Account.

**Comment by hrkfdn** [comment]
Hmm, it's hard for me to debug this, as I don't get these mails. I have pushed a commit that will use the cached credentials from librespot. Could you let me know if this alleviates the problem?

**Comment by montvid** [comment]
@hrkfdn How to compile it? Cargo builds from crates.io 0.1.2?

**Comment by BachoSeven** [comment]
I just clone the repo, built it and then used `cargo install --path .`, not sure if that's how is supposed to be but works fine

**Comment by montvid** [comment]
`cargo install --git` works fine. The bug seems to be gone - no email from spotify so far. Will test for a day or two. Thanks @hrkfdn!

**Comment by hrkfdn** [comment]
Glad it works! I'll close this one. Feel free to reopen if the issue still occurs.

**Comment by mbojan** [comment]
I am still getting these emails unfortunately, @hrkfdn . I am using 2e89cc3d01e25c27be752172d66f86a4486d614e. 

Is it possible that (one of) the dependencies is too old? Such as the librespot? I know next to nothing about Rust, but `Cargo.lock` seems to say that it is 0.1.1.

I am not using Facebook login on Spotify.

**Comment by mbojan** [comment]
Interestingly, Git says I'm using ncspot past 1.3 tag, but at the same time:

```
$ ncspot --version
ncspot 0.1.2
```

**Comment by mbojan** [comment]
Disregard above hidden comment. I got lost in my own mess of symlinks... :facepalm:
