### ISSUE TITLE
Feature Request: playlist starts with random song in shuffle mode

### ISSUE THREAD

**Issue by BachoSeven** [hrkfdn/ncspot#162]
It would be nice if, when Shuffle is activated, playing a playlist would result in a random song being picked as the first to be played rather than the actual first song of the playlist, as it works in Spotify

**Comment by hrkfdn** [comment]
This should already be fixed: https://github.com/hrkfdn/ncspot/pull/128

**Comment by hrkfdn** [comment]
Closing this, as it's fixed. It will be in the next release :) If the problem persists, feel free to reopen.
