### ISSUE TITLE
Build failed in WSL 1

### ISSUE THREAD

**Issue by dvisan** [hrkfdn/ncspot#164]
Installed all the dependencies using the command in Readme and stumbled upon the following build error:

> error: failed to run custom build command for `libdbus-sys v0.2.1`
> 
> Caused by:
>   process didn't exit successfully: `/tmp/cargo-installiVqIxw/release/build/libdbus-sys-9e27116179774e9b/build-script-build` (exit code: 101)
> --- stderr
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\nPackage dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n" } }', src/libcore/result.rs:1165:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `ncspot v0.1.2`, intermediate artifacts can be found at `/tmp/cargo-installiVqIxw`

Due to the fact that **libdbus** appeared to be the culprit, I installed it again using:

`sudo apt-get install -y libdbus-1-dev`

Then, I attempted to run `cargo install ncspot` one more time, but the build failed again, with the following error:

> --- stderr
> /tmp/cargo-installegbo0N/release/build/ncurses-fe4bf46afd674b98/out/chtype_size.c:6:10: fatal error: ncurses.h: No such file or directory
>  #include <ncurses.h>
>           ^~~~~~~~~~~
> compilation terminated.
> thread 'main' panicked at 'assertion failed: command.status().expect("compilation failed").success()', /home/dsv/.cargo/registry/src/github.com-1ecc6299db9ec823/ncurses-5.99.0/build.rs:105:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `ncspot v0.1.2`, intermediate artifacts can be found at `/tmp/cargo-installegbo0N`
> 
> Caused by:
>   build failed

Installed it earlier today using Snap on my other machine using elementary OS and I'm using it right now with no issues. Sadly, snap is not available in WSL 1 .

**Comment by hrkfdn** [comment]
You'll also need `libncursesw5-dev` or `libncurses5-dev`

**Comment by dvisan** [comment]
Installing both the packages above has fixed the build issue. Thanks!

**Comment by frostblooded** [comment]
Why isn't this in the dependencies in the README?
