### ISSUE TITLE
lots of question marks everywhere

### ISSUE THREAD

**Issue by sirtomato999** [hrkfdn/ncspot#165]
it loads fine, and works great, but there are a lot of unmatched characters or something everywhere. I have `TERM` set to xterm, and I am using the st terminal on FreeBSD, and I have the liberation fonts installed

**Comment by BachoSeven** [comment]
Your Liberation font probably might not be a Nerd font, so you could try to set `use_nerdfont=false` in the config file (~/.config/ncspot/config.toml) to remove the nerdfont Icons, see if that's the issue.

**Comment by sirtomato999** [comment]
sorry, actually my terminal font is Source Code Pro Nerd Font. I just mentioned liberation because it is kind of a catch-all for special characters (japanese, etc)

**Comment by hrkfdn** [comment]
Are you using a non-UTF-8 locale? See also https://github.com/hrkfdn/ncspot/issues/107

**Comment by hrkfdn** [comment]
Closed as duplicate of #107
