### ISSUE TITLE
Incomplete compile instructions

### ISSUE THREAD

**Issue by tupsut** [hrkfdn/ncspot#173]
The documentation does not specify anywhere that the project should be compiled with the nightly compiler rather than stable. When trying to install via yay (https://aur.archlinux.org/packages/ncspot/), it fails as it defaults to the stable compiler. This also happens when trying to compile using cargo default settings, meaning that with current documentation the project can not be compiled successfully (instead, a new user would need to install Rust as explained, then run `rustup install nightly`, then `cargo +nightly install ncspot`).

The best solution from the user's perspective would be to change the project's compiler to stable and make any relevant changes to make sure that it works on stable. Alternatively, you could specify in the install instructions that this requires the nightly compiler, but this makes it harder for a new user unfamiliar with Rust to install, and I can't immediately see any benefits to building on nightly for this type of project.

**Comment by hrkfdn** [comment]
Hey,

I'm not sure what exactly the problem is. I don't use the AUR package, but I can compile ncspot with the latest stable Rust release (1.42) and use it to actively develop ncspot.

**Comment by tupsut** [comment]
Looking into it some more, it seems like it's actually somewhat unintuitive behaviour by yay that's at fault - it installs rust from the official Arch repos, but then uses the local rustup install if one exists, which happened to be out of date. I didn't think to check if my local install was up to date, since clearly yay had just installed the newest version...

Sorry about the inconvenience, closing.
