### ISSUE TITLE
ncspot crashes after specific playlist searches

### ISSUE THREAD

**Issue by alexb7711** [hrkfdn/ncspot#175]
In the search menu (F2), when I search specific key words such as "lofi" or "relax" then pan over to the playlist tab ncspot crashes. If I search something like "test" and do the same thing, it will load everything just fine. 

Distro: Arch Linux 
Terminal: st

**Comment by hrkfdn** [comment]
Hey,
Can't really reproduce this. Could it be `st` is crashing due to odd Emoji? Can you reproduce this with other terminal emulators?

**Comment by alexb7711** [comment]
Yeah, it is an emoji thing. I just needed to install [libxft-bgra](https://aur.archlinux.org/packages/libxft-bgra/) from the AUR.

Thanks for your time!
