### ISSUE TITLE
Request: Daily Mixes

### ISSUE THREAD

**Issue by AlricRahl** [hrkfdn/ncspot#177]
Hello, I don't know the applicability of this idea, but a section for spotify made playlists like daily mixes might be pretty neat.

**Comment by hrkfdn** [comment]
Sorry, unfortunately, this is not possible at the moment: https://github.com/spotify/web-api/issues/324

**Comment by philipp-block** [comment]
If you come here looking for a solution to listen to Daily Mix playlist on ncspot: you can add them to your library via web client and they will appear in the playlist tab in ncspot.
