### ISSUE TITLE
search results including albums, playlists, etc.

### ISSUE THREAD

**Issue by jonjnicholson** [hrkfdn/ncspot#18]
It looks like the search is only returning songs. It would be nice if it also returned albums, playlists, users, etc.

**Comment by hrkfdn** [comment]
It would be nice if pressing F2 while in the search view opens a selector in which the user can chose what type of search to use (track, album, artist).

**Comment by SafariMonkey** [comment]
Slight point of confusion: isn't `F2` the key for going to the queue view? Overloading that seems like a bad idea.

**Comment by hrkfdn** [comment]
Right, I obviously meant F3. My bad.

**Comment by sajattack** [comment]
Silly request but if you want a screenshot of album searching, it should totally be Neil Young - Rust Never Sleeps

**Comment by hrkfdn** [comment]
Closed via https://github.com/hrkfdn/ncspot/pull/53
