### ISSUE TITLE
Move list to currently playing track

### ISSUE THREAD

**Issue by angelomen** [hrkfdn/ncspot#181]
I would like very much to have a key to move to the currently playing track in the queue list. Is there already a key for this? I was not able to find it.
Thanks

**Comment by hrkfdn** [comment]
You should be able to move items with `Shift + arrow key`.

**Comment by BachoSeven** [comment]
I think OP meant a key which finds the currently playing track in the queue and moves the cursor to it, which is not implemented as far as I'm aware of.

**Comment by hrkfdn** [comment]
Oh, my bad, I misinterpreted that. I can see how that is useful, especially for large queues.

**Comment by hrkfdn** [comment]
This is now implemented. You can use `.` to jump to the currently playing track in the queue.

**Comment by AndydeCleyre** [comment]
For anyone else finding this issue, looking for this feature, the trigger is now `p` by default, and the action for "jump to track" is named "move playing" and can be configured like

```toml
[keybindings]
"j" = "moveplaying"
```

**Comment by AndydeCleyre** [comment]
Actually, I'm wrong, my example above doesn't work.

**Comment by BachoSeven** [comment]
@AndydeCleyre I think `.` was working as a default trigger for the feature until last release, perhaps something changed recently?

**Comment by BachoSeven** [comment]
Okay so by looking at the [code](https://github.com/hrkfdn/ncspot/blob/master/src/command.rs#L186) I figured the command is actually called `move playing`, so the binding would be:
``` toml
[keybindings]
"." = "move playing"
```

**Comment by AndydeCleyre** [comment]
"move playing" is a very misleading name for this action. I've come back to this issue now just to figure out how to jump to the current track, after having carefully read through every action on the help screen.

This action does *not* move the playing item anywhere. It moves *to* the playing item.
