### ISSUE TITLE
space not working

### ISSUE THREAD

**Issue by Blade-B3AR** [hrkfdn/ncspot#182]
im trying to have playpause set to space but it doesnt work

**Comment by BachoSeven** [comment]
It could be because space is already binded by default to `queue` the item under the  cursor. You might want to first remap `queue` to something else and then set space to playpause.

**Comment by Blade-B3AR** [comment]
> It could be because space is already binded by default to `queue` the item under the cursor. You might want to first remap `queue` to something else and then set space to `playpause`.

yes it was thank you
