### ISSUE TITLE
Request: get recommendation from a track/artist/playlist

### ISSUE THREAD

**Issue by tshirtman** [hrkfdn/ncspot#186]
Could be interesting to add similar features as the "radio from track" feature, using the menu on a track, putting the returned recommendations in the queue.
https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/

**Comment by ltning** [comment]
I wasn't going to comment apart from adding my thumbs-up - but after reading the docs in the link above I'm absolutely floored with how cool that API call actually is. My letter to Santa this year will include 1) this feature in ncspot and 2) a spotify recommendations "control panel" to play with this API with sliders and knobs and the works.

**Comment by hrkfdn** [comment]
This is now implemented and can be accessed in the track context menu ("Similar tracks") :tada:

**Comment by stretchkennedy** [comment]
If you're like me and found this with no idea what a track context menu is, by default the track context menu is opened by pressing `o` when a track is highlighted.
