### ISSUE TITLE
Make the playlist overview a bit more clear

### ISSUE THREAD

**Issue by brother** [hrkfdn/ncspot#188]
I have my playlists in a folder based structure in the official client. I suspec that this is one of the reasons my playlist view is very strange.

Would be great to be able to see the folder structure if that information is available.
As a secondary solution I can live with having the lists sorted alphabetically as I have named them appropriately. The very random order I see now is not very helpful. (Just a find as you type feature could be something, both for the archive overview and the "add to playlist" list.

![bild](https://user-images.githubusercontent.com/243351/80576500-9b1c1580-8a05-11ea-93e4-475dd10c8dea.png)

![bild](https://user-images.githubusercontent.com/243351/80576770-0d8cf580-8a06-11ea-9e2f-3e5d8f326b83.png)

(spot the arrows to the right of "Generic" and "Electro". Folders that expand collections of playlists.)

**Comment by hrkfdn** [comment]
Unfortunately, folders are not exposed by the API, so I can't display the data hierarchically. I believe the order is based on creation date of the playlist, at least that seems to be the case here. I'll try to add sorting functionality soon (tracked in #189).
