### ISSUE TITLE
When arrowing down through the lists, the highlighted row disappears as the selected row is one row below the view.

### ISSUE THREAD

**Issue by jonjnicholson** [hrkfdn/ncspot#19]
It's a little confusing to see the highlighted row disappear, and it also means you have to arrow back up to select a song.

**Comment by hrkfdn** [comment]
I'm not able to reproduce this. Could you provide some more input? Or is this when using Page-Up/Down?

**Comment by jonjnicholson** [comment]
I haven't been able to reproduce this today either. Maybe you fixed it inadvertently? Looks good to me. Thanks!
