### ISSUE TITLE
Request: Enable runtime selection of audio backend

### ISSUE THREAD

**Issue by Jannik2099** [hrkfdn/ncspot#194]
Currently if you compile ncspot with multiple librespot backends enabled, it seems to always default to alsa.

Could we have an option to select between the enabled ones at runtime, similar to how e.g. spotifyd does it?

**Comment by hrkfdn** [comment]
You can now set the backend and the device to use via `backend` and `backend_device` respectively. Hope this helps.

**Comment by Jannik2099** [comment]
Thanks, this is exactly what I imagined!
