### ISSUE TITLE
Request: configurable volume normalisation

### ISSUE THREAD

**Issue by gatorget** [hrkfdn/ncspot#195]
I see that client has an option for setting up volume normalisation but unfortunately it's not possible through config file.

Normalisation is turned off by default. 
https://github.com/hrkfdn/ncspot/blob/2e89cc3d01e25c27be752172d66f86a4486d614e/src/spotify.rs#L228-L229

**Comment by hrkfdn** [comment]
Hey there, as I don't really use the normalization, could you tell me if the pregain value is also of interest?

**Comment by gatorget** [comment]
> Hey there, as I don't really use the normalization, could you tell me if the pregain value is also of interest?

Yeah, definitely.

**Comment by hrkfdn** [comment]
Should now be configurable!
