### ISSUE TITLE
Songs download locally, building up to several GBs

### ISSUE THREAD

**Issue by flesler** [hrkfdn/ncspot#196]
Hi, I'm using the [snap version](https://github.com/popey/ncspot-snap) of ncspot, I know it's unofficial but I'm guessing the same thing happens with the vanila one.
I got an alert about running out of space and noticed ncspot accumulated over 5GB. I was able to go and delete the directories but would be great to avoid this altogether.

I'd say the ideal solution would be to have a setting to only stream without saving. The next big solution would be a setting to clear up the cache every X or on reboot.

**Comment by hrkfdn** [comment]
You should now be able to disable audio caching via the `audio_caching` setting.

**Comment by flesler** [comment]
Excellent, will you be making a new release?
