### ISSUE TITLE
Feature request: open external links

### ISSUE THREAD

**Issue by BachoSeven** [hrkfdn/ncspot#197]
It would be awesome to be able to open external links to songs/playlists in ncspot!

**Comment by mxdevmanuel** [comment]
I think this is already requested in #155

**Comment by Bettehem** [comment]
You can do this via MPRIS already.
For example with playerctl you can run
```
playerctl -p ncspot open <your_link_goes_here>
```

**Comment by BachoSeven** [comment]
@Bettehem thanks for the tip, I did not know about `playerctl`, however:
- this solution only works when ncspot is already open,
- even when it is, it does not work for me, meaning the command is executed but nothing happens in the player.

I would be happy with playerctl if I was able to, say, write a script that opens dmenu and lets me paste a link to open in ncspot

**Comment by BachoSeven** [comment]
Okay now I figured it out: in order for it to work through playerctl, you need the following format for the URL:
(Example)
`https://open.spotify.com/track/2WTAUN77y319PP2TKdbxgw` -->> 
 `spotify:track:2WTAUN77y319PP2TKdbxgw`

Then, `playerctl -p ncspot open URL` will work as mentioned. This is what I was looking for, so I will close the issue.
