### ISSUE TITLE
Run ncspot in docker container

### ISSUE THREAD

**Issue by gabrielaigner** [hrkfdn/ncspot#198]
Does anybody know how to run ncspot in a docker container?

**Comment by mxdevmanuel** [comment]
@gabrielaigner Running the program perse, you just need to build it inside the container or build it and replicate the environment you build it in and copy the binary, and run it interactively, people run vim  or neovim in docker containers so you can look a  similar thing,the playing sound part I think it is a little more tricky and is dependent of your platform

**Comment by grerrg** [comment]
I'm on it but i can't even install `ncspot` on debian(ubuntu bionic). :(
I've tried for 2 hours. Will update this post later today.

---

## Requirements
1. Rust
2. Python 3 (needed for building `rust-xcb` dependency)
3. `libpulse-dev` (or `portaudio-dev`, if you want to use the PortAudio backend)
4. `libncurses-dev` and `libssl-dev`
5. `libdbus-1-dev`
6. `libxcb` + development headers (for clipboard access)
7. A Spotify premium account
8. pkg-config
9. On Debian based systems you need following packages for `libxcb` development headers:
- libpulse-dev libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

---

I would go for the `rust:buster` image. So we have a official rust installation on a debian.

```shell
FROM rust:debian # 1.

RUN apt update && \
    apt install -y \
        \
        python3 \ # 2.
        \ 
        libpulse-dev \ # 3.
```

**Comment by leleobhz** [comment]
For who interests in Docker images, where is one I did https://github.com/leleobhz/ncspot-docker

This version features a script called `ncspot_launch-beta.sh` to launch image with MPRIS correct options for podman (Also works correctly on docker) and a `build.sh` script.
