### ISSUE TITLE
F-keys don't work in Termite (and probably other VTE terminals)

### ISSUE THREAD

**Issue by barzamin** [hrkfdn/ncspot#20]
In Termite (a VTE-based terminal emulator), I can't switch tabs with F-keys; ncspot works completely fine in `urxvt`, though. I'm assuming this has to do with some internals of Cursive, but it might be good to look into; I thought ncspot was broken until I tried a different terminal emulator.

Interestingly, forcing `TERM=xterm` makes everything work, so it might be terminal feature detection being screwed up?

**Comment by gyscos** [comment]
Hi!
That's interesting - what's `$TERM` before you override it to `xterm`?

If you have time, you could fetch `cursive` and try the `key_codes` example, see what happens when you press the some F-keys. If that's a problem (and it sounds likely), we may post a Cursive issue as well.

**Comment by barzamin** [comment]
* urxvt (`$TERM = rxvt-unicode-256color`): **works**
* xterm (`$TERM = xterm`): **works**
* GNOME terminal (`$TERM = xterm-256color`): **works**
* Termite (`$TERM = rxvt-unicode-256color`): **breaks**
* Termite (`$TERM = xterm-termite`): **breaks**

Note that `$TERM` for termite was being overridden to `rxvt-unicode-256color` by a dotfile I forgot about. If it takes the value `xterm-termite`, or if it's overridden to `xterm-256color` like GNOME terminal, everything works fine.

Looks like this one was entirely user error! Don't know why `rxvt-unicode-256color` made everything interplay wrong versus `xterm-256color` (or just `-termite`), but it's pretty much my fault and Cursive definitely shouldn't be expected to handle this.

Sorry for the trouble, @hrkfdn and @gyscos :)

**Comment by barzamin** [comment]
@hrkfdn I ran `key_codes` for you in Termite with various `$TERM`, pressing <kbd>F3</kbd>. Not sure if you care at this point, but it might be vaguely interesting:
![image](https://user-images.githubusercontent.com/20133857/53978765-a4e00c80-40d1-11e9-94c1-f0a616da6046.png)

**Comment by gyscos** [comment]
I'm glad you solved the problem!

ncurses (the backend used here by cursive) uses TERM to map the input escape codes to actual events. Since rxvt and VTE use different codes, the TERM variable is the only way to know how to parse it.

We might add some bad-TERM-detection logic when an unexpected code is received, like here, but that's another story... :)
