### ISSUE TITLE
Runtime error when playing a song

### ISSUE THREAD

**Issue by raccoondude** [hrkfdn/ncspot#201]
Whenever I run ncspot from source (cargo run) or from an executable the program exits and no error message is shown, debug log shows nothing strange, the deps are installed

Im using a gentoo based distro, anyone else having this issue? I have nothing to add as too why this may be happening because I don't see anything strange outside of it crashing

**Comment by hrkfdn** [comment]
Could you check if something is logged to stderr, e.g. via `RUST_BACKTRACE=full cargo run -- -d /tmp/debug.log 2>>/tmp/debug.log` and by checking `/tmp/debug.log`?

**Comment by raccoondude** [comment]
dbus error
