### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by Ahummeling** [hrkfdn/ncspot#205]
Attemping to compile ncspot using the readme on a fresh install of debian 10.3 (with apt-get update/upgrade) leads to the following error:
```
error: failed to run custom build command for `libdbus-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installZ9ZKFF/release/build/libdbus-sys-ed980eaf7f9e6b8b/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\nPackage dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n" } }', /home/arend/.cargo/registry/src/github.com-1ecc6299db9ec823/libdbus-sys-0.2.1/build.rs:6:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to compile `ncspot v0.1.3`, intermediate artifacts can be found at `/tmp/cargo-installZ9ZKFF`

Caused by:
  build failed
```

I was able to resolve this by installing `libdbus-glib-1-dev`, maybe this package can be added to the readme.

**Comment by daniel-vera-g** [comment]
Hey, on Ubuntu 18.04 I could compile it without `libdbus-glib-1-dev`.

Nevertheless, with:
> Attemping to compile ncspot

Do you mean compiling by source(`cargo build --release`) or installing it directly via cargo(`cargo install ncspot`)?
The last one did not work out for me(See mentioned issue).

**Comment by Ahummeling** [comment]
It's been a while, I think I used `cargo install ncspot` aswell. 
Are you sure you do not have `libdbus-glib-1-dev`? You can check with `apt list | grep libdbus-glib-1-dev`. 

I think I tried to compile it from source afterwards, learned my version of rust was too outdated, so I tried compiling rust from source. Then my old HDD died, so I gave up,  waiting for my new SSD now and then I'll try again.

**Comment by daniel-vera-g** [comment]
Ah, ok.
On Ubuntu 18.04:
1. For me compiling from source without `libdbus-glib-1-dev` worked out successfully.
2. Using `cargo install ncspot` failed but `cargo install ncspot --locked` fixed it as described here:
https://github.com/hrkfdn/ncspot/issues/212#issuecomment-651350764
