### ISSUE TITLE
question: how to remove a track from playlist

### ISSUE THREAD

**Issue by grerrg** [hrkfdn/ncspot#209]
i'm kinda shocked that i couldn't find anything by searching for "delete/remove". (am i really the only one stumbling across this?)

how can i remove a track from a playlist?

the context menu (`shift+o`) allows only to add a track to a playlist. but when being in a playlist i also want to be able to remove a song from the playlist.

**Comment by hrkfdn** [comment]
In the library/playlist view, `d` should remove a track from a playlist

**Comment by thomasrstorey** [comment]
I am also unable to delete a track from a playlist. What I have tried so far:
1. Go to Library view (`F3`)
1. Go to detail/context view for my playlist (`o`)
1. Navigate to track I want to remove and remove (`d`)
Nothing seems to happen when I hit `d` though

**Comment by hrkfdn** [comment]
Huh, you guys are right. The feature was never there.

**Comment by thomasrstorey** [comment]
I am extremely a rust newbie but would be willing to take a crack at this if you're busy. :)

**Comment by hrkfdn** [comment]
Sure, go ahead. Contributions are always welcome and appreciated :)

This API seems like a good fit for the task: https://docs.rs/rspotify/0.8.0/rspotify/spotify/client/struct.Spotify.html#method.user_playlist_remove_specific_occurrenes_of_tracks

**Comment by thomasrstorey** [comment]
I have gotten it to successfully make the correct API request to spotify when you hit `d` on a track in the playlist view, but I can't seem to figure out how to trigger a redraw with the updated track list after removing the track from the playlist and updating the playlist cache. Any guidance/pointers would be appreciated!

**Comment by jtmr05** [comment]
did this actually fix it? it still seems like nothing happens when I hit `d`
