### ISSUE TITLE
Question: Testing strategy

### ISSUE THREAD

**Issue by felipesere** [hrkfdn/ncspot#21]
I understand this is still (?) a toy project, but I was wondering what the test strategy for it would be, 
given that it is mostly "glue" between Spotify and Cursive?

Its fun to hack around, but there is a good chance I'll break something in a way the compiler doesn't catch.

An app like this would be an interesting project to explore how the Rust community factors/refactors/designs code to make it testable und understandable 😃

**Comment by hrkfdn** [comment]
No testing strategy so far for reasons you've mentioned. But I'm open to suggestions :smile: 
Also, I'd love this to be a usable client, so we'll definitely need tests at some point.
