### ISSUE TITLE
Checkmark on all playlists on search

### ISSUE THREAD

**Issue by daniel-vera-g** [hrkfdn/ncspot#213]
I'm not sure whether this is an issue or a feature but I could not find anything related.

I assume a check mark means, that the song/playlist/... is in a `saved` state.

In the `v.0.1.4` version searching for a topic and looking at the playlist section it shows me all playlists as saved(See image). In comparison, on the `songs` tab, only `saved` songs are ticked.

![image](https://user-images.githubusercontent.com/28257108/86411018-322e7380-bcbc-11ea-97e1-2b16d1c9bacc.png)

**Comment by hrkfdn** [comment]
That's a bug. It should only have a checkmark, when the playlist is saved/subscribed.
