### ISSUE TITLE
timeout?

### ISSUE THREAD

**Issue by ShaneEverittM** [hrkfdn/ncspot#216]
After a large duration of being paused, upon resuming no sound is produced. This is difficult to reproduce specifically because the time period is so long. I think I remember seeing somewhere on a forum talking about this being related to the network connection being unable to reconnect. Sorry if this is vague, will look more into it.

**Comment by hrkfdn** [comment]
Which version is this?

**Comment by ShaneEverittM** [comment]
0.1.4 I did some more digging and the behavior seems to be something that is also in the official Spotify desktop application. It is resolved by trying to play another song then trying to play the stuck song, both in ncspot and the Spotify app, so it may not originate here.

**Comment by hrkfdn** [comment]
Unfortunately I can't really reproduce or debug this. If the issue persists, feel free to open another issue with a log/backtrace. Until then I'll close this one for now, hope you don't mind.
