### ISSUE TITLE
CLI commands

### ISSUE THREAD

**Issue by nagy135** [hrkfdn/ncspot#226]
Hello, loving this app, its absolute replacement to my spotify electron garbage ...I have just one issue. I m used to binding stuff to my keyboard and I would like to have binds for `pause/play`, `next/previous song`. With spotify app I could do that via `dbus-send`. Is this possible at all in current state ? Is there any way to communicate with running instance ?

**Comment by hrkfdn** [comment]
You can communicate with the current instance via MPRIS/DBus, e.g. with `playerctl`.

**Comment by nagy135** [comment]
Havent heard of that, but installed and works flawlessly ...thanks. Closed
