### ISSUE TITLE
Confirmation on certain actions

### ISSUE THREAD

**Issue by ghost** [hrkfdn/ncspot#227]
Please add a confirmation for certain actions, for example when pressing `d`, it should confirm "Do you want to delete this track from your playlist? Y/n". Maybe also for `c`, when clearing the whole queue "Are you sure you want to clear the queue?". And when quitting by pressing `q` "Do you want to quit ncspot?". I've been pressing these keys accidentally many times now and deleted tracks I don't know how to restore and so on...

Thanks!

**Comment by hrkfdn** [comment]
Hi! I have added a confirmation dialog before deleting the queue. I'm sorry if you lost tracks by accidentally hitting `d`, but I've checked and it matches the official clients behavior. Especially when a user wants to delete multiple tracks, having to confirm each deletion seems a little excessive.

**Comment by Qluxzz** [comment]
Wouldn't a single prompt on single and multiple tracks be better? In the client "Remove from Playlist" is an option in the context menu so it takes two clicks to remove a track from a playlist, making it a more concious act.

I agree with the original poster that it is very dangerous to have such a destructive act hiding behind a single key.
