### ISSUE TITLE
ncspot does not like running in tmux

### ISSUE THREAD

**Issue by jrcharney** [hrkfdn/ncspot#228]
First off, thanks for making an awesome application. I like how I can simply enter in my user credentials and run everything in one app instead of needing to run a daemon like with many other applications.

I only have three issues with this program, one of which is how `cargo` does compiles things (which is something to complain to the Rust folks about.), the second issue is how `snap` does things (who put's a `snap` directory in the home directory and doesn't make it hidden?! Blame Canonical for that.), and the third item which I think you can fix: `ncspot` will not run in `tmux` because the terminal (`$TERM`) is set to `tmux-256colors`.

That third item is why I am here today.

I'm glad to report that the `snap` version (which I had to use because cargo ate all the 2GB of RAM my Raspberry Pi 4 has) does compile onto Raspberry Pi. I think the the `cargo` version will have better luck now that I've upgraded to the 4GB Pi 4 (which honestly the Rust people need to learn how to use virtual memory (disk space) to compile all their stuff instead of bogarting the precious RAM. Again that's a problem for them to fix. (`snap` is nasty. I uninstalled `ncspot` to get rid of `snap` simply because I wasn't going to use a version of software where the software manager was so blatantly obnoxious to store itself on my home directory in a visible directory.)

So what's the problem? What's my issue?

Put it simply `ncspot` will not run in `tmux` because it's terminal is `tmux-256colors`. I was running this in `zsh` and it ran, so why would it refuse to run in a terminal multiplexer with 256 colors?

I'm certain whatever it is is a simple fix as other applications like `spotify-tui` (which you should really team up with @Rigellute or offer to make a couple parts of his project better) works well.

Considering this is an `ncurses` program, `ncspot` should be capable of running inside `tmux`. (In fact, that's kind of the appeal I had to `ncspot`. The name kind of indicated `ncurses` support.

I'm sure with a little modification this can fix this.

OS: Manjaro Linux ARM 20.06
Kern: aarch64 (I don't have the full number on me right now.)

**Comment by hrkfdn** [comment]
Hey, what exactly is the problem? Does it give you an error message?

I just tested this locally and ncspot runs fine in tmux here, however, `TERM` is set to `screen-256color` by default here.

**Comment by jrcharney** [comment]
That's odd. I though I explained it.

Sure it might work where `$TERM` is `screen-256color` (probably because you are using `screen`), but it won't run in `tmux` (where `$TERM` is `tmux-256color`).

It needs to work in `tmux`!

**Comment by hrkfdn** [comment]
Hey, I'm still not sure what you mean when you say "it doesn't run". Any console output? What's the observed behavior?

I did test it in tmux. I don't know why it doesn't run with your setup, but it's most likely not a fault of ncspot, as I don't handle `TERM` settings. I could be within the cursive or pancurses crate. You could also try the ncurses backend instead of pancurses (see https://github.com/gyscos/cursive/wiki/Backends).

**Comment by sn0opy** [comment]
> Sure it might work where `$TERM` is `screen-256color` (probably because you are using `screen`), but it won't run in `tmux` (where `$TERM` is `tmux-256color`).

Sorry to bust your bubble, but https://github.com/tmux/tmux/wiki/FAQ
> Inside tmux TERM must be "screen", "tmux" or similar (such as "tmux-256color")

also: 
* https://github.com/tmux/tmux/wiki/FAQ#why-do-you-use-the-screen-terminal-description-inside-tmux
* https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal
* https://github.com/tmux/tmux/wiki/FAQ#why-do-you-use-the-screen-terminal-description-inside-tmux

**Comment by jrcharney** [comment]
Yeah...I've realized this was all me.

tmux's term should be `xterm-256color`. I had to figure that out the hard way when vim was acting weird in tmux.
