### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Herbstein** [hrkfdn/ncspot#23]
This is a tracking issue at this point.

I just tested after 41164df was commited, and #10 was closed. 

Cursive linking and compilation seems to work well now. 

The big issue is that right now librespot is configured to use pulseaudio as the backend. And, without fiddling with an MSYS2 installation, I don't think there's any way of making that work on Windows in a satisfactory way. However, it seems librespot want to move away from having their own internal playback implementation, and instead delegate it to the `Rodio` crate - discussed in librespot-org/librespot#195. This is being done in the librespot-org/librespot#277 pull request, though it seems progress has slowed a bit.

Looking at the `main.rs` file, I can also tell that you are making some assumptions about there being a `$HOME` environment variable, which you can't on Windows. Through a quick look around it seems [`app_dirs`](https://crates.io/crates/app_dirs) is a preferred way to find resource directories.

I didn't see anything else, but there might be some more lurking in there.

**Comment by hrkfdn** [comment]
Some solid points, thanks. I'll keep it open so once I have some time I might be able to tackle some of these or maybe someone else would like to have a look.

**Comment by Herbstein** [comment]
Just a small update. The Rodio backend for librespot almost kinda works. I'm experiencing some problems, but it seems the developer of the backend isn't. More testing is needed, but the prospects look great.

**Comment by ashthespy** [comment]
For the impatient - the `portaudio` backend works quite fine with Windows - have it running here on Win10 a few months now now issues.

**Comment by hrkfdn** [comment]
I have switched over to the Rodio backend, which is what librespot uses by default now. It should work on macOS and Windows out of the box. Reports are appreciated :)

**Comment by hrkfdn** [comment]
I have moved over to PulseAudio by default again, as Rodio blocks a whole CPU thread in idle.

Optional linking with PortAudio/Rodio backend is still supported. I'm closing this for now.

**Comment by terndrup** [comment]
Sorry to comment on a closed issue but how are you guys getting it to work on windows? My install or local build just fails with libdbus-sys errors

**Comment by Herbstein** [comment]
I haven't been involved here for some time, but I got to the login screen just now with the following command:

```
cargo run --no-default-features --features rodio_backend,cursive/pancurses-backend
```

Make sure to use the MSVC-based rustc, and not the GNU-based one. Further, after logging in with Facebook I get a hang (looks like some infinite loop?), but after restarting it works perfectly and I get audio as expected.

**Comment by terndrup** [comment]
@Herbstein awesome that did the trick!
