### ISSUE TITLE
Add 'G' and 'gg'

### ISSUE THREAD

**Issue by JojiiOfficial** [hrkfdn/ncspot#230]
Using G and gg to navigate to bottom/top of a list like in vim would be a nice feature

**Comment by BachoSeven** [comment]
Hey, this was already implemented a few months ago. In fact, you can remap any set of keys to `move top` and `move bottom` actions.

Have a look at https://github.com/hrkfdn/ncspot/pull/167

**Comment by JojiiOfficial** [comment]
The only thing I could achieve with remapping keys is using `G` to go to the bottom and `g` to go to the top. Having to press `g` twice (like in vim) seems not to be working?

My config:
```toml
[keybindings]
"G" = "move bottom"
"g" = "move top"
```

**Comment by BachoSeven** [comment]
I had also tried to use `gg` or `g+g`, but I don't think that combining two or more non-modifier keys is supported...

Btw, cli apps which use vim bindings often use a single `g` too (i.e. `sxiv`, `stig`) when there is no need for as many keybindings as in vim itself (and one keypress is better than two imo)

**Comment by JojiiOfficial** [comment]
Yes I think 'g' is enough. It's a music player, not a music editor :D
I think this question is answered.
