### ISSUE TITLE
Cannot set custom binding for 'save'

### ISSUE THREAD

**Issue by redschalken** [hrkfdn/ncspot#231]
It does not seem possible set a custom binding for the 'save' action. Consider this simple configuration, in which I drop the default keybindings and then set the bare minimum needed to demonstrate the problem and then quit:

```
default_keybindings = false

[keybindings]
"?" = "help"
"s" = "save"
"q" = "quit"
```

If I run ncspot and then press ? to see the current bindings, I see this:

```
Keybindings

Custom bindings can be set in /home/user/.config/ncspot/config.toml within the [keybindings] section.

? -> help
q -> quit
```

The problem happens even without dropping the default keybindings, as in this config:

```
[keybindings]
"s" = "shuffle"
"Shift+s" = "save"
```

`s` does get rebound to do shuffle, but `Shift+s` still does stop. Save ends up bound to no key.

This is on ncspot 0.2.0 on OpenBSD -current (July 27 snapshot).

**Comment by hrkfdn** [comment]
Thanks for the detailed report. Should be fixed.
