### ISSUE TITLE
How to change the color of rest of the progress bar?

### ISSUE THREAD

**Issue by aabbcdd99** [hrkfdn/ncspot#233]
Is it possible to change the color of this part of the progress bar (image below)? Would be nice to have a variable, such as `statusbar_progress_remaining`, or something similar.

![](https://upload.vaa.red/i/kZJTc.png)

**Comment by 20repsej** [comment]
"statusbar_progress_bg" does this.

**Comment by aabbcdd99** [comment]
Thank you. Closing.
