### ISSUE TITLE
Theme generator

### ISSUE THREAD

**Issue by vaared** [hrkfdn/ncspot#235]
Heya!

I did a simple web interface for generating themes. You can find the tool here: https://ncspot-theme-generator.vaa.red

Before it was kind of a pain in the ass to try and test the colors editing the hex values in the config.toml file, but hopefully we now have a little user-friendlier way to do this! This tool is not perfect, but it's something.

GitLab here: https://gitlab.com/vaared/ncspot-theme-generator

Thanks for doing this awesome project @hrkfdn.

**Comment by hrkfdn** [comment]
This is so cool, thanks a lot. Do you mind if I link this in the README?

**Comment by vaared** [comment]
I don't mind at all - it would be awesome!
