### ISSUE TITLE
Windows linker error on nightly Rust (unresolved external symbol __imp_ExtractIconW referenced in function get_app_icon)

### ISSUE THREAD

**Issue by udoprog** [hrkfdn/ncspot#24]
Hey,

It seems like rust std will no longer link to `shell32.dll`, which is a dependency of pancurses (used through cursive for Windows support).

```
  = note: libpdcurses-b041d7947661b96d.rlib(pdcscrn.o) : error LNK2019: unresolved external symbol __imp_ExtractIconW referenced in function get_app_icon
          E:\work\repo\ncspot\target\debug\deps\ncspot-545a65ef205f4774.exe : fatal error LNK1120: 1 unresolved externals
```

Cursive and pancurses will need to be bumped once it has been fixed here:
https://github.com/ihalila/pdcurses-sys/pull/5

A temporary workaround is to add a `build.rs` in ncspot with the following in it for Windows users:

```rust
fn main() {
    println!("cargo:rustc-link-lib=dylib=shell32");
}
```

**Comment by udoprog** [comment]
Related: https://github.com/rust-lang/rust/pull/56568

**Comment by gyscos** [comment]
Should be fixed if you run `cargo update`

**Comment by hrkfdn** [comment]
@udoprog can you confirm it is fixed?

**Comment by udoprog** [comment]
I think so, but I can't test right now due to #38

**Comment by hrkfdn** [comment]
@udoprog I have switched to directories, wanna give it another spin? :)

**Comment by udoprog** [comment]
Yeah, fixed. Thanks!

**Comment by hrkfdn** [comment]
Great, thanks for reporting!
