### ISSUE TITLE
About artist? (feature request)

### ISSUE THREAD

**Issue by felleg** [hrkfdn/ncspot#240]
One of the features I really enjoy from the Spotify client is being able to read an artist's biography. Is this something that could feasably be added? 

![image](https://user-images.githubusercontent.com/7781739/89655300-e7de7a80-d897-11ea-95c2-987aafb0eb71.png)

**Comment by hrkfdn** [comment]
Looks like this data is not exposed by the Spotify API: https://github.com/spotify/web-api/issues/207

**Comment by felleg** [comment]
Good catch. The spotify/web-api repo is archived, so I created a follow-up question on their forum: https://community.spotify.com/t5/Spotify-for-Developers/Include-Biography-in-Artist-s-Metadata-in-Web-API/m-p/5015242#M904

**Comment by hrkfdn** [comment]
Closed for now as this API does not exist yet. Feel free to reopen once it can be implemented.
