### ISSUE TITLE
Create new empty playlist 

### ISSUE THREAD

**Issue by JojiiOfficial** [hrkfdn/ncspot#242]
Is there a way or reference how to create an empty playlist?

**Comment by hrkfdn** [comment]
@JojiiOfficial @TheBolliwood Could you explain the use case behind this? Is this to start with a new so tracks can be selectively added via context menu? In that case, would a `[Create new]` button in that menu also be an option?

**Comment by JojiiOfficial** [comment]
I'd like to create new empty playlists using ncspot. That's all.

**Comment by AndydeCleyre** [comment]
Ah, great, I just discovered this is possible, thanks!

FWIW, whenever I want to create a new playlist, it's to add a selected or playing track. So if there's a button to be added, I would put it on the Add to Playlist dialog.
