### ISSUE TITLE
(archlinux) AUR install apearantly not working.

### ISSUE THREAD

**Issue by NicTanghe** [hrkfdn/ncspot#244]
Hello I installed ncspot via the aur (arch community packagerepository).
When I type ncspot in the terminal and pres enter nothing happens.

Command is also not recognized

Am I doing something wrong?

**Comment by mtshrmn** [comment]
Might be a silly question, which package did you use? `ncspot` or `ncspot-git`?

**Comment by NicTanghe** [comment]
Apearantly the normal ncspot crashes my terminal during installation.

Trying instakking the -git version now.

**Comment by NicTanghe** [comment]
Istalling the git version worked.

Thought you wouldn't need a premium qcount for this version :(

**Comment by Bettehem** [comment]
> Istalling the git version worked.
> 
> Thought you wouldn't need a premium qcount for this version :(

You need a Spotify Premium account to stream audio from any other source than the official client.
They don't allow streaming audio with free accounts using the API

**Comment by hrkfdn** [comment]
Please try again with the latest release. If that doesn't fix it, let me know!
