### ISSUE TITLE
support without a desktop environment

### ISSUE THREAD

**Issue by vkb24312** [hrkfdn/ncspot#249]
Songs do not play unless I'm using a desktop environment.
This is Kubuntu with KDE plasma. It works fine in the Konsole. But when I try running it from tty2 or similar, it doesn't have any sound. Everything else works perfectly. I downloaded it via snap.
Am I missing something?

**Comment by hrkfdn** [comment]
It looks like your ncspot is built against the pulseaudio backend, which does not when a desktop session does not exist.

You could either run pulseaudio in your tty or build ncspot with portaudio or alsa (see https://github.com/hrkfdn/ncspot#audio-backends).
