### ISSUE TITLE
Windows support ?

### ISSUE THREAD

**Issue by NicTanghe** [hrkfdn/ncspot#254]
since it requires 

libpulse-dev (or portaudio-dev, if you want to use the PortAudio backend)
libncurses-dev and libssl-dev
libdbus-1-dev
libxcb

Probably not.
But spotify + spicetify is eating my cpu :`(

**Comment by swarfega** [comment]
If you have WSL installed you could always install it on there.

**Comment by NicTanghe** [comment]
Oh, weird that I didn't think of that. 
Does the sound work tho ?

Also, if you could put that in the readme it could help others

**Comment by swarfega** [comment]
I don't know as I've not used any sound software in WSL. Worth a shot though.

**Comment by Bettehem** [comment]
I tested ncspot with WSL2 in a Windows VM and it worked nicely with pulseaudio.

**Comment by 42wim** [comment]
For those looking to make this work on windows, with this comment https://github.com/hrkfdn/ncspot/issues/23#issuecomment-603955270 you can build/run it.
Maybe a windows binary can be added to the releases ?
