### ISSUE TITLE
Nerd fonts

### ISSUE THREAD

**Issue by voidpin** [hrkfdn/ncspot#258]
Quick question,
Is there a config or build option to disable nerd font by default.
I would like to build it with nerd fonts disabled.
Thx

**Comment by hrkfdn** [comment]
Not a build option, only a config option: https://github.com/hrkfdn/ncspot#configuration. It is off by default.

**Comment by voidpin** [comment]
Thanks!
It wasn't really clear from the README that it was off by default.
Closing this issue now.
