### ISSUE TITLE
how can I clear saved credentials?

### ISSUE THREAD

**Issue by colegleason** [hrkfdn/ncspot#259]
I accidentally logged into the wrong Spotify account, one that isn't premium. Now when I start ncspot it throws the "Authentication failed with reason: PremiumAccountRequired" error and crashes. But I can't find where credentials are stored to erase and retry (nothing in ~/.config).

**Comment by hrkfdn** [comment]
What platform? On Linux `~/.config/ncspot/credentials` contains your credentials and `~/.cache/ncspot/librespot/credentials.json` stores cached your token. It may be you need to delete both.

**Comment by colegleason** [comment]
I'm on OSX, neither of those folders exist (maybe not yet?). This is the first run using `cargo run --no-default-features --features portaudio_backend,cursive/pancurses-backend`

**Comment by hrkfdn** [comment]
On OSX the folders are stored according to macOS policies. The config should be in `~/Library/Preferences/org.affekt.ncspot` and cache in `~/Library/Caches/org.affekt.ncspot`.

**Comment by colegleason** [comment]
Great, I was able to delete the credentials file and login properly. Thanks!

**Comment by hrkfdn** [comment]
Should be fixed with the removal of cached ncspot credentials.
