### ISSUE TITLE
Crash on play with no notification server and notify=true (0.2.2)

### ISSUE THREAD

**Issue by WhoRegisteredAllTheGoodUsernames** [hrkfdn/ncspot#265]
After updating to 0.2.2 tried to play a song/album/playlist but crashed without any message, tried with `RUST_BACKTRACE=1` and `RUST_BACKTRACE=full` but no output. It happens in all screens, and everything else works as normal.
### steps to reproduce:
1. Update to 0.2.2 with makepkg -sirc
2. Launch ncspot
3. Try to play something
4. Crash without any error :3

Here is the debug log:
[https://drive.google.com/file/d/1uxvMawqIbDIleRxMpvWGTM6iOYM8PhIB/view?usp=sharing](url)

`uname -a` Output:
`Linux user 5.8.6-arch1-1 #1 SMP PREEMPT Thu, 03 Sep 2020 17:27:39 +0000 x86_64 GNU/Linux`

**Comment by hrkfdn** [comment]
Could you try logging stderr, e.g. by calling it like so: `ncspot -d debug.log 2> stderr.log` and see if that gives you anything?

**Comment by WhoRegisteredAllTheGoodUsernames** [comment]
Here is the output:
[https://gist.github.com/WhoRegisteredAllTheGoodUsernames/3276da44f82faa01039cb3576feb8827](url)
It complains about the notifications, which are activated in the configuration file (`notify = true`), I forgot this since I was trying them a few months ago, and at the end I ended uninstalling any notification server and in the previous version it looked like it just ignored that option.
