### ISSUE TITLE
Update the "help->keybinding" section

### ISSUE THREAD

**Issue by MartinAramayo** [hrkfdn/ncspot#266]
I come up with this when I found that the _readme.md_ of this repository says what _"space"_ does, but that does not appear inside the help screen called with _?_ inside _ncspot_. I may be able to change it if someone tells me how.

**Comment by mtshrmn** [comment]
for me it appears right at the top, it's just a blank (literally a space) so maybe that's confusing. 
![image](https://user-images.githubusercontent.com/18540571/93189188-889f4000-f74a-11ea-975f-4e62b7cb78a1.png)

**Comment by MartinAramayo** [comment]
It's true, sorry. Maybe I had ignored it because it seems unclear to me what the meaning was, in other programs like Zathura the manuals say "space" explicitly. It is possible to change it so it says "space" like in the readme.md? Sorry if it comes as nitpicking, but details like this might be very helpful for new users like myself.

**Comment by mtshrmn** [comment]
I don't think we'll see this in upstream anytime soon, so I've added it to my own [fork](https://github.com/mtshrmn/ncspot). It has some extra features but It's mainly the same as the upstream.

**Comment by hrkfdn** [comment]
> I don't think we'll see this in upstream anytime soon

I'll gladly take a patch 😄

**Comment by mtshrmn** [comment]
My fork is a mess to merge, so I'll just paste the patch here, hopefully that's enough
```diff
From 6270bdc3973be6073aada4ae1d947ca3730ff80d Mon Sep 17 00:00:00 2001
From: Moshe Sherman <moshesher1998@gmail.com>
Date: Tue, 15 Sep 2020 23:37:11 +0300
Subject: [PATCH] give proper name to the space key

---
 src/commands.rs | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/src/commands.rs b/src/commands.rs
index fd5f7d5..1575227 100644
--- a/src/commands.rs
+++ b/src/commands.rs
@@ -268,7 +268,7 @@ impl CommandManager {
         kb.insert("<".into(), Command::Previous);
         kb.insert(">".into(), Command::Next);
         kb.insert("c".into(), Command::Clear);
-        kb.insert(" ".into(), Command::Queue);
+        kb.insert("Space".into(), Command::Queue);
         kb.insert("Enter".into(), Command::Play);
         kb.insert("s".into(), Command::Save);
         kb.insert("Ctrl+s".into(), Command::SaveQueue);
@@ -375,6 +375,7 @@ impl CommandManager {
     fn parse_key(key: &str) -> Event {
         match key {
             "Enter" => Event::Key(Key::Enter),
+            "Space" => Event::Char(" ".chars().next().unwrap()),
             "Tab" => Event::Key(Key::Tab),
             "Backspace" => Event::Key(Key::Backspace),
             "Esc" => Event::Key(Key::Esc),
-- 
2.28.0

```
