### ISSUE TITLE
[Request] Add option for bitrate

### ISSUE THREAD

**Issue by eulerfan271** [hrkfdn/ncspot#269]
Based on other questions, it seems ncspot uses an audio bitrate of 320kb/s.  Higher audio quality great!  However, the higher bitrate uses more cache storage and processing power, and sometimes can't be noticed due to poor headphones, poor hearing, etc.

I thus think it would be useful to have a "bitrate" configuration option (like spotifyd) to lower the bitrate if one wished.

Thanks for this fantastic project!

**Comment by hrkfdn** [comment]
Fixed by #270
