### ISSUE TITLE
[ Feature Request] Transparency

### ISSUE THREAD

**Issue by BachoSeven** [hrkfdn/ncspot#275]
Hi, I was wondering if it would be possible to implement an optional transparency for the background color.

**Comment by hrkfdn** [comment]
Hey, not sure how this is possible. Wouldn't this be usually done in the terminal emulator?

**Comment by BachoSeven** [comment]
So I do have terminal transparency enabled, and it does work with most other TUI apps I use(i.e. `neomutt`).

I think this could possibly be done by having `ncspot` optionally not draw any background color, so to leave it to the terminal as you said(?)

**Comment by hrkfdn** [comment]
Could you try setting `background` to `default` in your config and see if that helps?

**Comment by BachoSeven** [comment]
Ohh thank you, I don't know why I hadn't tried that.

I guess I have always had a custom theme since I first installed `ncspot` so I never really tried using the default. Closing this
