### ISSUE TITLE
Album view only shows the first 50 tracks

### ISSUE THREAD

**Issue by nwroot** [hrkfdn/ncspot#281]
ncspot v0.2.2 only shows the first 50 tracks in an album, possibly because of the way Spotify's [API](https://developer.spotify.com/documentation/web-api/reference/albums/get-albums-tracks/) works (max 50 tracks per request).

This issue is very similar to #5, but instead of search results, it's on album's track list.

Can be reproduced by opening (with "o" key by default) any album with more than 50 tracks (such as [this](https://open.spotify.com/album/5igTFdgbS1jxBpBufbcQA6) one).

**Comment by MNolan147** [comment]
I'm getting this issue currently, how were you able to fix it?
