### ISSUE TITLE
Set different pace for volume changing

### ISSUE THREAD

**Issue by victante** [hrkfdn/ncspot#282]
Would it be possible to have a configuration option that lets us choose at what pace the volume will be changed? For example, being able to set it so that every "+" increases 5% instead of just 1% etc.

I'm sorry if this is already possible, but reading the documentation I think there isn't such a feature yet.

Also, thank you very much for this app, it's awesome! Never used the web player anymore after discovering ncspot.

**Comment by whisperity** [comment]
Most other features have big step versions, but yeah, the volume does not.

**Comment by ChaboCode** [comment]
I thing I can work on it, let me try.

**Comment by ChaboCode** [comment]
Did it. #298
