### ISSUE TITLE
[Feature Request] Show daily mixes and other per-user generated content

### ISSUE THREAD

**Issue by whisperity** [hrkfdn/ncspot#283]
One big thing in Spotify that is not *easily* accessible from ncspot are daily mixes and other user-tailored content. While it's debateable how good they actually are, I find myself using some features often.

However, AFAIK the only way to find these mixes is to search their name, but that turns up millions of results because other people also save their `Daily Mix 1` as `Daily Mix 1`.

**Comment by mtshrmn** [comment]
This is a limitation within the Spotify API, unfortunately they don't plan on documenting this endpoint :frowning_face:

**Comment by whisperity** [comment]
Oh, that's a real bummer... and stupid.
Anyways... I do believe we could still side-step this issue.

First, I see that daily mixes also have unique playlist URLs, like this: https://open.spotify.com/playlist/37i9dQZF1E37raiTuxaDUQ?si=_1FZlTbwQsewmJwuGDgbHA

And while when logged out of Spotify it does not show whose playlist it is:
![Screenshot_20201009_154444](https://user-images.githubusercontent.com/1969470/95590479-64333c80-0a46-11eb-914c-c2f3b15671ee.png)

it does when you're logged in:
![Screenshot_20201009_154623](https://user-images.githubusercontent.com/1969470/95590639-99d82580-0a46-11eb-9a8f-6fb75d865dd4.png)

I tried to sniff but it seems the desktop Spotify app isn't an Electron thingie, at least if it is they disabled the developer console...

Worst case, it could be done in an ugly way by making an HTTP request and sniffing out the results? :hushed:

**Comment by mtshrmn** [comment]
I've created an [issue](https://github.com/ramsayleung/rspotify/issues/104) in the rspotify library. The best way is to implement it there, but I don't think I have the time to do it myself.

**Comment by hrkfdn** [comment]
Closing this for now as it can't be implemented yet. Feel free to reopen once API support is there.

**Comment by JulienMar** [comment]
A temporary solution (but this requires opening Spotify in another client) is following the Daily Mixes. They will then show up in your playlists.
