### ISSUE TITLE
Background mode / suspend ignored

### ISSUE THREAD

**Issue by whisperity** [hrkfdn/ncspot#284]
The client seems to ignore `SIGTSTP` (`C-z` suspend).
I'd wish a background mode was supported, e.g. after putting a queue together, I could put it to the background and keep playing (I understand this requires some restructuring as the main process is frozen in this case), and switch between individual songs with the media keys on my keyboard. (Using KDE and the integration to the media daemon works amazing!)

In addition, as ncspot does not support local songs, I often find myself "tabbing out" to another cli player, like `nvlc` or something. Switching the two in the background would be a breeze!

**Comment by mtshrmn** [comment]
About running it in the background - Why not just detach it? I'm using `screen` and it's working flawlessly.

**Comment by ChaboCode** [comment]
I think it can be a little bit complicated, because it needs to create a background process playing the music and sleep the main process with the menu. I don't know anything of Rust, so I don't know how to fork and create processes. Let me search about that and se if I can do something.

**Comment by hrkfdn** [comment]
Hey, a "daemon" mode is not on the roadmap for now, as it would require major restructuring. Sorry!
