### ISSUE TITLE
Cargo crate depends

### ISSUE THREAD

**Issue by voidpin** [hrkfdn/ncspot#286]
Hi, pkgsrc maintainer here.
NetBSD has an helping tool to generate raw pkg Makefiles from an URL, `url2pkg`.

You probably don't need to know this, but the issue is that up to commit f40b36c9671ca346f299cd2a092cea84b7513ced `url2pkg` was able to identify all dependency crates and generate a list of `CARGO_CRATE_DEPENDS`. This is not working on the v0.2.3 release.

There're 401 crate dependencies in total and it's a nightmare to go through all of them manually.

So, I wonder what changed in the last 4 commits that could have induced this behavior change?

Thanks.

**Comment by voidpin** [comment]
Actually, commit f3c66111a29be19280c74521e01967db78113719 works also.
While commit b9dfc09421b9f8cd19f4abbffe63c8bb48744ab6 does not, so the change was introduced in this one.

**Comment by hrkfdn** [comment]
Hmm, looks like the `Cargo.lock` format changed recently: https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md

> If Cargo.lock needs to be updated, then it will be automatically transitioned to the new V2 format. This format removes the [metadata] table, and should be easier to merge changes in source control systems. This format was introduced in 1.38, and made the default for new projects in 1.41. https://github.com/rust-lang/cargo/pull/8554

This was made default with Rust 1.47, so this will show up with other ports as well in the future. OpenBSD has a similar task and could also be affected.

**Comment by voidpin** [comment]
I see, so your suggestion is that I report this to NetBSD?

**Comment by hrkfdn** [comment]
I suppose so, in any case this is not something ncspot specific, as this file is generated by cargo.

**Comment by voidpin** [comment]
Ok, thanks. I'll report the behavior change.
I've managed to start compiling the new release by pulling the crate list from the last working commit and manually adding the versions from the current Cargo.lock file.

Closing the issue now.

**Comment by voidpin** [comment]
@hrkfdn `ncspot-0.2.3` has now been merged into pkgsrc.
