### ISSUE TITLE
Queue should remember currently selected item

### ISSUE THREAD

**Issue by hrkfdn** [hrkfdn/ncspot#3]
As *Cursive* provides no mutable access to `ListView` entries, the entire list is re-drawn on queue changes, such as the player consuming the next track.

This moves the cursor back to the top. Before redraw, the queue should store the selected entry and restore selection after redrawing the list.

**Comment by gyscos** [comment]
Hi! If possible, I'd love to make cursive easier to use!

`ListView` is indeed missing some ways to remove existing views. I could add these methods, but there's a better alternative! Most of the time, a `LinearLayout` wrapped in a `ScrollView` achieve the same result as a `ListView` (`ListView` was a "temporary" solution before `ScrollView` was available).

`LinearLayout` does have `remove_child` and `get_child_mut`. On the latest git branch, there is also `insert_child` and `swap_children` for more ways to update the list without the need to re-create it entirely.

**Comment by hrkfdn** [comment]
Ooh, that is good to know, thanks for chiming in, I'll look into that.

Great work on Cursive, it's been very helpful!
