### ISSUE TITLE
"Import" own music

### ISSUE THREAD

**Issue by JojiiOfficial** [hrkfdn/ncspot#300]
I was thinking about a feature which lets you add your own music (files) to your playlists/queue/library/... . Additional data could be stored local in a file and simply "added" to the listviews. The player would decide between playing from spotify or the local audio file. I know that this isn't really the intend of this project but since spotify and its official client doesn't support such a feature, it's still nice to have in my opinion. Before I get deeper into details or think about the way I'd implement it, I wanted to know what the community of this project thinks about such a feature.

What do you guys think? Would you like it or rather not?
@hrkfdn Would you accept such a feature in this repository?
I'd call myself ready to (try) to implement this feature if it gets accepted. Maybe there are more devs who would probably join me?

**Comment by hrkfdn** [comment]
Hey,

while it is a nice idea, I'm afraid that's out of scope of this project and I wouldn't be able to maintain this. Sorry!
