### ISSUE TITLE
Text truncation breaks on long titles

### ISSUE THREAD

**Issue by sloshyyy** [hrkfdn/ncspot#303]
![image](https://user-images.githubusercontent.com/45954802/97129351-09bc0080-1715-11eb-90b9-8ffcb2c63703.png)

Present on version 0.2.3 built from cargo

**Comment by hrkfdn** [comment]
This is 0.2.3 release, right? This should be fixed with https://github.com/hrkfdn/ncspot/commit/9fbbc7921e2ae95271732e69469c8a9cf8ae8933 in the upcoming release.
