### ISSUE TITLE
Not able to login with Facebook

### ISSUE THREAD

**Issue by Goth** [hrkfdn/ncspot#310]
I didn't have any kind of trouble signing in with Facebook in the past.
I reinstalled today my Arch and cannot sign anymore, works ok with the Spotify GUI.
Any idea?

**Comment by crayo** [comment]
I am also unable to log in using Facebook. Attempting to do so results in the following error page:

![Screen Shot 2021-01-13 at 7 44 40 AM](https://user-images.githubusercontent.com/3330029/104460078-3f81c000-5573-11eb-888a-ea7097559d1c.png)

**Comment by medwards** [comment]
Looks like the URL being used here https://github.com/hrkfdn/ncspot/blob/master/src/authentication.rs#L59 is out of date.

There is either a new endpoint to fetch URLs from (like `v2/config`) or a new URL in this endpoint (like `login_url2`) and `ncspot` needs to be updated to use it.

The authpoller (https://github.com/hrkfdn/ncspot/blob/master/src/authentication.rs#L74) likely also needs to get updated, especially if Spotify has dramatically modified its Facebook login process.

**Comment by MatthewPrinz** [comment]
I was also not able to log in with Facebook, but you can set up a device password and login that way. http://www.spotify.com/account/set-device-password/

**Comment by shannonrdunn** [comment]
> I was also not able to log in with Facebook, but you can set up a device password and login that way. http://www.spotify.com/account/set-device-password/

interesting this link just redirects to https://www.spotify.com/us/account/overview/
