### ISSUE TITLE
Login Error Loop

### ISSUE THREAD

**Issue by M4rk3h** [hrkfdn/ncspot#313]
After entering the wrong password when logging in on first try, stuck in a loop saying connection error: reason: PremiumAccountRequired.

But i'm pretty sure I entered the wrong password.

**Comment by JojiiOfficial** [comment]
So what's the point? You rather want to see "wrong credentials"? Or do you want it to work? (a premium account would help with this one) I don't get exactly what the problem is.

**Comment by liu2z2** [comment]
I'm quite sure 100%, but the credential data is saved by default in `~/.config/ncspot/credentials.toml` for ubuntu. Look somewhere like that and maybe delete it to reset the credential data?
