### ISSUE TITLE
MPRIS set volume support

### ISSUE THREAD

**Issue by benjaminBrownlee** [hrkfdn/ncspot#315]
I have keybinds that use `playerctl` to adjust the volume of the active player (which already works great for cmus and mpv), so it would be great if we could add volume MPRIS support to ncspot. I have not done any rust development before, but it looks like it would be as simple as adding a single function and registering it with dbus, and there are plenty of similar functions in the existing code base. 

Let me know if this is a welcomed change and I can take a crack at a pull request.

**Comment by AckslD** [comment]
Maybe support for `shuffle` could be added at the same time? :)

**Comment by Bettehem** [comment]
@AckslD Could you make a separate issue of that, I could probably add the shuffle feature pretty fast

**Comment by AckslD** [comment]
@Bettehem Cool, sure thing, I opened #317

**Comment by benjaminBrownlee** [comment]
So I have a fix that will actually return the correct volume, but I am having issues with moved value access if I try to define both a read and a write option (forgive my ignorance, I have never developed with Rust before). It appears the standard approach is to implement `Clone` and `Copy` but obviously we don't wish to clone the entire spotify client. Do we already have implemented a sort of interface or proxy to the spotify client that can be cloned and used for synchronized access? Or am I going about this all wrong?

Here is what I have so far for my modifications to mpris volume. Only `on_get` or `on_set` can be implemented at a given point (the other must be commented out to compile.
```rust
    let property_volume = {
        let spotify = spotify.clone();
        f.property::<f64, _>("Volume", ())
            .access(Access::ReadWrite)
            .on_get(move |i, _| {
                i.append(spotify.volume() as f64 / 65535_f64);
                Ok(())
            })
            .on_set(move |_, m| {
                let cur = spotify.volume() as f64 / 65535_f64;
                let req = m.msg.get1::<f64>().unwrap_or(cur);
                if req > cur {
                    let diff = ((cur - req) * 100.0) as u16;
                    let vol = spotify.volume().saturating_add(VOLUME_PERCENT * diff);
                    spotify.set_volume(vol);
                }
                else if cur < req{
                    let diff = ((req - cur) * 100.0) as u16;
                    let vol = spotify.volume().saturating_sub(VOLUME_PERCENT * diff);
                    spotify.set_volume(vol);
                }
                Ok(())
            })
    };
```

**Comment by r4v3n6101** [comment]
@benjaminBrownlee try to move line `let spotify = spotify.clone();` into closure or try making two separate variables in order to capture each of cloned values.

**Comment by r4v3n6101** [comment]
Also you should rewrite if/else branch because there are same conditions in branches. Try use abs/max/min to simplify code
