### ISSUE TITLE
Implement Spotify's Token-based Auth

### ISSUE THREAD

**Issue by pard68** [hrkfdn/ncspot#32]
[Spotify docs][0] outline a way to provide auth without the need for the username and password. Using this would remove the need for either the config file or a login screen (as another issue/enhancement has suggested). This method would provide the user with a unique URL and upon accessing this and logging into Spotify the user would be given a token for subsequent auth attempts made by ncspot. 

Using this method of auth would make this app more secure, eliminating the need to store credentials in plaintext or exposing credentials to this app at all. It would also remove the need to implement an initial login as [suggested here][1]. 

[0]: https://developer.spotify.com/documentation/general/guides/authorization-guide/
[1]: https://github.com/hrkfdn/ncspot/issues/1

**Comment by hrkfdn** [comment]
As far as aI know this won't work, as librespot (the player component) still requires username/password for authentication. So while we could use this for the web API requests that fetch metadata (playlists), we can't use it for the player and end up with two auth implementations.

**Comment by pard68** [comment]
ah, needs to be done upstream first. I'll take a look into librespot then!

**Comment by hrkfdn** [comment]
Cool, I'll close this for now. Feel free to re-open in case something changes :)
