### ISSUE TITLE
Panic where track in playlist has empty album

### ISSUE THREAD

**Issue by egorgam** [hrkfdn/ncspot#321]
I have a playlist where some tracks has empty album
![Screenshot 2020-11-15 at 21 56 20](https://user-images.githubusercontent.com/13712792/99193963-672ff400-278d-11eb-8207-245e89a7de7d.png)

When track with album ends, and player going to next track without album name, ncspot crashing
![Screenshot 2020-11-15 at 21 56 50](https://user-images.githubusercontent.com/13712792/99193972-79119700-278d-11eb-8b84-fbdeade80de7.png)

**Comment by ChaboCode** [comment]
Having songs in Spotify whitout album seems so illegal, kinda funny. But can you play that songs? I searched some of them but I didn't find anything.

**Comment by egorgam** [comment]
@ChaboCode songs cant be played, because panic is when it starts. I opened this playlist in Spotify electron client, looks like there is no takedown implementation in ncspot (and takedown tracks has empty album)  

![Screenshot 2020-11-16 at 13 12 19](https://user-images.githubusercontent.com/13712792/99240323-6179f300-280d-11eb-8d5e-d2a405bc4f0f.png)

**Comment by egorgam** [comment]
https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlists-tracks/

I think parameter "is_playable" may be useful for this case, when using in this function https://github.com/hrkfdn/ncspot/blob/db521d47ed23c275a78932b0e73c34d665f254c4/src/spotify.rs#L727

**Comment by hrkfdn** [comment]
Thanks for the report. Should be fixed.
