### ISSUE TITLE
Conflict with Official Spotify client's mpris:trackid implementation and MPRIS own specification

### ISSUE THREAD

**Issue by Bettehem** [hrkfdn/ncspot#323]
Hello,  there's a conflict between the way Spotify returns `mpris:trackid` and the way it should be implemented according to the [MPRIS specification](https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html#Mapping:Metadata_Map).

Spotify's official client returns a Spotify URI in the `mpris:trackid` field and that differs from the way it actually should be implemented.

How should this be done in ncspot? Because if a Spotify URI is returned in `mpris:trackid`, that goes against the MPRIS specification,  and if a dbus path is returned, that goes against Spotify's own implementation🤔

_Originally posted by @Bettehem in https://github.com/hrkfdn/ncspot/issues/322#issuecomment-729343898_

**Comment by hrkfdn** [comment]
I think I'd rather have ncspot implement MPRIS properly than copy Spotify's incorrect behavior. There is also `xesam:url` which may be more suitable for the Spotify URL. What do you think?

**Comment by Bettehem** [comment]
Yeah, I think you're right. It's better to implement MPRIS properly.
Also, while searching on Spotify's MPRIS implementation, I came across [this project](https://github.com/freundTech/SpotPRIS2) which apparently implements MPRIS for Spotify, better than the official client does, so I guess it's probably better not to worry about the official Spotify client's own MPRIS implementation anyways.
