### ISSUE TITLE
Change brew formula to build with portaudio

### ISSUE THREAD

**Issue by alexfromester** [hrkfdn/ncspot#333]
There some noises on the background while I'm playing songs on the latest version of macOS Cathalina

**Comment by hgvhgv** [comment]
Fyi I was able to improve audio output by using portaudio as the backend rather than the default rodio (see the above-referenced issues)

**Comment by s6joui** [comment]
Same problem here on macOS Catalina.

Solved by recompiling using portaudio with the following steps:

- Clone repo
- `cd ncspot`
- [Install Rust](https://www.rust-lang.org/tools/install):  `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
- Add cargo to PATH: `source $HOME/.cargo/env`
- Run `cargo run --no-default-features --features portaudio_backend,cursive/pancurses-backend`
- Edit config file: `nano ~/.config/ncspot/config.toml` add `backend = "portaudio"`
- Run ncspot: `./target/debug/ncspot`

**Comment by hrkfdn** [comment]
Is the brew package built with rodio? The formula should probably be updated to build with portaudio instead, it's also documented like this in the README.

**Comment by s6joui** [comment]
> Is the brew package built with rodio? The formula should probably be updated to build with portaudio instead, it's also documented like this in the README.

Yeah it's built with rodio! It would be great if it was updated :)

**Comment by hrkfdn** [comment]
Would be great if someone could take care of this. I don't maintain the formula and don't have a lot of experience with brew formulas, either.

**Comment by jkelol111** [comment]
`ncspot` has been updated to 0.5.0 on Homebrew, thanks to the kind folks over there. However, I'm getting an internal PortAudio error when trying to play anything:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Internal PortAudio error
```

**Comment by hrkfdn** [comment]
Current formula builds with portaudio
