### ISSUE TITLE
Can't play podcasts

### ISSUE THREAD

**Issue by bulak** [hrkfdn/ncspot#344]
Great software but I am having an issue playing podcasts.

After ncspot initializes without issues, I go to `Podcasts`, where I see my podcasts listed. When I chose one of them (for example BBC Radio 4 - The Infinite Monkey Cage), I get immediately some error messages dumped, which I can not copy but goes more or less like this:

>thread '\<unnamed\>' panicked at 'called `Option::unwrap()` on a `None` value', /home/***/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.3/src/player.rs:653:14

Afterwards, when I go the Queue page, I can see the full list of episodes from this podcast but when I try to play any of them I get the same error message and nothing is played. If go to Playlist or chose a track from an album, even after having these error messages, songs are played without problem.

I also ran ncspot with RUST_BACKTRACE=full and saved the debugging messages using the --debug argument. I am attaching the last couple hundred lines which seem relevant.

I am running ncspot 0.2.4 on Debian bullseye/sid testing around Linux 5.9.0-1-amd64 kernel.

I love ncspot, as I mainly use terminals and find it much better than GUIs I used so far. I'd appreciate if anyone can show me the right direction to fix this issue as I am only a starter in Rust and would love to listen to my podcasts in ncspot.

Many thanks,

Bulak
[ncspot_full_debug_tail.txt](https://github.com/hrkfdn/ncspot/files/5652076/ncspot_full_debug_tail.txt)

**Comment by hrkfdn** [comment]
Hey Bulak, thanks for the report.

Does this happen with every podcast? Librespot seems to be having problems with selecting the audio file for this episode: https://github.com/librespot-org/librespot/blob/89cafd7c86cd62ca0666a9a3d94eeb50fa51a16e/playback/src/player.rs#L650-L653

I can reproduce this with `playerctl -p ncspot open spotify:episode:1SEwzYYdOh61lAuP476zOI`. Can you try playing this podcast: playerctl -p ncspot open spotify:episode:2oE1P1VFA80gXBBsXcat9l (e.g. via `playerctl -p ncspot open spotify:episode:2oE1P1VFA80gXBBsXcat9l`). It plays fine here.

**Comment by bulak** [comment]
Thanks for the prompt reply. I don't have access to the same machine until Thursday. Meanwhile, I did a little reproducibility experiment on another machine: Ubuntu 20.04.1 LTS on Linux 5.4.0-56-generic kernel.

I can reproduce my earlier report. I don't have `playerctl` so I tried another podcast using `ncspot`: The Royal Institution - Ri Science Podcast and that one worked. So indeed the problem was podcast specific. I also tried the one you have suggested, `spotify:episode:2oE1P1VFA80gXBBsXcat9l` (Qualcomm’s Snapdragon 888 processor for 2021 Android phones ...) and I can confirm that one also worked without any issue in `ncspot`.

**Comment by ashthespy** [comment]
FWIW, `librespot`'s implementation of podcasts is minimal - it only supports podcasts that are available via the internal Spotify API. Newer podcasts from Spotify's recent acquisitions are all served via an external CDN that hasn't (yet) been implemented into `librespot`

**Comment by hrkfdn** [comment]
Then these are probably podcasts served via CDN.. :thinking:

**Comment by hrkfdn** [comment]
Needs to be implemented upstream: https://github.com/librespot-org/librespot/issues/309

**Comment by bulak** [comment]
Thanks again for this great project and your prompt response. Great work. I am closing this issue as there is not much to do on ncspot's side.
