### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by mickenordin** [hrkfdn/ncspot#350]
Is there a way to support this project financially? I just love the software and I am so happy to be using spotify with a free and open source client.

**Comment by hrkfdn** [comment]
Hey @mickenordin, at the moment there is no way to donate, as this is purely a hobby project, but I'm glad you like ncspot and really appreciate your message. Happy holidays!

**Comment by mickenordin** [comment]
Happy holidays to you to, like I said, I am very very happy that you are working on this project!
