### ISSUE TITLE
No album art when playing songs from 'Similar Tracks' option

### ISSUE THREAD

**Issue by Bracktus** [hrkfdn/ncspot#354]
I'm using playerctl to get the album art. The artUrl field is there but empty.

To reproduce:

- Open Selected (press o)
- Select 'Similar Tracks'
- Play any song from the playlist

**Comment by mtshrmn** [comment]
This is a limitation within the API, the recommendation endpoint returns a `SimplifiedTrack`, which doesn't hold information about the album. I was able to get around it by re-fetching all of the songs again using `spotify.track()`.  Even if you run each fetch in parallel this will still take some time (I haven't done any benchmarking, but I can clearly feel a subtle lag).

Here's my implementation attempt, I didn't try to merge it to upstream as I'm not sure this is a good enough idea.
https://github.com/mtshrmn/ncspot/commit/9db944e89ff1786334e8aff790ce469ae7bda075

**Comment by Bracktus** [comment]
Ah, thanks for taking the time to help. I guess it's just a matter of spotify updating their API then.

**Comment by hrkfdn** [comment]
Another option could be to fetch the full track details in background when a new track is played. I'll mark this as a bug for now. I wouldn't consider it critical but it should be fixed at some point. Thanks for the report!
