### ISSUE TITLE
As a user, I want to be able to collect search results in standard out

### ISSUE THREAD

**Issue by Rkubinski** [hrkfdn/ncspot#355]
Hey guys, trying to build my own UI for spotify for my raspberry pi. Currently using tux + ncspot as a backend. I am looking to abstract the search function and wrap it in my own and build my own UI around it. However, I am not sure if theres a way to actually collect the search results to a file for example ? 

Any ideas ? 
Thanks!

**Comment by Bettehem** [comment]
It's probably easier to call the spotify api directly for the search and then just use playerctl or something to play it from ncspot.
I have done this for my [musicbot](https://gitlab.com/Bettehem/ts3-musicbot/-/blob/song_queue/src/main/kotlin/ts3_musicbot/services/Spotify.kt#L79) and it works pretty well.

**Comment by Rkubinski** [comment]
@Bettehem that's what I'm leaning towards, will probably get the song link and call the API to get the track info. Thanks!

**Comment by hrkfdn** [comment]
There are various libraries wrapping the Spotify Web API: https://developer.spotify.com/documentation/web-api/libraries/#libraries

ncspot by itself is already a ncurses frontend, so there are no plans to implement an `stdout`/machine-readable interface.

Good luck!
