### ISSUE TITLE
Keep getting xcb_connection_has_error returned true

### ISSUE THREAD

**Issue by blackspoof32** [hrkfdn/ncspot#360]
So after updating and upgrading my system (Manjaro 5.19.16-1) ncspot stopped working, I can login fine but whenever I try to play a song it crashes and loops the console saying "xcb_connection_has_error returned true: Protocol not specified" over and over.
If I run ncspot using sudo, I get an additional error saying "Failed to create secure directory (/run/user/0/snap.ncspot/pulse) No such file or directory.

Any ideas? Thanks in advance!

**Comment by hrkfdn** [comment]
It's trying to connect to PulseAudio. Is PulseAudio installed? It seems that you are using the snap package. As I don't maintain it I don't think I can help you that much. What you could try is to build ncspot from cargo.

**Comment by hrkfdn** [comment]
This can't be fixed within ncspot. It's either the PulseAudio lib or the librespot PulseAudio backend. A workaround is to prevent stderr logging, as described in #472. Alternatively, you could use the PortAudio or ALSA backends.
