### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by trululu96** [hrkfdn/ncspot#361]
Could not compile in a fresh install of ubuntu (all dependencies are checked). The output is as follows: 

error[E0658]: use of unstable library feature 'str_strip': newly added
   --> /home/arrakis/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.2.6/src/main.rs:313:20
    |
313 |             if cmd.strip_prefix('/').is_some() {
    |                    ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `ncspot v0.2.6`, intermediate artifacts can be found at `/tmp/cargo-instally5CZli`

**Comment by hrkfdn** [comment]
Please check the link in the output, you'll need a more recent Rust version.
