### ISSUE TITLE
Load credentials using shell command

### ISSUE THREAD

**Issue by jackkinsey** [hrkfdn/ncspot#374]
An option to read username/password/both from a shell command would be a nice upgrade from storing passwords in plaintext. See e.g. [aerc](https://jlk.fjfi.cvut.cz/arch/manpages/man/aerc-config.5.en) for examples of this behavior. (I might get around to implementing this myself, but I figured I might as well make an issue for it.)

**Comment by hrkfdn** [comment]
Hi, credentials are not stored anymore, only the Spotify token is retained. So I'm closing this for now.
