### ISSUE TITLE
Function to clear a search using ESC

### ISSUE THREAD

**Issue by JojiiOfficial** [hrkfdn/ncspot#384]
As the title says. Pressing `ESC` should clear the text inside the search bar, at least that is what I think would be most intuitive.

**Comment by windowswithoutborders** [comment]
it would be nice to have the usual bash shortcuts available too. ctrl +a,e to go to the beginning/end of a text insert box (search, command field, any others I may be overlooking...), ctrl + u to clear the box, ctrl +w to clear a word, alt+d to clear a word forward, etc....
