### ISSUE TITLE
Issues with syn

### ISSUE THREAD

**Issue by TheCatster** [hrkfdn/ncspot#385]
Just experienced this same issue with nushell, and they solved the problem by pinning the 'syn' version. Apparently an incompatible version went out. Here is the error, specifically:
```error[E0432]: unresolved import 'syn::export'
  --> /home/danya/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.0/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find 'export' in 'syn'

**Comment by hrkfdn** [comment]
@TheCatster Does the committed fix work for you?

**Comment by TheCatster** [comment]
Building from source works fine, but the version in crates is still not building correctly.

**Comment by hrkfdn** [comment]
Thanks for the feedback. I have published a new release.

**Comment by TheCatster** [comment]
Awesome, thank you!
