### ISSUE TITLE
Console display shows strings

### ISSUE THREAD

**Issue by randomlylelo** [hrkfdn/ncspot#408]
I'm not too sure if this a bug because of my terminal or because of ncspot so I apologise if this isn't a ncspot problem.

So I'm running on Arch Linux, KDE Plasma 5.20.5.
My console is the default for KDE: `Konsole`
I tried running ncspot in both bash & zsh so im guessing shell is not the problem. 

I installed ncspot through the aur using pikaur, `pikaur -S ncspot` no errors during installation.

When I first ran `ncspot`, the login screen was messed up but I ignored and managed to login.
The display is just messed up, instead of the lines & colors it has strings instead.

My current `ncspot`:
![image](https://user-images.githubusercontent.com/38267386/105912296-3ecc3d80-5ff9-11eb-9db3-86b35a008273.png)
I drew circles where the song length is supposed to be and where the progress bar is supposed to be,

Thank you so much! I have no clue why this is happening but it's just a minor visual bug and ncspot works just fine.
Let me know if you guys want any console output/anything to help me debug this!

I also wasn't able to find other issues that had the same problem as mine and Google didn't help to much...

**Comment by rgerardi** [comment]
I had a similar issue with the fonts. Also running Arch Linux but using Terminator instead. I resolved the issue by setting this option in the configuration file:
```
use_nerdfont=false
```

**Comment by randomlylelo** [comment]
> I had a similar issue with the fonts. Also running Arch Linux but using Terminator instead. I resolved the issue by setting this option in the configuration file:
> 
> ```
> use_nerdfont=false
> ```

I tried that and restarted my computer, but it still doesn't work. Maybe I have to install the nerd font and use it instead?
If so could you guys send me the font so I can download and manually install (I googled nerd font and there are multiple ones)?

My config file opened in vscode: 
![image](https://user-images.githubusercontent.com/38267386/106042643-55cb6800-60ab-11eb-835d-effc198e7e74.png)

**Comment by hrkfdn** [comment]
Is your environment set to UTF-8? Looks a lot like this: https://github.com/hrkfdn/ncspot/issues/107

**Comment by randomlylelo** [comment]
#107 solution works. All I had to do was update env variable.
I did it through my `~/.zshrc` file by adding this line: `export LANG='en_US.UTF-8'`

**Comment by codabrink** [comment]
Unfortunately I'm also experiencing this with a fresh install of Manjaro Gnome in Guake. Tried all the possible solutions here and none of them have worked. Not sure what's happening.
I installed from source using the nightly toolchain.

**Comment by codabrink** [comment]
Okay, I figured it out. For some reason Manjaro doesn't automatically configure your locale on the most recent release.

Uncomment `en_US.UTF-8 UTF-8` in `/etc/locale.gen`, run `sudo locale-gen`, and then restart. Problem solved.
