### ISSUE TITLE
Default playlist sort

### ISSUE THREAD

**Issue by avant-gronche** [hrkfdn/ncspot#411]
I have a few playlists with tons of songs and I'm constantly adding new ones, as well as usually playing these latests songs first.

The way it is now, I have to either scroll through 3k songs or use 'sort added d', both of those needing to be done every single time I open the playlist, which is tedious.

Reading the documentation I haven't found a way to select a default playlist sort in the config file, could one be added eventually?

**Comment by matgd** [comment]
That's the functionality I'd like to see too.

**Comment by hrkfdn** [comment]
Yeah, ncspot should probably keep track of the sorting modes set for playlists.

**Comment by hrkfdn** [comment]
Will be implemented via #436
