### ISSUE TITLE
have command line search switch to search screen

### ISSUE THREAD

**Issue by windowswithoutborders** [hrkfdn/ncspot#413]
It's kind of disorienting searching from the command line within queue or library and having to backspace all the way back to the beginning while the search screen is completely unused. Essentially makes the feature useless for me since I'll always want to start a search specifically from the search screen to avoid that.

**Comment by hrkfdn** [comment]
Unless I misunderstood, this should be fixed in `master`.

**Comment by windowswithoutborders** [comment]
@hrkfdn
I might've not explained it clearly enough. when you are already in ncspot and start a search through `:search`, this should behave as if you pressed F2 and did a search. Currently, it does not. A search through `:search` will overtake the current screen, but I think a more sensible behavior would be to switch you to the search screen for the search. I'm on the latest commit.

**Comment by hrkfdn** [comment]
Ah, now I get it. So the search results layer is displayed in the current screen (e.g. queue) but it should switch to the search screen first, so it's pushed on the search screen view stack. Yes, that's a bug indeed. Thanks for clarifying!

**Comment by hrkfdn** [comment]
I just pushed a fix for this. Please let me know if this improves things.

**Comment by windowswithoutborders** [comment]
updated to the latest commit through the aur. Works perfect :). Thanks!
