### ISSUE TITLE
Trouble with Logging in via Facebook

### ISSUE THREAD

**Issue by adamshem** [hrkfdn/ncspot#420]
Hello,

I am trying to login using facebook, but it's not allowing me. Could someone please help?

![Screenshot_20210204_005459](https://user-images.githubusercontent.com/73026422/106820174-90249e80-6683-11eb-8e2c-13a6d302ee5b.png)

**Comment by medwards** [comment]
The GTK warnings look unrelated and probably something related to your local configuration. If you type the URL out by hand you probably get #310

**Comment by hrkfdn** [comment]
Duplicate of #310
