### ISSUE TITLE
Super Key in Keybinding Configuration?

### ISSUE THREAD

**Issue by mentalblock** [hrkfdn/ncspot#430]
I am trying to make a keybinding that uses the Super key modifier. Is this possible?

Without going into too much detail, I would like to configure `ncspot` to match my text editor as much as possible. Paging down is Ctrl-v, paging up is Super-v. I cannot "move up" in `ncspot` because it seems like I cannot bind with the Super key modifier. Thanks in advance for taking the time on this project.

**Comment by hrkfdn** [comment]
Hey there, looking at this it seems like the Super modifier is not accessible within cursive, which is the library ncspot uses for its UI: https://docs.rs/cursive/0.15.0/cursive/event/enum.Event.html#variants

I'm afraid it looks like it's not possible. I'm not even sure terminals/terminal emulators can use the Super key :thinking:

**Comment by mentalblock** [comment]
Terminal emulators supporting the Super key is definitely possible. I have key bindings that leverage Super in the terminal emulator I use, which is Alacritty.

https://github.com/alacritty/alacritty/blob/fc87aaa4b10b9a5949fa2eae9e33ef66949b70d3/alacritty.yml#L654

At any rate. Thanks for the research. Hope this feature will eventually arrive to the library.

**Comment by hrkfdn** [comment]
Well there must be some sorcery involved, because from what I know terminals don't know Super keys. If I run `showkey -a` in `gnome-terminal` and press `Super+i` or other combinations with Super that aren't taken by the system, `showkey` doesn't print any modifier.

Could be that it's mapped to `ESC` in Alacritty. You could check with `showkey -a` and see what it prints.

**Comment by mentalblock** [comment]
You are correct. There is no difference from Super-v compared to 'v' in my `showkey -a`. As someone who does not fully understand the terminal workings, thanks for the help on clarifying the issue. I can always map this key in my terminal application that will send a different code to ncspot.
