### ISSUE TITLE
Request: Resume queue on restart

### ISSUE THREAD

**Issue by lervag** [hrkfdn/ncspot#432]
It seems the currently playing queue is forgotten everytime ncspot is closed. It would be nice if it was possible to retain the queue when I close ncspot and to continue playing the same song (preferably from the same place) and the same queue when I restart ncspot.

**Comment by hrkfdn** [comment]
Thanks, this is a good idea. I'll implement it via #436

**Comment by lervag** [comment]
Great, and thanks for making and sharing this useful tool!
