### ISSUE TITLE
Idea: update terminal title with the playing track and state

### ISSUE THREAD

**Issue by crdx** [hrkfdn/ncspot#434]
What do you think about a feature to update the terminal title with the playing track and state on the appropriate event, so that it can be seen at-a-glance in the panel (if one uses one)?

**Comment by hrkfdn** [comment]
Hi, I would like to add this at some point, but currently it's not possible. See also: https://github.com/hrkfdn/ncspot/issues/73

**Comment by crdx** [comment]
Ah, that is a shame.

Also sorry for not checking more closely for an existing issue.
