### ISSUE TITLE
Persist runtime state

### ISSUE THREAD

**Issue by hrkfdn** [hrkfdn/ncspot#436]
Persist runtime state, e.g.

- [x] track queue
- [x] playback mode (shuffle, repeat, etc.)
- [x] volume
- [ ] sorting orders for playlist
- [x] add config values to override stored state for shuffle, repeat and volume

and reload it upon restart

**Comment by BachoSeven** [comment]
If I understand the code correctly, this removes the need for setting an initial state in the configuration.
However, would you consider making this configurable? i.e. to turn off the persistence state.

**Comment by hrkfdn** [comment]
Could you explain your use case a bit more? Is it just about setting the shuffle/repeat state on startup?

**Comment by BachoSeven** [comment]
I would like to have shuffle and repeat off at startup, even if I turned them on, and also reset the volume (this one is less important I guess) 

I don't mind keeping the queue, so I guess still having the initial state configuration options could be a solution, if possible.

**Comment by hrkfdn** [comment]
Sounds like a good compromise. I'll introduce some configuration values to set shuffle, repeat and volume at startup overriding the stored state. I think keeping the state from last usage is the default use case, but your use case is also very valid. That sound okay?

**Comment by BachoSeven** [comment]
That's perfect. I agree that it makes sense to default to the stored values and have the initial state override only if it is explicitly set.

**Comment by lervag** [comment]
Would it be possible to also remember the current screen? E.g., if I close `ncspot` while playing and also viewing a particular playlist, it would be nice to get back directly there to avoid the extra navigation.

**Comment by Qluxzz** [comment]
Tried out the latest update and while the queue is persisted, the current queue index is reset to the first track in the queue instead of what it was when you exited the program.

I think it should continue from the position in the queue it was when you exited the program.

**Comment by hrkfdn** [comment]
@Qluxzz @lervag I like those ideas, but they are a little more complex so I'd prefer to de-scope them for this issue. Could you open separate issues for them so they don't get lost?

**Comment by Qluxzz** [comment]
I have created an issue for persisting the queue index.

Another issue with persisting the queue as you have done led me to wonder, if a track would change info between sessions and a track with old info was loaded to the queue, what would happen?

Would it not be better to just store an array of track IDs as the queue and then load all info for the tracks when starting the application?

I tried this myself, but I only managed to load full tracks, which with a larger queue was not sustainable and led me to get timeouts from Spotify.

**Comment by hrkfdn** [comment]
@Qluxzz Thanks!

Yeah, the current approach is quite primitive. I don't expect the track info to change between sessions. I'd assume at worst it could become unavailable in which case playback simply wouldn't work and the next track is queued (haven't verified this).

This API is the best that could be used, but it only accepts at most 50 track IDs: https://developer.spotify.com/documentation/web-api/reference/#category-tracks -- I'm guessing you used that one. I agree that it would be rather annoying to delay startup with larger queues.

As queues have a rather short lifespan I think the current approach is good enough as a start.

**Comment by lervag** [comment]
> @Qluxzz @lervag I like those ideas, but they are a little more complex so I'd prefer to de-scope them for this issue. Could you open separate issues for them so they don't get lost?

Definitely; done (#449).

**Comment by skitoxe** [comment]
looking forward alot to the persistent sort order feature. Keep up the great work! Loving it.

**Comment by BachoSeven** [comment]
If I close the terminal which spawned `ncspot`, the queue is not saved to `userstate.toml`. Do you think there could be a workaround around this or is it to be considered off-scope?

**Comment by hrkfdn** [comment]
I guess ncspot could save the userstate when it receives `SIGHUP`, it's worth a try.

**Comment by BachoSeven** [comment]
Thanks for considering it! 

Perhaps, this could also temporarily useful for the issue where `ncspot` crashes following a resume from suspend(i.e. #422, #425, and this [new comment](https://github.com/hrkfdn/ncspot/issues/192#issuecomment-795741328) from a solved issue). What I mean is, in such cases if one were to force closing `ncspot` because it is unresponsive, perhaps it could still catch `SIGHUP` as you suggested, thus saving an otherwise lost queue.

**Comment by chaseadam** [comment]
I presume the state and playlist does not change very often (one per song play or user action). Is there a reason to avoid writing when (a subset of) these state changes happen?

I run into similar issues (lost playlist) on crash a few times (which I recognize hopefully the never happen).
