### ISSUE TITLE
the shortcut does not work go to the next song

### ISSUE THREAD

**Issue by liltingle** [hrkfdn/ncspot#452]

**Comment by hrkfdn** [comment]
Could you elaborate what you mean by "go to the next song"?

**Comment by liltingle** [comment]
On the web it tells you that you can pass the song with "<and> play the previous or next track" I press the arrows on the keyboard and the song is not changed

**Comment by liltingle** [comment]
Excuse me, I saw how it's done. ": next" .. xD sorry
