### ISSUE TITLE
"Albums" tab does not populate as expected in the Library view

### ISSUE THREAD

**Issue by NaabSunde** [hrkfdn/ncspot#461]
**Describe the bug**
I have +1000 songs in my Tracks, but for some reason Albums tab only shows around 15 albums.

**To Reproduce**
1. Have songs in your Spotify Liked playlist
2. Browse to Albums tab in ncspot
3. Find only few albums

**Expected behavior**
If I've understood correctly, the Albums tab should contain every album from which you have saved music to the Liked playlist.

**Screenshots**
Tracks:
![image](https://user-images.githubusercontent.com/9089790/110472135-a8a23180-80e5-11eb-9a80-4aaa5395e9b0.png)
Albums:
![image](https://user-images.githubusercontent.com/9089790/110472172-b5bf2080-80e5-11eb-8668-af177899665c.png)

**System (please complete the following information):**
 - OS: Fedora 33
 - Terminal: GNOME Terminal
 - Version: at least 0.4.0 and 0.5.0
 - Installed from: cargo

**Backtrace/Debug log**
Instructions unclear, I'm not familiar on how to debug issues in Rust. Help is required if a backtrace is needed.

**Comment by hrkfdn** [comment]
Closing as discussed on Gitter. The current behavior matches that of the official clients. The album tab only contains saved/liked albums and is not influenced by single liked tracks.
