### ISSUE TITLE
Add a playlist using a URL

### ISSUE THREAD

**Issue by nloyola** [hrkfdn/ncspot#471]
**Is your feature request related to a problem? Please describe.**
Be able to add playlist using a URL.

**Describe the solution you'd like**
I would like to be able to add a playlist to my account by using a URL. For example Reddit has a SpotifyPlaylists subreddit where people share playlists (https://www.reddit.com/r/SpotifyPlaylists/). I would like to be able to add one of these playlists to my account.

**Describe alternatives you've considered**
The way I do it now is to log into Spotify's web client and add the playlist from there.

**Additional context**
None.

**Comment by hrkfdn** [comment]
You should be able to enter that URL in the search view. You can then subscribe to that list using `s`.

**Comment by nloyola** [comment]
It works.

Thank you!
