### ISSUE TITLE
Playlist stats: number of songs and duration

### ISSUE THREAD

**Issue by nloyola** [hrkfdn/ncspot#475]
**Is your feature request related to a problem? Please describe.**
No. It's not related to a problem.

**Describe the solution you'd like**
The Spotify client shows how many songs are in a playlist and the duration (e.g. in hours) of the playlist. Is it possible for **ncspot** to show this information as well?

Could this also be done for the queued up songs as well?

**Describe alternatives you've considered**
For a playlist, I have to look up this information in Spotify's web client for now.

**Additional context**
None.

**Comment by Bettehem** [comment]
Yeah I think this is possible. [Spotify API](https://developer.spotify.com/documentation/web-api/reference/#object-trackobject) exposes the `duration_ms` variable for each (Simplified)TrackObject so a playlist's length could be calculated by adding each track's duration together.

**Comment by hrkfdn** [comment]
This is now implemented.

**Comment by nloyola** [comment]
Thank you!
