### ISSUE TITLE
Opening artists with huge discographies takes a long time

### ISSUE THREAD

**Issue by nikolaus-stahlberg** [hrkfdn/ncspot#477]
Opening artists with huge discographies takes a long time.
This is especially noticable when navigating to classical artists, as those will be linked to up to hundereds of albums a year.

Without having studied the code at all, I'd suspect that meta information for artists is queried in full before building the artist page. This is easily fast enough for contemporary music but takes a substanitial amount of time for the big boys of the bygone eras.

##### Steps to reproduce the behavior:
- Navigate to 'Tchaikovsky'
- Open the artists page by hitting o
- Wait for a long time to proceed

This is probably not of very high concern for now as the program merely hangs for a while but keeps function wonderfully after the artists pages were built.
This is therefore not necessarily a 'breaking-bug' but rather a small inconveniece..

**Comment by gbaranski** [comment]
Playing `Eminem` is not even possible in my case, after pressing ENTER nothing happens.

**Comment by hrkfdn** [comment]
Sounds like the album tab in the artist view should be paginated as well. The download is also taking place in the UI thread.
