### ISSUE TITLE
Support for playlist folders

### ISSUE THREAD

**Issue by LucaDiBona** [hrkfdn/ncspot#480]
I have a lot playlists, sorted into folders. On the official Spotify apps these folders mean that it is significantly easier to find which playlist I want. However, on ncspot, all playlists are displayed, no folders

**Describe the solution you'd like**
Folders should show, and when Return is pressed on a folder, it should be opened, either intended in the main playlist view or in a separate view.

**Comment by Bettehem** [comment]
This is currently not possible. See [here](https://developer.spotify.com/documentation/general/guides/working-with-playlists/#folders).

**Comment by hrkfdn** [comment]
Can't be done unfortunately, as @Bettehem explained. Folders are not sent by the Spotify Web API. Closing this.
