### ISSUE TITLE
Allow command line mode key to be remappable

### ISSUE THREAD

**Issue by smithbm2316** [hrkfdn/ncspot#487]
**Is your feature request related to a problem? Please describe.**
No, it is simply a suggestion I would love to see implemented!

**Describe the solution you'd like**
I'd love if there was a way for me to remap the **command mode** keybinding. In my case, I'd like to remap it to **;** instead of **:**, as that's a remap I have in my Neovim config and it's muscle memory for me now.

**Describe alternatives you've considered**
If this isn't a very easy thing to implement, then I'd rather not bug you with a niche request. I just personally have the Vim command mode rebound to my semi-colon key to save my pinky the extra work (since i run a lot of command-mode commands in my neovim usage), and my habit is to reach for that, not a regular colon. I'm thoroughly enjoying this project and can't thank you enough for your hard work on it! :smiley: 

**Sidenote**
Have you considered creating an Open Collective or GitHub Sponsor account for this project? Or if not, is there a place I can send a tip as a thank you for such a great project? Even if it's small, I always like supporting open-source software projects that I love and use heavily with either financial support or by contributing code, but I unfortunately do not know any amount of Rust to help contribute to this project (so I'd love to support in other ways if I can :smiley:).

**Comment by hrkfdn** [comment]
I finally got around to implement this.

Thank you for the kind words, I appreciate it. I have set up GitHub Sponsors for my account. Feel free to send a tip if you like, but don't feel obligated :)
