### ISSUE TITLE
Can't get back to the search bar

### ISSUE THREAD

**Issue by sajattack** [hrkfdn/ncspot#49]
Previously, after a search, I was able to get back to the search text input field by scrolling up or clicking on it, in the latest version (cb753ea073b561cc418af9ca353518674899d510), it doesn't seem to be working. It stops at the top of the search results, and doesn't get back into the text field. The only thing that works now is `:search Rust Never Sleeps`

**Comment by hrkfdn** [comment]
Yeah, that got lost due to some UI restructuring. We should probably
reimplement it. For now, you should be able to use TAB to switch between
the input field and results.
