### ISSUE TITLE
Earphones recognition and playback

### ISSUE THREAD

**Issue by aaandri98** [hrkfdn/ncspot#494]
**Is your feature request related to a problem? Please describe.**
Can't connect ncspot to my AirPods - the terminal does not recognize the fact that I want to reproduce music over my earphones.

**Describe the solution you'd like**
Understand which playback tool am I using, and directly stream music to it.

**Comment by hrkfdn** [comment]
Does this help? https://github.com/hrkfdn/ncspot/issues/484#issuecomment-816930980

**Comment by aaandri98** [comment]
https://github.com/hrkfdn/ncspot/issues/484#issuecomment-816930980 solved everything!
