### ISSUE TITLE
casting to other devices

### ISSUE THREAD

**Issue by alembiq** [hrkfdn/ncspot#496]
It would be very nice to be able to use other devices logged under my account as the devices to listen on.
Spotify is allowing me to "listen on remote device"; for example my router (which doesn't have keyboard/monitor etc but has speakers).

**Comment by icalvin102** [comment]
This has already been discussed in #101

**Comment by alembiq** [comment]
i see, although it's more than 18 months later, maybe the opinion about it changed ;) 
and i guess the inability to "send" sounds to device running spot is the same issue

**Comment by hrkfdn** [comment]
Hey @alembiq, unfortunately it's still out of scope. It would require a rewrite of the entire player logic. Sorry, closing this.
