### ISSUE TITLE
Setting An Invalid Color Name Causes Main Thread To Panic

### ISSUE THREAD

**Issue by Rayqan** [hrkfdn/ncspot#498]
Simply setting any value under the '[theme]' key to an invalid color name causes: 
`thread 'main' panicked at 'Failed to parse color "grey"', src/theme.rs:25:26`. 
As a side note are the valid color names documented anywhere?

**Comment by hrkfdn** [comment]
I'm assuming only these base colors work by string: https://docs.rs/cursive/0.16.3/cursive/theme/enum.BaseColor.html

If you want something more specific, it's better to go by hex value.
