### ISSUE TITLE
ncspot's saved state is bugged

### ISSUE THREAD

**Issue by epixinvites** [hrkfdn/ncspot#503]
```
[saved_state]
volume = 100
repeat = "playlist"
shuffle = true

[theme]
background = "black"
primary = "#F8F8F2"
secondary = "light black"
title = "#bd93f9"
playing = "#bd93f9"
playing_selected = "#D0B3FA"
playing_bg = "black"
highlight = "#f8f8f2"
highlight_bg = "#44475a"
error = "#f8f8f2"
error_bg = "#ff5555"
statusbar = "black"
statusbar_progress = "#bd93f9"
statusbar_bg = "#bd93f9"
cmdline = "#f8f8f2"
cmdline_bg = "black"
search_match = "#ff79c6"
```
Here is my config, and everytime when I open ncspot, it automatically goes to the state that it was like a week ago. Same song, same location, although I did play other songs in that period. I remember clearly that last night before I slept, I turned ncspot off and it was an entirely different song. The next morning I wake up, turn on ncspot, and its back to the same song i played a week ago.

**Comment by hrkfdn** [comment]
How are you closing ncspot? If it's terminated abruptly, e.g. by closing the terminal window instead of pressing `q`, it won't update the state.

FYI: `saved_state` is gone

**Comment by epixinvites** [comment]
I always close ncspot with `q`... when did `saved-state` disappear???

**Comment by epixinvites** [comment]
after I cleared the [saved_state] the problem is fixed. Thanks
