### ISSUE TITLE
Recreating config dir

### ISSUE THREAD

**Issue by im-n1** [hrkfdn/ncspot#51]
Currently on the master (`83a394790`):

```
thread 'main' panicked at 'can't create config folder: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by hrkfdn** [comment]
The config path has changed: https://github.com/hrkfdn/ncspot/commit/3892ac07d0073c4a0313416660b1a7ce171fa7fc

You need to move the config to the new path. Right now it's trying to create a folder at the current config location.
