### ISSUE TITLE
Macbook touchbar play/pause does not work

### ISSUE THREAD

**Issue by stanbar** [hrkfdn/ncspot#519]
**Describe the bug**
Macbook touchbar play/pause does not work. MacBook Pro (15-inch, 2016) Big Sour 11.2.3 (20D91)

**To Reproduce**
1. Start ncspot
2. Play music 
3. Try to pause it using touchbar play/pause button
4. Nothing happens

**Expected behavior**
Music should be paused.

**System (please complete the following information):**
 - OS: MacBook Pro (15-inch, 2016) Big Sour 11.2.3 (20D91)
 - Terminal: Alacritty
 - Version: 0.6.0
 - Installed from: brew

**Comment by hrkfdn** [comment]
Hey, did they work before or why is this marked as a bug?

**Comment by stanbar** [comment]
I don't know if it worked before. But on my Linux machine, with the play/pause functional key, it works.

**Comment by jpochyla** [comment]
FWIW there's a new effort to make a multi-platform interface for this, and MPRIS is missing: https://github.com/Sinono3/souvlaki

**Comment by hrkfdn** [comment]
Duplicate of #703

**Comment by gouegd** [comment]
See also another solution for macos via a companion app: https://github.com/hrkfdn/ncspot/issues/703#issuecomment-4691783320
