### ISSUE TITLE
Highly distorted audio when audio normalization is true

### ISSUE THREAD

**Issue by avant-gronche** [hrkfdn/ncspot#522]
**Describe the bug**
I recently migrated from pulseaudio to pipewire and since then, audio in ncspot sounds very loud and distorted, even when in-app volume is set to 0%.
EDIT: Seems like the problem involves audio normalization and an update to librespot, as indicated on comments below.

**To Reproduce**
1. Uninstall pulseaudio
2. Install pipewire and pipewire-pulse
3. Open ncspot and play any song

**Expected behavior**
Supposedly it shouldn't sound different than if played with pulseaudio.

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Termite
 - Version: 0.7.0-1
 - Installed from: AUR

**Comment by arielcrivas** [comment]
I can confirm the same issue with Pulseaudio and ncspot 0.7.0
Disabling volume normalisation (volnorm = false) in config file or downgrading to ncspot 0.6.0 solves this

**Comment by rbuch** [comment]
I was having the same issue with 0.7.0; changing the `normalisation_method` used in `librespot` also fixes this for me:

```
diff --git a/src/spotify.rs b/src/spotify.rs
index 559d666..d02c723 100644
--- a/src/spotify.rs
+++ b/src/spotify.rs
@@ -190,6 +190,7 @@ impl Spotify {
             bitrate: bitrate.unwrap_or(Bitrate::Bitrate320),
             normalisation: cfg.values().volnorm.unwrap_or(false),
             normalisation_pregain: cfg.values().volnorm_pregain.unwrap_or(0.0),
+            normalisation_method: librespot_playback::config::NormalisationMethod::Basic,
             ..Default::default()
         };
```

So it seems the issue is caused by the new dynamic normalisation used by default in `librespot`, which was added in https://github.com/librespot-org/librespot/pull/660.

**Comment by avant-gronche** [comment]
Thanks guys.
I haven't got around trying to disable audio normalization but I updated the main post to better reflect the issue.

**Comment by roderickvd** [comment]
I authored the new normalisation `librespot`. Please provide your input on https://github.com/librespot-org/librespot/issues/745 and continue there.
