### ISSUE TITLE
Feature Request: Packages for Alpine Linux and PostmarketOS

### ISSUE THREAD

**Issue by baconicsynergy** [hrkfdn/ncspot#532]
Hello my friends! I would absolutely love to see packages for Alpine Linux and postmarketOS, as they have become very relevant and widely used, and postmarketOS has become the default operating system for the Sxmo mobile desktop environment (https://sr.ht/~mil/Sxmo/).

I am currently attempting to compile this from source on postmarketOS but am having trouble finding build dependencies.

**Comment by hrkfdn** [comment]
Hey! You can install ncspot with `cargo install ncspot`. Unfortunately I can't maintain ports/packaging for all the various distros, but if someone is interested in helping out, I'll gladly merge a PR. Closing this until then.
