### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by epixinvites** [hrkfdn/ncspot#533]
this crash just came out of nowhere and I literally have no idea how
![image](https://user-images.githubusercontent.com/54717060/118944323-0b863380-b987-11eb-9d36-388605802475.png)

**Comment by mtshrmn** [comment]
I have a feeling this is the same error as #422, but without any information I'm just guessing.

**Comment by hrkfdn** [comment]
Please provide a debug log and stderr output with `RUST_BACKTRACE` set, e.g. like here: https://github.com/hrkfdn/ncspot#usage

**Comment by epixinvites** [comment]
No but the thing is I cant reproduce it, it just crashed randomly.

**Comment by hrkfdn** [comment]
Closing this due to lack of information, but probably related to #536, so I'd refer to that one instead. Please reopen if you think this is a different bug.
