### ISSUE TITLE
panic after suspend/resume

### ISSUE THREAD

**Issue by eprst** [hrkfdn/ncspot#536]
**Describe the bug**
I had ncspot running (but paused) when I suspended my box. Unpaused it after resuming, it finished playing current track and panicked when switching to the next one.
```
'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/konstantin/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.7.1/src/spotify_worker.rs:151:66
```

will run with `RUST_BACKTRACE=1` and update if it happens again.

**To Reproduce**
1. load some playlist
2. play
3. pause
4. suspend, eg as root: `echo mem > /sys/power/state`
5. resume from sleep
6. unpause ncspot
7. wait for it to switch to another track
8. observe the panic

**System (please complete the following information):**
 - OS: Linux
 - Terminal: Konsole
 - Version: 0.7.1
 - Installed from: cargo

**Backtrace/Debug log**
will update

**Comment by hrkfdn** [comment]
I have pushed a change to `master` that should hopefully help with this. Would be great if you can run `master` and report back if it makes a difference.

**Comment by eprst** [comment]
Hi. Not reproducible on `master`, though I'm getting this after a bit of playback, once buffer is exhausted I guess:

![image](https://user-images.githubusercontent.com/661098/119391796-a894e500-bc83-11eb-9655-8b6f4114f8c9.png)

and playback is stopped until I manually restart some track. UI gets somewhat broken by the stderr output.

thanks

**Comment by hrkfdn** [comment]
Ah, that means it actually reconnected when the session expired due to suspend, so that's good. I'll move the printing of that message so it's only done once. 

I'm closing this one then. Thanks for the reports. It doesn't pick up the previously played track yet as that would be a little more complicated, but at least the crash is fixed.
