### ISSUE TITLE
The nscpot app does not play any sound in Ubuntu 21.04 when using Wayland

### ISSUE THREAD

**Issue by rbok78** [hrkfdn/ncspot#547]
**Describe the bug**
There is no sound when trying to play any song from any playlist. The app's progress bar shows that a song starts playing but after several seconds the app automatically moves to another song inside a playlist. Same behavior repeats for all songs in a playlist.

**To Reproduce**
1. Install ncspot by running sudo snap install ncspot
2. Login to Spotify using a username and a password
3. Navigate to any of the Daily Playlists
4. Click on any song inside the chosen playlist

**Expected behavior**
I can listen to the song being played.

**Screenshots**
-

**System (please complete the following information):**
 - OS: Ubuntu 21.04 with Wayland
 - Terminal: GNOME Terminal
 - Version: 0.7.3
 - Installed from: Snap

**Backtrace/Debug log**
Tried to run RUST_BACKTRACE=full ncspot -d debug.log, but repeatedly got the error
thread 'main' panicked at 'can't setup logging: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:128:33

**Additional context**
I found the following error in syslog when starting ncspot
kernel: [ 3104.027763] audit: type=1400 audit(1623675514.137:102): apparmor="DENIED" operation="open" profile="snap.ncspot.ncspot" name="/proc/5684/mountinfo" pid=5684 comm="ncspot" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000

**Comment by hrkfdn** [comment]
Looks like a permission issue? This is most likely not a bug, but a problem with the Snap package/sandboxing. Not much I can do here, maybe contact the Snap package maintainer?

**Comment by rbok78** [comment]
I see. I did not know about the Snap packages being maintained by someone else. I will try to find out more about how the process of creating a Snap package work, and who maintains the ncspot package.
