### ISSUE TITLE
Track Details View

### ISSUE THREAD

**Issue by sajattack** [hrkfdn/ncspot#55]
It would be nice to be able to get some info on the currently playing track such as what album it's from, what year it was released, etc.

**Comment by hrkfdn** [comment]
Hey! What did you have in mind on how/where you think this could be displayed?

**Comment by sajattack** [comment]
Another Fn key

**Comment by im-n1** [comment]
Maybe we can add something like "detail page" similar to a page under "o" key on an artist for example. We can display there all the info about song + some menu like "Add to playlist" or just "Save". I guess the page could be pushed forward as time advances but this can be good start.

**Comment by hrkfdn** [comment]
TODO: Show information of currently playing/selected item in context menu (o|Shift-o)

**Comment by hrkfdn** [comment]
This is in an acceptable state at the moment, I'd say.
