### ISSUE TITLE
Create a Windows binary for package managers

### ISSUE THREAD

**Issue by rashil2000** [hrkfdn/ncspot#555]
**Is your feature request related to a problem? Please describe.**
Only linux and macos binaries are present in the Releases page.

**Describe the solution you'd like**
Add a Windows binary (through CD, as mentioned in #546) so that a manifest can be prepared for Scoop or Chocolatey package managers.

**Describe alternatives you've considered**
I don't think there's an alternative 😜

**Additional context**
None

**Comment by rashil2000** [comment]
Hey @hrkfdn!

I saw that there was a release recently, is there no plan for this?
It'd be really helpful for package managers, and is really easy to set up in the workflows (pretty much similar to macOS's).

**Comment by hrkfdn** [comment]
I don't really use ncspot on Windows and I didn't have the time yet to work on this, but I'll gladly take a PR.
