### ISSUE TITLE
ncspot window looking corrupted/wrong

### ISSUE THREAD

**Issue by AtlasC0R3** [hrkfdn/ncspot#556]
**Describe the bug**
So, normally ncspot looks like normal ncurses, clean and straightforward. However, my terminal (Konsole) did not like that.

**To Reproduce**
1. Open `ncspot`

**Expected behavior**
I expected it to not look corrupted-ish, and I know how it's supposed to look like, I had it installed on Debian and it looked just fine, but with Arch Linux, everything looks.. wrong.

**Screenshots**
![image](https://user-images.githubusercontent.com/39468657/122805184-c9f2ec00-d296-11eb-9dbf-9d0d5309da67.png)
*i dont think thats how its supposed to look like*

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Konsole
 - Version: 0.7.3
 - Installed from: cargo *(AUR too, both `ncspot` and `ncspot-git` looked like this)*

**Backtrace/Debug log**
stderr.log
```
error: could not find `Cargo.toml` in `/home/atlas` or any parent directory
```

To debug crashes a backtrace is very helpful. Make sure you run a debug build of ncspot, e.g. by running the command mentioned in the link above.
*(I don't quite think this is going to be very useful...)*

**Additional context**
It's most likely an issue with Konsole. Or Arch.

**Comment by TheSemicolons** [comment]
Same issue on OpenBSD 6.9. The font probably doesn't support some characters being used, but I have no idea what font would.

![2021-06-22-102128_683x409_scrot](https://user-images.githubusercontent.com/20374463/122963696-5fe05280-d33b-11eb-9ba4-984a76065bf4.png)

**Comment by AtlasC0R3** [comment]
It doesn't seem like a font-related issue, I tried a bunch of them and they did the same garbled mess thing.
![Peek 2021-06-22 12-48](https://user-images.githubusercontent.com/39468657/122967220-3d106700-d358-11eb-91fe-5812e5f7a3b3.gif)

It may be an encoding issue though. Tried XTerm, UXTerm, Yakuake and the tty shell (<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>F\*</kbd>) and they all did the same thing.

**Comment by hrkfdn** [comment]
Hmm, would you happen to know if this also occurs with versions <0.7.x? I wonder if it's because of https://github.com/hrkfdn/ncspot/commit/b80e0180794e361dff0defb24e852bbd2b193698

**Comment by TheSemicolons** [comment]
localhost$ pkg_info ncspot
Information for inst:ncspot-0.5.0

Comment:
ncurses Spotify client

Description:
Cross-platform ncurses Spotify client written in Rust with
a low resource footprint. The UI is heavily inspired by
ncurses MPD clients, such as ncmpc.

Maintainer: Henrik Friedrichsen <henrik@diff.cc>

WWW: https://github.com/hrkfdn/ncspot

**Comment by AtlasC0R3** [comment]
Tried launching ncspot [0.5.0](https://github.com/hrkfdn/ncspot/releases/tag/v0.5.0) and [0.4.0](https://github.com/hrkfdn/ncspot/releases/tag/v0.4.0) by launching their \*.tar.gz executables, they look equally corrupted.
Here's a screenshot of 0.4.0:
![image](https://user-images.githubusercontent.com/39468657/123014826-0d338480-d395-11eb-96c9-b5f46c15a0a9.png)

Oh by the way, the screenshots I sent previously are all running on the latest AUR version, which I believe is the latest available.

**Comment by hrkfdn** [comment]
Then the change I mentioned is not related. What locale are you using? I use `LANG=en_US.UTF-8` and have no problems on OpenBSD with rxvt-unicode or GNOME-Terminal on Debian.

**Comment by TheSemicolons** [comment]
```
localhost$ echo $TERM
xterm
localhost$ echo $LANG

localhost$
```

Looks like LANG isn't set by default in OpenBSD. When I set it with `export LANG="en_US.UTF-8"` and then run `ncspot` it works.

**Comment by AtlasC0R3** [comment]
My `TERM` variable was also set to xterm, although I had xterm-256. Changing the lang variable didn't do anything, although it is already set to en_CA.UTF-8 by default.

**Comment by TheSemicolons** [comment]
The API for Spotify was having issues yesterday. I confirmed today with ncspot-0.5.0 on OpenBSD using `export LANG="en_US.UTF-8" ` then running `ncspot` works in both `xterm` and `st-256color`.

![2021-06-24-130837_564x364_scrot](https://user-images.githubusercontent.com/20374463/123319182-f308bc00-d4e4-11eb-9af1-48aba113c48a.png)

**Comment by ant0n-anon** [comment]
just did a fresh arch install and i'm having this issue. didn't have it on kde neon or manjaro. does look to be something with the LANG. once i set that i'll be back to let you  all know if that fixed it. i'm having trouble figuring that out though, lol.

**Comment by ant0n-anon** [comment]
yeah, it was language issues. if you run: `locale` and see that it's showing "C" instead of your locale, just start following the crumbs or message me. once you get it to show your locale, it works perfect. :)

**Comment by AtlasC0R3** [comment]
Good to know it's an Arch related issue. I don't think I set my Lang
variables properly either, I'll check that when I can. Thanks!

**Comment by Bettehem** [comment]
You should enable at least `en_US.UTF-8` as instructed in the Arch Linux [Installation guide](https://wiki.archlinux.org/title/Installation_guide#Localization).
If `en_US.UTF-8` isn't enabled apps can misbehave.

**Comment by ant0n-anon** [comment]
> Good to know it's an Arch related issue. I don't think I set my Lang variables properly either, I'll check that when I can. Thanks!

yes, it's from not setting the locale correctly. it wasn't too bad to fix. I think this issue can be closed. message me if you need links.

**Comment by AtlasC0R3** [comment]
Yep, confirmed. `export LC_ALL="en_CA.UTF-8"` fixed the app. Thanks a lot!
*Now I'll just need to figure out how to make LC_ALL default to that.*
