### ISSUE TITLE
Show indicator for followed playlists

### ISSUE THREAD

**Issue by im-n1** [hrkfdn/ncspot#56]
It would be really nice to see following playlists. In playlist page (F3) I see only playlists created by me. My humble suggestion is to create 2 tabs just like search page has.

* 1. tab: My playlists
* 2. tab: Following playlist

**Comment by hrkfdn** [comment]
Hmm, I can't really confirm this. My followed playlists show up fine in the playlist tab.

**Comment by im-n1** [comment]
Well..I'm sorry, you are right. I was blind when I checked playlist list :)
Anyway, what do you think of the tabs idea - split playlists to mine and following? Is is even possible?

**Comment by hrkfdn** [comment]
It is possible, but I don't know if it is very beneficial. In the official client, both playlist kinds are shown in the same list, although they have an indicator when they are followed playlists. Maybe that would be something we could add.

**Comment by im-n1** [comment]
The benefit is better ux. Maybe this app can be better than the official app (which is not the best app ever anyway :)
