### ISSUE TITLE
Select Artist modal can't interact with certain keys

### ISSUE THREAD

**Issue by mtshrmn** [hrkfdn/ncspot#560]
**Describe the bug** 
Select Artist modal can't interact with certain keys (`hjkl` and `backspace`)

**To Reproduce**
1. Open context menu for a song with multiple artists
2. Select "Show artist"

**Current behavior**
- When using `hjkl` to move up and down the listview highlight is focused.
- Pressing `backspace` doesn't dismiss the modal. 

**Expected behavior**
- Same behavior as if using the arrow keys
- `backspace` should dismiss the modal 

**Screenshots**
I hope this demonstrates the problem: 
https://asciinema.org/a/keLLki8LLWkFyKzyKu8bwOko0

**System (please complete the following information):**
 - OS: Arch Linux 5.12.14
 - Terminal: Alacritty
 - Version: [latest commit on the master branch ](https://github.com/hrkfdn/ncspot/commit/2f08330d5addf35043a939ee37cbed4a36457ef0)
 - Installed from: compiled locally

I don't see a reason to add a backtrace/log but I'll create one if needed.
Unfortunatly I have no time to create a PR to fix this so I'm creating this Issue instead.

**Comment by Bettehem** [comment]
Using `escape` in other context menus doesn't work either, you have to select the `Cancel` button by pressing the `TAB` key.
I was able to recreate the issue with `hjkl` though.

**Comment by mtshrmn** [comment]
You're right, `escape` is the wrong key. I meant `backspace`. Editing the issue.
