### ISSUE TITLE
Works great from rpi but when I SSH in from my Windows machine UI menus work fine but there is no sound.

### ISSUE THREAD

**Issue by WhiteTrashWeeb** [hrkfdn/ncspot#564]
I installed the program on my rpi4 and everything works great. I plan to use it headlessly and control it from my windows machine, but when I SSH in it doesnt work. I can launch the program, go through the menus, do everything as if I were on the pi, but when I play a song there is no sound. When I go back to the pi and do the same thing, the sound works again. SSH in from a different machine, same thing, no sound. It seems weird that there would be a permission I'd need to grant that would pertain ONLY to sound and nothing else. Any idea what's going on?

**Comment by Bettehem** [comment]
No, [SSH](https://en.wikipedia.org/wiki/Secure_Shell_Protocol) only gives you a shell. But you can configure your apps etc to do the networking via SSH so for example you could route your pulseaudio output over the network and use ssh for that but then you'd have to have some way of receiving the audio data on the client side. Good luck with that. I haven't used Windows in years so I can't help you any further.

**Comment by hrkfdn** [comment]
You probably don't have access to your PulseAudio session or there is no PulseAudio running, this is not really an ncspot problem but more of a SSH + PulseAudio issue. It's a common problem, maybe this helps: https://unix.stackexchange.com/questions/193208/program-run-in-ssh-accessing-pulseaudio-on-the-machine-where-it-runs

**Comment by whisperity** [comment]
Definitely unrelated to the project at hand.

I created [this script](http://github.com/whisperity/dotfiles/blob/d6bf664f1e457c95d098bf7644e0865315ac2703/bin/ssh-with-audio) from the answer steps in [SuperUser &ndash; Forwarding audio like X in SSH](http//superuser.com/a/311830), but this requires the client machine (where you're SSHing *away from*) to be POSIX-like. So... not Windows.

Your best bet *could* be WSL, perhaps. Or [this Windows port for PulseAudio](https://www.freedesktop.org/wiki/Software/PulseAudio/Ports/Windows/Support/) with [these steps](http://superuser.com/a/1450765). But it says **1.1** in the version, while the latest for *nix is **15.0**...

Maybe buying a USB sound card with a jack output and plugging it into your desktop's *Line In* port would be the easiest solution.
