### ISSUE TITLE
Hi, can you please add a Gentoo package or way to install ncscpot?

### ISSUE THREAD

**Issue by Lunatic1985** [hrkfdn/ncspot#567]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hrkfdn** [comment]
Hey! You can install ncspot with `cargo install ncspot`. Unfortunately I can't maintain ports/packaging for all the various distros, but if someone is interested in helping out, I'll gladly merge a PR. Closing this until then.
