### ISSUE TITLE
Just made a logo for ncspot

### ISSUE THREAD

**Issue by reorx** [hrkfdn/ncspot#578]
**Is your feature request related to a problem? Please describe.**
I'm a happy user of ncspot, and I want it to have a cool logo.

**Describe the solution you'd like**
I made a logo that mixes the VIs of Rust and Spotify for it.

**Additional context**
I'm trying to wrap ncspot as a standalone app for macOS.

![ncspot-logo-1](https://user-images.githubusercontent.com/405972/129918507-e3e97f0b-c447-47c4-b733-945a51eda7f4.png)

**Comment by mtshrmn** [comment]
I'm pretty sure thig logo is against the [spotify guidelines](https://developer.spotify.com/documentation/general/design-and-branding/)

**Comment by hrkfdn** [comment]
Hello reorx, I appreciate the effort, however I'm afraid that as stated by @mtshrmn this will violate the guidelines and I'd rather not risk that
