### ISSUE TITLE
Command line control

### ISSUE THREAD

**Issue by Avimitin** [hrkfdn/ncspot#585]
**Is your feature request related to a problem? Please describe.**
Ncspot's command now only supports read different configurations or print debug messages. It will be more convenient if the ncspot can use command line arguments to search songs or play and pause. With this feature, I can integrate ncspot with some bash scripts.

**Describe the solution you'd like**
Example:

```bash
ncspot query <Song Name>
ncspot <play/pause>
ncspot query --album <Album Name>
```

**Comment by reorx** [comment]
@mtshrmn it seems impossible to control ncspot through MPRIS on MacOS, since Mac doesn't support it. I'm wondering how Mac users could control ncspot in the command line.

**Comment by Bettehem** [comment]
> @mtshrmn it seems impossible to control ncspot through MPRIS on MacOS, since Mac doesn't support it. I'm wondering how Mac users could control ncspot in the command line.

Hi, I don't use macOS myself so I can't test how well this works, but I found something that may help.
You can install and run dbus fairly easily using something like [homebrew](https://brew.sh). Here are instructions on how to do it: https://github.com/zbentley/dbus-osx-examples#faq
You could then build and install something like [playerctl](https://github.com/altdesktop/playerctl#compile-from-source) to control the player using MPRIS. You can install the build requirements for playerctl using `brew` too.
