### ISSUE TITLE
Playing music directly from terminal command?

### ISSUE THREAD

**Issue by TheNomadicAspie** [hrkfdn/ncspot#586]
I don't know if this is possible or not, but I couldn't find anything about it in the documentation. Is it possible to play a song directly from a single command with ncspot, rather than opening the program and navigating?

I'm attempting to use the "at" package as an alarm clock, and would like to play a specific song. But to do so I would either need to download the song locally and use a local music player, or if possible I would love to just specify the song and play it through ncspot. Is this doable?

**Comment by Bettehem** [comment]
Yeah you can control ncspot via MPRIS using something like [playerctl](https://github.com/altdesktop/playerctl).

**Comment by TheNomadicAspie** [comment]
Thank you so much.
