### ISSUE TITLE
F1 not focusing queue

### ISSUE THREAD

**Issue by mrsteve0924** [hrkfdn/ncspot#592]
F1 not focusing queue.  just keeps bringing up the terminal help menu (xfce4-terminal)
while in my library  F1 will not bring up queue of current play list.  F2 works and so does F3
i just installed ncspot yesterday, and the F1 was working as expected.  can't figure out what changed. 

[edit]  i figured out the command :focus queue works though
 
[edit2] set f4 as focus queue instead of f1.  seems to work.   all good now  i guess.

**Comment by Bettehem** [comment]
Your terminal emulator is probably capturing your F1 key. For example Xfce Terminal does this. You can disable it by going to `Edit -> Preferences -> Advanced` and then select `Disable help window shortcut key (F1 by default)`

**Comment by mrsteve0924** [comment]
> Your terminal emulator is probably capturing your F1 key. For example Xfce Terminal does this. You can disable it by going to `Edit -> Preferences -> Advanced` and then select `Disable help window shortcut key (F1 by default)`

easy enough. thanks.
