### ISSUE TITLE
wrong display of characters

### ISSUE THREAD

**Issue by antoineouellet** [hrkfdn/ncspot#594]
**Describe the bug**
Text display issue while using ncspot.
For example, the two last lines always display \~T\~I \~T\~I \~T\~I \~T\~I \~T\~I ...
Song length is replaced \~\\~S
Open menu is \~T\~BT\~@
etc.

**To Reproduce**
Unknown. This system has two users that were created at the same time with mostly the same parameters (AFAIK).
One user has the problem and not the other.

**Expected behavior**
Normal display of characters.

**System (please complete the following information):**
 - OS: Manjaro Linux
 - Terminal: Alacritty, Xfce terminal, Konsole
 - Version: 0.8.2-1
 - Installed from: AUR, rolling

**Additional context**
Found only one mention on a forum of someone having the same problem. No solution.
I do not have any other display problem on the system, CLI or GUI.

**Comment by Bettehem** [comment]
Is your issue the same as [#556](https://github.com/hrkfdn/ncspot/issues/556)?

**Comment by antoineouellet** [comment]
Yes. Sorry to not have fallen on this thread before, it set me on the right path.

I had forgotten to mention that I had priorly tried to reset my locale through command line as described in the Arch wiki (as hinted in the forum I mentioned). Did not work for me nor for that other user.

However, it turns out Plasma keeps a local-user overriding the system locale configuration file in home (~/.conf/plasmalocalerc). This was created to en_CA... when I edited my panel to display dates as YYYY-MM-DD. All in all an Arch/Manjaro/KDE problem really.

So problem solved.
