### ISSUE TITLE
Permit binding multiple commands to a shortcut

### ISSUE THREAD

**Issue by H-M-H** [hrkfdn/ncspot#596]
**Is your feature request related to a problem? Please describe.**
When enqueuing songs I often want to enqueue multiple consecutive songs and pressing `Space` and then `Down` is a bit annoying.

**Describe the solution you'd like**
Binding multiple commands to a key easily solves this problem as this `"Space" = "queue; move down 1"` becomes possible.

**Describe alternatives you've considered**
Of course a new command to could be added to handle enqueuing a song and moving one item down but that is less flexible.

**Additional context**
Actually I already have an implementation of this: https://github.com/H-M-H/ncspot/commit/10cb013f6d81ce7f31c7d2b81b6a48eba6bc2675?w=1
If this feature is wanted, I will open a pull request.

**Comment by hrkfdn** [comment]
I like the idea! Maybe instead of parsing multiple commands using delimiters we could allow TOML arrays? For instance:
`"Space" = ["queue", "move down 1"]`

Haven't tested this, but it should make config file parsing a little simpler I think.

**Comment by H-M-H** [comment]
I also thought about this, but it does feel unpractical for usage with the builtin command prompt.

**Comment by hrkfdn** [comment]
Oh yeah, good point. Though I wonder how common it is for users to chain commands in the prompt.

**Comment by hrkfdn** [comment]
I think a PR would be a good start, we can still iterate on it then (if necessary).

**Comment by H-M-H** [comment]
Alright, PR is at: #598.
> Though I wonder how common it is for users to chain commands in the prompt.

Something else to consider is that this might change, if some kind of remote controlling is implemented as requested here: #524.
