### ISSUE TITLE
Unknown command: toggle & sort

### ISSUE THREAD

**Issue by cyqsimon** [hrkfdn/ncspot#597]
## Description
`toggle` and `sort` are listed as available commands in [README](https://github.com/hrkfdn/ncspot#commands), but not actually usable.

## Steps to reproduce
1. Play any playlist
2. Type <kbd>:</kbd>, followed by either `toggle` or `sort`
3. UI prompts `ERROR: Unknown command: "toggle/sort"`

## System
 - OS: Manjaro KDE
 - Terminal: Yakuake & Konsole
 - Version: 0.8.2
 - Installed from: AUR & cargo

**Comment by H-M-H** [comment]
Looks like `toggle` is actually `playpause` or one of its aliases: `pause`, `toggleplay`, `toggleplayback`.  Sorting a playlist works fine for me as long as I supply the sort key, for example `title`.

**Comment by cyqsimon** [comment]
@H-M-H huh that's interesting. `sort` simply won't work on my box.

![bug](https://user-images.githubusercontent.com/28627918/132513076-5b97244c-a9ef-4056-bc61-3551b22687fe.gif)

**Comment by H-M-H** [comment]
Do you have a playlist focused? As far as I can tell it only works for playlists.

**Comment by cyqsimon** [comment]
I think it's fair to say I've tried to run `sort` in every view there is (including Queue [F1], Library-Tracks [F3, tab 1], Library-Playlist [F3, tab 4]). It hasn't worked on any view for me.

What exactly do you mean by "focused"? Can you perhaps record a GIF of the command working? Maybe I'm misunderstanding something.

**Comment by H-M-H** [comment]
That's weird. With focused I mean you are viewing one of your saved playlists:
![2](https://user-images.githubusercontent.com/7461564/132537034-4dd5230a-b6f5-490b-8a11-a363bc1840d7.png)
![3](https://user-images.githubusercontent.com/7461564/132537048-e8ac6c0e-467b-4529-b574-951c8e98d044.png)

I am running on latest master though, so perhaps something changed in this regard?

**Comment by cyqsimon** [comment]
Ah okay I see what I did wrong. I misunderstood you and was trying to sort the active queue. `sort` works as intended in the detailed view of the playlist.

Perhaps we can add a note in README? Or better yet, add the sort feature to the active queue as well?

**Comment by cyqsimon** [comment]
Also the error prompt could be improved. Perhaps instead of a uniform `Error: Unknown command: "sort"`, maybe show a more informative prompt like `Error: "sort" command is unsupported in this view`?

**Comment by hrkfdn** [comment]
Yes, this is more of a documentation problem, although the error is sort of misleading. Maybe `sort` without arguments or in an unsupported view could trigger a more specific error message.
