### ISSUE TITLE
Undefined reference to various ncurses constants

### ISSUE THREAD

**Issue by kiroma** [hrkfdn/ncspot#6]
[Pastebin with error](https://pastebin.com/diCwNXF7)
Tested on OpenSUSE Tumbleweed with rustc 1.31.1

**Comment by hrkfdn** [comment]
Hey, thanks for the report. I believe this is a problem with ncurses-rs, which is a dependency of Cursive. So I don't think I can fix it here. Sorry!

**Comment by ntasos** [comment]
I had the same issue on Tumbleweed with rust 1.32. I installed ncurses5-devel and it compiles without errors.
Maybe it will help you.

**Comment by kiroma** [comment]
Oh yeah I figured that out in post. Seems to be a really peculiar issue with ncurses-rs.
