### ISSUE TITLE
Change playlist saving functionality

### ISSUE THREAD

**Issue by medwards** [hrkfdn/ncspot#60]
I skimmed the new keyboard commands and thought `s` saved a specific song that was selected in the queue. This is my normal flow (play Discover Weekly for example and add stuff I like).

This resulted in me wiping out a 200+ song playlist.

I'd recommend changing it to *add* specific tracks to playlists or having a big-ass warning dialog if the playlist already has tracks.

I'm going to QQ somewhere now.

**Comment by hrkfdn** [comment]
Ouch, sorry to hear that.

I'm not sure I understand, though. As of today `s` should add/remove tracks to the library, `Ctirl-s` will save it to a new or existing playlist. The behavior of the "save playlist" dialog hasn't changed, though, just the binding.

Do you mean to suggest that the latter should show a warning that it will overwrite the existing playlist? Seems reasonable to me.

**Comment by medwards** [comment]
I'll double-check this later, but I'm pretty sure I just pressed unmodified
`s` on a track in the queue.

I also can't definitively confirm that it went down how I said, I'm
inferring from:
1. Earlier this week I wanted to add two tracks from my Discover Weekly to
Started
2. Pressed the key combination, didn't look closely just selected a
playlist from the dialog
3. This morning I wanted to listen to some Starred tracks and found the
Discover Weekly tracks instead

Anyways, if the default behaviour for s is single track addition then
that's already good (how I possibly pressed ctrl-s I dunno...) And yeah it
would be good to warn users about overwriting playlists.

**Comment by hrkfdn** [comment]
I have updated the wording in the save queue dialog. If you think this still isn't clear enough or have other feedback, please let me know, I'll gladly make it more obvious.
