### ISSUE TITLE
Share function does not copy to system clipboard

### ISSUE THREAD

**Issue by deed02392** [hrkfdn/ncspot#603]
**Describe the bug**
When using the share feature, either via `:share` or the keybindings, although the command executes, the share URI is not set as the current system clipboard value.

**To Reproduce**

1. Play a song
2.  Execute `:share current`
3. Observe system clipboard is not set to a Spotify share URI

**Expected behavior**
Spotify share URI should be set on the clipboard

**System (please complete the following information):**
 - OS: macOS
 - Terminal: iTerm 2
 - Version: 0.8.2
 - Installed from: brew

**Comment by mjclements** [comment]
I'm interested in taking a look at this.

**Comment by hrkfdn** [comment]
@mjclements Sure, feel free! :)

**Comment by mjclements** [comment]
So, it appears to be as simple as the feature isn't enabled in the brew formula. Brew uses `cargo run --no-default-features --features portaudio_backend,cursive/pancurses-backend` like README.md suggests for macOS. Simply changing this to `cargo run --no-default-features --features portaudio_backend,cursive/pancurses-backend,share_clipboard` appears to fix the issue.
It would be really nice if cargo supported conditional features based on operating system, but it doesn't. So in the meanwhile @hrkfdn, would you think it better to edit the brew formula? We could also just un-feature gate the sharing, as it appears to work cross-platform.

**Comment by deed02392** [comment]
Confirmed that setting the `share_clipboard` feature on cargo works. Agree to either add the flag to the feature list in the formula or remove the feature gate.

**Comment by hrkfdn** [comment]
@mjclements I think we should add it to brew. The reason it's optional is that it pulls in dependencies to access the clipboard state, which are not available in non-graphical environments.

**Comment by mjclements** [comment]
I've opened a PR on homebrew: https://github.com/Homebrew/homebrew-core/pull/85883 . If that gets merged, hopefully we can mark this as resolved,

**Comment by hrkfdn** [comment]
Looks like it was merged. Thanks, @mjclements
