### ISSUE TITLE
Windows build fails since 0.8.2

### ISSUE THREAD

**Issue by oclero** [hrkfdn/ncspot#605]
**Describe the bug**
Windows build fails since 0.8.2. I was able to build `ncspot` successfully in 0.8.1. Now, I get the following error message:

```powershell
error: failed to run custom build command for `libdbus-sys v0.2.1`

Caused by:
  process didn't exit successfully: `C:\Users\oclero\Documents\Development\ncspot\target\release\build\libdbus-sys-3cd811e9636c7097\build-script-build` (exit code: 101)
```

And further:
```powershell
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", cause: Os { code: 2, kind: NotFound, message: "Le fichier spécifié est introuvable." } }', C:\Users\ocler\.cargo\registry\src\github.com-1ecc6299db9ec823\libdbus-sys-0.2.1\build.rs:6:70
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**To Reproduce**
1. Open a Windows terminal.
2. Run `cargo install ncspot`. (Since 0.8.2)
3. Wait for the build to process...

**NB:** I get the same error if I clone the repository and run `cargo build --release` inside.

**Expected behavior**
`ncspot` 0.8.2 should build successfully like 0.8.1.

**System (please complete the following information):**
 - **OS:** Windows 10 21H1 19043.1237
 - **Rust/Cargo:** 1.55.0
 - **Terminal:** Windows Terminal 1.10.2383.0
 - **Ncspot:** 0.8.2, master branch
 - **Installed from:** cargo, cloned repository

**Full build log**
- 📄 [ncspot-build-log.txt](https://github.com/hrkfdn/ncspot/files/7215938/ncspot-build-log.txt)
    **Remark:** the French message "Le fichier spécifié est introuvable." means "The specified file can not be found.".

**Comment by hrkfdn** [comment]
The windows build is built using these feature flags: https://github.com/hrkfdn/ncspot/commit/7622292ffa42629979e15da8712d47157e0b9e27

You may want to try those

**Comment by hrkfdn** [comment]
Also there is a binary here if that helps: https://github.com/hrkfdn/ncspot/releases/tag/v0.8.2

**Comment by oclero** [comment]
I used the pre-compiled binary, yes :)
Also, it builds successfully with the added features flags. It's just a matter of updating the build instructions in the README, so great news! (I get a few warnings, though, but I guess you already know that)
Thanks! Do you want me to make a PR to update the build instructions for Windows in the README?

**Comment by hrkfdn** [comment]
@oclero Sure, a PR is always appreciated :)

**Comment by hrkfdn** [comment]
Closing this for now

**Comment by oclero** [comment]
@hrkfdn The PR is made. It took longer than expected because I made a big overhaul for the whole README ;)
