### ISSUE TITLE
Share album

### ISSUE THREAD

**Issue by deed02392** [hrkfdn/ncspot#606]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to store the album share link to the system clipboard for the album associated to the currently playing track, or the selected track.

**Describe the solution you'd like**
A 'Share album' entry in the song context menu.
A 'Share album' command that stores the album share link to the clipboard for the album _in context_, when you have navigated to the album for a given track (via the 'Show album' context menu entry)

**Describe alternatives you've considered**
You can add an album to your library, navigate to it and then use the 'share selected' command, but this is cumbersome especially if you are only interested in sharing the album with somebody else and not necessarily interested enough in adding it to your own library permanently.

**Comment by hrkfdn** [comment]
Added, thanks. Btw, if the currently selected item is an album you can also press `x` (which will share the currently selected item).
