### ISSUE TITLE
Download/cache a playlist

### ISSUE THREAD

**Issue by jessicah** [hrkfdn/ncspot#618]
**Is your feature request related to a problem? Please describe.**
Songs often pause mid-way for a second or two playing for the first time; it'd be nice to be able to download/cache a playlist to workaround the issue.

**Describe the solution you'd like**
An option to cache a playlist to avoid the pauses

**Describe alternatives you've considered**
Can't think of any, other than the client caching songs better...

**Additional context**
Probably an issue with an upstream dependency, I've experienced issues with I think it was spotifyd as well.

**Comment by hrkfdn** [comment]
Hey, librespot supports caching and it should be enabled by default. You can validate this by checking if there are files in `~/.cache/ncspot/librespot/files`.

If there are error messages printed to `stderr`, you can persist them by running ncspot like so `ncspot 2> /tmp/stderr.log`. A regular debug log using the `-d` flag may also be helpful to see if there are buffer underruns.

**Comment by hrkfdn** [comment]
Caching is already supported. Downloading of playlists can not be implemented currently as it's not supported by librespot.

Closing this as the playback issue seems to be covered here: https://github.com/librespot-org/librespot/issues/864
