### ISSUE TITLE
F3 shows me no search screen and I can't come back from the search screen.

### ISSUE THREAD

**Issue by rizzini** [hrkfdn/ncspot#630]
F3 for search doesn't work. Here it turns down the volume by 10%. 

I added this to `~/.config/ncspot/config.toml`:
```
[keybindings]
"Shift+s" = "search"
```
Now I can use the search, but I can't come back to the library screen. Already tried backspace.

Version: 0.8.2

**Comment by hrkfdn** [comment]
Seems like something is incorrectly configured in your terminal emulator regarding F-keys. Do F-keys work in other terminal applications?

**Comment by Bettehem** [comment]
Could [#592](https://github.com/hrkfdn/ncspot/issues/592) be related?

**Comment by rizzini** [comment]
> Seems like something is incorrectly configured in your terminal emulator regarding F-keys. Do F-keys work in other terminal applications?

That's it. When I press F3, `[[C` appears on my terminal. I'll have to check KDE hotkey.  Thanks, man. It's on me from now on.

**Comment by rizzini** [comment]
> Do F-keys work in other terminal applications?
Yes. It worked using xterm. 

So It's something in my environment. It's on me now. Should close the issue?

**Comment by hrkfdn** [comment]
Can be closed :)
