### ISSUE TITLE
Add Wayland clipboard support

### ISSUE THREAD

**Issue by mdartmann** [hrkfdn/ncspot#633]
The clipboard package used unfortunately uses on X11's headers and library.  I mostly work on Wayland-based environments and XWayland's clipboard integration has been shotty at best for me, so I would appreciate it if it would be possible to support Wayland in a more native fashion, 

I don't much about rust myself (if I did, this would be a PR instead), but the [copypasta](https://crates.io/crates/copypasta) crate or the [wl-clipboard CLI tool](https://github.com/bugaevc/wl-clipboard) might be something to start working with.

**Comment by Bettehem** [comment]
I found this project: [wl-clipboard-rs](https://github.com/YaLTeR/wl-clipboard-rs) which could be used to solve this issue. I could take a look at this and see if I can implement it (I'm still quite a Rust noob so not sure if I can), but it might be a couple weeks before I'll have the time to start

**Comment by Bettehem** [comment]
I have now fixed this with my latest [pull request](https://github.com/hrkfdn/ncspot/pull/666).
