### ISSUE TITLE
wrong display of non-english band names

### ISSUE THREAD

**Issue by zveber** [hrkfdn/ncspot#635]
When the app shows tracks in user library or in results of search or in queue band names are latinized. So instead of `Тараканы! ` I see `Tarakany! `,  instead of `Психея` there is `Psychea` and so on.  Albums, track names and playlist names look good though.

Version: `0 8.2' for Linux.

**Comment by hrkfdn** [comment]
Hey, I just compared the API requests for playlist tracks and search. For both requests the user country is passed to the API, so they should be localized the same. It's possible this is handled differently in rspotify, so #640 may help with this. Other than that there is not much I can do as ncspot just displays the API results.

**Comment by zveber** [comment]
Got it. I hipe some day they will take into account user locale.
