### ISSUE TITLE
ncspot fails to build on ubuntu: error[E0658]: arbitrary expressions in key-value attributes are unstable

### ISSUE THREAD

**Issue by fjgibson** [hrkfdn/ncspot#643]
ncspot build fails on ubuntu. (Apologies if I am missing something obvious, I am new to Rust)

Rust version (latest, i believe):
- rustc 1.58.0-nightly (936238a92 2021-11-11)
- cargo 1.58.0-nightly (2e2a16e98 2021-11-08)

System:
 - OS: Ubuntu 20.04.3 LTS x86_64
 - Terminal: gnome-terminal
 - Version: 0.9.0 main branch
 - Installed from: cargo

running `cargo build --locked` produces:

> log:
> error[E0658]: arbitrary expressions in key-value attributes are unstable
>    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rspotify-model-0.11.2/src/idtypes.rs:284:21
>     |
> 284 |               #[doc = concat!(
>     |  _____________________^
> 285 | |                 "ID of type [`Type::", stringify!($type), "`], made up of only \
> 286 | |                 alphanumeric characters. Refer to the [module-level \
> 287 | |                 docs][`crate::idtypes`] for more information.")
>     | |_______________________________________________________________^
> ...
> 413 | / define_idtypes!(
> 414 | |     Artist => ArtistId,
> 415 | |     Album => AlbumId,
> 416 | |     Track => TrackId,
> ...   |
> 419 | |     Episode => EpisodeId
> 420 | | );
>     | |__- in this macro invocation
>     |
>     = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
>     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
> 
>    Compiling cookie_store v0.15.0
>    Compiling wasmer_enumset v1.0.1
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0658`.
> error: could not compile `rspotify-model`
> 
> To learn more, run the command again with --verbose.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> 

Additional info: 

>  see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

suggests this issue is resolved. But maybe I am misunderstanding.

**Comment by hrkfdn** [comment]
Hmm, it works fine with Rust stable 1.56.1 here. Can you try with the latest stable version?

**Comment by snusmu** [comment]
getting same issue with rust 1.53 / cargo 1.53 in Ubuntu 20

**Comment by snusmu** [comment]
Update: after uninstalling the ubuntu's default rust/cargo and instead installing latest stable rust/cargo 1.57 using rustup (rustup itself was installed with snap), build succeeded.

**Comment by hrkfdn** [comment]
In any case this would a problem with rspotify, a library that ncspot uses, but it seems to be fine when using the latest stable compiler, so closing this. Feel free to reopen if it's still an issue.
