### ISSUE TITLE
ncspot won't fetch albums

### ISSUE THREAD

**Issue by isinyaaa** [hrkfdn/ncspot#650]
**Describe the bug**
The latest version of ncspot doesn't seem to fetch albums properly.

**To Reproduce**
1. `rm ~/.cache/ncspot/albums.db`
2. open ncspot and wait for it to update
3. go to albums tab and see empty
4. `cat ~/.cache/ncspot/albums.db` to confim

**Expected behavior**
Neither the `.db` or the tab should be empty if user has any albums.

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Kitty
 - Version: 0.9.1 from main branch (though it appears 0.9.0 as there's no tag for the newest version yet)
 - Installed from: AUR

**Backtrace/Debug log**
_https://gist.github.com/a9878f0d4a339b90a12a2033a3ba9f00_

**Additional context**
I tried going back to 0.9.0 and it seems to work just fine.

**Comment by hrkfdn** [comment]
Thanks, this is actually a bug in rspotify: https://github.com/ramsayleung/rspotify/issues/285

Will fix upstream. If their release cycle takes longer than expected I have an idea for a workaround.
