### ISSUE TITLE
Option to display playlist's owner username

### ISSUE THREAD

**Issue by tsundokul** [hrkfdn/ncspot#652]
I have many playlists that have the same name but belong to different users. It would be nice to have a setting in `config.toml` to enable the display of username next to a playlist's name

This is how it looks right now
![image](https://user-images.githubusercontent.com/42388638/142723729-38f73bac-5a8e-4b2b-90b7-31f1a984cd96.png)

How I imagine it
```
Discover Weekly • pickcolgate
Discover Weekly • miaowother
Discover Weekly • bloodhoundsubmissive
Discover Weekly • silverfishcounselor
```

**Comment by hrkfdn** [comment]
Nice idea, I've added this. You will have to clear your playlist cache for it to take effect: `rm ~/.cache/ncspot/playlists.db`
