### ISSUE TITLE
Shuffle mode not working when opening a playlist via MPRIS

### ISSUE THREAD

**Issue by superjojo140** [hrkfdn/ncspot#654]
**Describe the bug**
When shuffle is enabled and starting a playlist **via ncspot's ncurses interface** it starts with a random song and continues with another random song (as described in #128).

When opening a playlist **via MPRIS** with `playerctl --player=ncspot open <PLAYLIST_URL>` the playlist allways starts with the first song, even if shuffle mode is enabled.

I'm working on an embedded music playing device so i can't use ncspot directly via the ncures interface. How can i achive starting a playlist with a random song by a simple cli command?

**To Reproduce**
1. start ncspot
2. enable shuffle mode
3. execute `playerctl --player=ncspot open https://open.spotify.com/playlist/37i9dQZF1DWZJhOVGWqUKF`
4. ncspot starts playing the playlist, but allways with the first song...

**Expected behavior**
ncspot starts playing the playlist, but with a random song

**System (please complete the following information):**
 - OS: archlinux
 - Terminal: konsole (bash)
 - Version: ncspot 0.9.0
 - Installed from: AUR

**Comment by Bettehem** [comment]
I have now made a [pull request](https://github.com/hrkfdn/ncspot/pull/662) which fixes this issue

**Comment by superjojo140** [comment]
@Bettehem Thanks a lot. Does exactly what i want!

I cloned your fork and compiled it on my Raspberry Pi 3 for ARM (took about 3 hours...😔) and it works like a charm. Awesome👍🏼

**Comment by Bettehem** [comment]
Haha yeah Raspberry Pi build times are really long, but I'm glad it works!
