### ISSUE TITLE
Better memory management for the AUR package

### ISSUE THREAD

**Issue by dvisan** [hrkfdn/ncspot#656]
Windows based ncspot occupies around 50-65mb of RAM while using it in a customised Windows Terminal.

On EndeavourOS instead, it stays constantly at ~130mb in every terminal. The same on Manjaro. Thus, since on both distros it came via pacman, I suppose we can isolate it to the AUR package.

Thanks for the good job with ncpost so far btw, works unexpectedly well!

**Comment by JBGruber** [comment]
I installed it from AUR on EndeavourOS and mine takes up 60mb in memory. Version is ncspot 0.9.4-1.

However (and this is maybe a different issue), ncspot takes a very long time to 'boot up'. The Playlists tab is empty until ~1min after start before my playlists are pulled from the API (I assume). Did you encounter something similar?

**Comment by dvisan** [comment]
@JBGruber no, I did not, mine loads up as expected.

however, the snap package for ubuntu exhibits the same memory usage as the one for EndeavourOS in my case:
![image](https://user-images.githubusercontent.com/13108600/151137805-2429b023-4191-4f52-83a8-6be8784af715.png)

**Comment by JBGruber** [comment]
I identified my issue with booting up ncspot: I had a very large playlist (+7000 songs) as the first entry in Playlists. When I moved it to the last spot, the issue went away and I could start playing songs after ~2-3 seconds (it still takes ~1 min for the large playlist to load).

**Comment by hrkfdn** [comment]
Hey there, may I suggest to report this to the AUR maintainer as I don't maintain the PKGBUILD. Thank you!
