### ISSUE TITLE
Add to collaborative playlist doesn't work

### ISSUE THREAD

**Issue by salunn** [hrkfdn/ncspot#657]
**Describe the bug**
Adding a track to a collaborative playlist, then pressing shift+u to update doesn't show the track having been added.

**To Reproduce**
1. Select a track
2. Press o to bring up the context menu, select add to playlist
3. Select a collaborative playlist
4. Press shift+u to reload playlists, open collaborative playlist
5. See track not having been added

**Expected behavior**
Tracks should be added to collaborative playlists.

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Terminator
 - Version: 0.9.0-1
 - Installed from: AUR

**Backtrace/Debug log**
No debug logs available

**Additional context**
-

**Comment by hrkfdn** [comment]
Hmm, I can't reproduce this locally. Neither with 0.9.0 nor with the latest `main` branch. Could you provide a debug log?

**Comment by hrkfdn** [comment]
Closed due to lack of feedback/unable to reproduce
