### ISSUE TITLE
Ability to run shell commands

### ISSUE THREAD

**Issue by dan-forsberg** [hrkfdn/ncspot#673]
**Is your feature request related to a problem? Please describe.**
I'm currently running `ncspot` in a `screen` to be able to close the terminal that it's running in without stopping the music. This is a setup I've used with `cmus` before and in `cmus` I was able to bind the `q` key to run a shell command. In my case to detach from the screen to drop down into a terminal.

However I'm not able to do this with `ncspot` because I cannot bind a key to run a shell command.

**Describe the solution you'd like**
An ability to run shell commands and the ability to bind a key to run that command, just like for example `:pause` can be bound to a key.

**Describe alternatives you've considered**
Another possible solution, which I've seen been requested in issue #284 is to add a background/daemon-mode but understadably it's not a small feature to develop.

**Comment by Bettehem** [comment]
Could you bind a key to a `playerctl` command? ncspot can be controlled via MPRIS and `playerctl` let's you do that quite easily.

**Comment by dan-forsberg** [comment]
I have that sorted out already through my DE, so the media keys on my keyboard can play/pause, play the next song etc. But I'd like to be able to open a terminal, run `spotify` (or another alias which would attach to the screen with `ncspot`), change playlists, hit `q` (which would run `screen -D [screen name]`) and be dropped back to my shell without actually closing `ncspot`. 

Right now I can /sort of/ do that, but I have to open another shell/terminal to detach the `ncspot`-screen or I have to close the terminal window.

Other than that I'm really liking the project :+1:

**Comment by hrkfdn** [comment]
Sounds like a reasonable feature, will look into it when I have the time :)
