### ISSUE TITLE
Put Cargo.lock into git repository

### ISSUE THREAD

**Issue by Herbstein** [hrkfdn/ncspot#68]
The program has a lot of dependencies (370 to be exact). It would be great to get everyone on the same page with this file. A package getting updated unexpectedly could lead to diverging behavior. This is especially true when `winapi` is pulled in as an git repository without being pinned - if there is an api change this binary will seize to build. 

It would lead to some annoyance regarding people's own local versions, but I'd argue that small annoyance is alright. I do wonder how the AUR package handles something like that though.

**Comment by Herbstein** [comment]
The Rust book also agrees with me on this point, and the link and argument is also present in the `.gitignore` in the repo.

https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

**Comment by hrkfdn** [comment]
I agree. I'm worried though, will this cause problems when building on platforms that are different to the one I generated `Cargo.lock` on? That would be the only thing worrying me.

**Comment by Herbstein** [comment]
I don't run on Windows anymore, so I won't be able to test for you. If there is anyone running Windows you could ask them to test on a separate branch. I guess it would be the same for any package that relies on platform-specific APIs. I would hope `cargo` can handle it, but I have no experience with it.
