### ISSUE TITLE
No `WM_NAME` property

### ISSUE THREAD

**Issue by Hooregi** [hrkfdn/ncspot#685]
**Is your feature request related to a problem? Please describe.**
`ncspot` doesn't spawn with a window name, so stuff like auto-workspaces in i3 aren't configurable.

**Describe the solution you'd like**
For a **static** window name to be added (i.e "ncspot").

**Describe alternatives you've considered**
My current solution is to have a custom alias, like so:

```{bash}
alacritty --title="ncspot" -e /usr/bin/ncspot
```

This works flawlessly since it's just changing the title of Alacritty.

**Additional context**
I looked at the config and didn't find anything (apologies in advance if there is), and I had the `dynamic_title` flag as `true` in my Alacritty config. Also, tried it with xfce4-term, gnome-term, xterm, and kitty.

I used `xprop` to check whether ncspot would spawm with a window name, other programs like `pulsemixer` do have this functionality. Hopefully it isn't too difficult to implement. Let me know if any images or the xprop outputs are needed.

**Comment by hrkfdn** [comment]
Hi there, unfortunately this is not yet possible with Cursive, see also:

- https://github.com/hrkfdn/ncspot/issues/73
- https://github.com/gyscos/cursive/issues/380

But I can manually print the ESC sequence to set the title, e.g. as described here: https://tldp.org/HOWTO/Xterm-Title-3.html

I have pushed a small change for this. Could you see if that solves it for you?

**Comment by rashil2000** [comment]
> I have pushed a small change for this. Could you see if that solves it for you?

Hi @hrkfdn, I have a couple of questions:
- Why is this disabled for Windows? The support for xterm sequences is terminal-dependent AFAIK, not OS dependent. Plenty of terminals support this (and pretty much all) xterm sequences. Windows Terminal, ConEmu, Alacritty etc. to name a few.
- Is it possible to emit this escape sequence for every song change and/or play/pause state change?

**Comment by hrkfdn** [comment]
Hey @rashil2000 
>     * Why is this disabled for Windows? The support for xterm sequences is terminal-dependent AFAIK, not OS dependent. Plenty of terminals support this (and pretty much all) xterm sequences. Windows Terminal, ConEmu, Alacritty etc. to name a few.
I wasn't sure whether the Windows Terminal supported this, but if you're willing to test it I can enable it on `main`. Could you do a build on Windows to see if it works once I push it?
>     * Is it possible to emit this escape sequence for every song change and/or play/pause state change?
Theoretically yes. I originally wanted to do this, but I don't know if this can still be filtered with i3 rules as needed by @Hooregi, i.e. if it supports regular expressions or similar. Then we could go for a naming pattern such as `ncspot - {artist} - {title}` or similar.

**Comment by rashil2000** [comment]
> I wasn't sure whether the Windows Terminal supported this, but if you're willing to test it I can enable it on `main`. Could you do a build on Windows to see if it works once I push it?

I have already tested it (by removing the `cfg` line in my fork). Tested with the 3 terminals mentioned above.

> Theoretically yes. I originally wanted to do this, but I don't know if this can still be filtered with i3 rules as needed by @Hooregi, i.e. if it supports regular expressions or similar. Then we could go for a naming pattern such as `ncspot - {artist} - {title}` or similar.

I'm not much familiar with i3, but I guess if we follow how Spotify Desktop app behaves we could do it in a standardized way.

**Comment by Hooregi** [comment]
> I have pushed a small change for this. Could you see if that solves it for you?

Thank you for taking the time to patch this, especially on a 31st of December. I'll get to building it right away.
