### ISSUE TITLE
Winget Package

### ISSUE THREAD

**Issue by Maxplosion** [hrkfdn/ncspot#686]
**Describe the solution you'd like**
Hello, have you thought of creating a winget package for ncspot? 
Having a scoop package is good, but having it also on winget would be great as well.

**Comment by hrkfdn** [comment]
Hi :wave:, I can't maintain all the packages for all platforms/operating systems. If someone is willing to take this over I'd be happy to assist/review PRs, but as I don't even use ncspot on Windows I won't be able create a winget package.

**Comment by rashil2000** [comment]
Winget does not support zip archives as of now. See https://github.com/microsoft/winget-cli/issues/140
