### ISSUE TITLE
Use a two-queue system like the official clients

### ISSUE THREAD

**Issue by Herbstein** [hrkfdn/ncspot#69]
The official Spotify clients use, effectively, two queues. The first queue is the general playback queue, which would be what `ncspot` has now. The second queue is the user-handled queue. This is the queue a song is added to when you press "Add to Queue" in the official clients.

I took a screenshot from the Linux client to illustrate.

![](https://i.imgur.com/g6EVcig.png)

The user queue is emptied first, and then the playback queue is used. 

It's a feature that is great when you're playing a playlist, but want to hear a specific song next. This could be because you saw it mentioned online, a friend mentioned it, or any other reason.

**Comment by Herbstein** [comment]
Right now the queue is a single `Vec` wrapped in a `Arc<RwLock>`. The `ListView` in the `QueueView` accesses this directly. This gives the great functionality of having a dynamically updated list.

I was considering whether changing the implementation of the `Queue` struct to use two queues - one being the "play-queue" and the other being the "queue-queue" (terrible name) - and making the public interface of the `Queue` struct opaque to this implementation. This, however, would break the above-mentioned functionality. 

Do you have a suggestion as to how this could be done? One option is to divorce the `QueueView` from the `ListView`. We could try and mimic the Spotify layout as shown above instead. 

Another option is to rework the `ListView` to use a generator function, that simply returns a `Vec<I>` (or `Iterator<Item=I>`). It's trivial to extend the "play-queue" to the back of the "queue-queue" so this should be easily integrateable. 

The last option I've come up with is probably also the hardest to retrofit. We can keep the single queue and have it manually split by an index. Before the index would be the "queue-queue", and after would be the "play-queue". Whenever a song is played we'd pop the first (index `0`) from the "queue-queue" and reduce the "split" index by one. When the split index (wrapped in an `Option`) is non-existent the usual behavior is exhibited. Whether that's shuffling or not. Maintaining the invariants in this design would be tough, and it's a lot of index fiddling. I generally do not prefer this one. The nice part is that any usage of the `queue` field on the `Queue` struct would be unaffected.

**Comment by hrkfdn** [comment]
This is indeed a bit tricky. Historically, the queue was an actual queue where entries would be popped out/dequeued for playback until it is empty, at which point the playback stopped.

However, this is rather undesirable if you want to save the tracks that have accumulated in the queue to a playlist. Eventually this became a `Vec` to overcome this.

I am not really sure which way is the best here. If we want to reflect the behavior of the official client, we should probably drop this temporary queue altogether and instead use the playlists directly/in-place. The currently loaded list is then played until the end. We could then introduce an extra-queue that has priority over the currently loaded playlist. I believe this would be your "queue-queue", if I understood you correctly?

**Comment by Herbstein** [comment]
Yeah, you understood me correctly.

If we want a "save queue to playlist" the official desktop client has a "History" tab on the queue page. That could potentially be used.

I think moving back towards using a two-queue system with a history `Vec` would be preferable.

**Comment by Herbstein** [comment]
Do you have any ideas or suggestions on what to do with the `ListView` if I start moving to a proper queue-backed approach? I can't really see a path where major refactoring isn't required, but maybe you can?

**Comment by Herbstein** [comment]
Actually, since `QueueView` is a thing, I think it should be possible to retrofit the queue-backed approach into the 'ListView`.

**Comment by hrkfdn** [comment]
Not without major refactoring, no. Maybe it's reasonable to create a new View for the queue to display the entries? The `ListView` is still usable for the other views.

**Comment by oliver-daniel** [comment]
Building on @Herbstein 's idea of an index, you could consider having flyweight, sentinel values in the queue vector, such that the queue looks like (in human terms, since I don't actually know any Rust):

<...songs..., END_UP_NEXT ...songs..., END_PLAYLIST>,

with adding to Up Next inserting at `index(END_UP_NEXT)-1`. If you do this computationally (i.e., O(n) time), you don't run into index invariant issues, and I can't imagine a Rust-based backend having a performance problem with anything short of *thousands* of songs in Up Next.

This would also allow for simple rendering closer to the Spotify UI, since the sentinels would still be of type RowLock. Thus, they don't screw up row-based rendering of the songs, and they allow for conditional special rendering of the row they happen to fall on.

If this makes sense, I'd be happy to help... I'd finally have a justification to learn Rust.

**Comment by hrkfdn** [comment]
Hey there, thanks for your comment. The current WIP approach by @Herbstein (https://github.com/hrkfdn/ncspot/pull/79) uses two Vecs for the respective queues.

The sentinel value approach is interesting. The UI rendering seems simpler, yet I wonder if managing the queue (adding/removing tracks at the correct position, dequeueing, etc.) is more cumbersome.

In any case, if you are interested in working on this, I'll gladly take a PR.

**Comment by Johannesd3** [comment]
If I understand librespot-connect correctly, the Spotify backend solves this using an integer to denote where the first queue ends. But this seems like an error-prone approach, it's not very robust against mistakes while reordering. Maybe it was done for legacy reasons, at least the queue could be played without knowing that two queues exist.

**Comment by hrkfdn** [comment]
See also: https://github.com/hrkfdn/ncspot/pull/79#issuecomment-944394298
