### ISSUE TITLE
Typo in release asset name

### ISSUE THREAD

**Issue by rashil2000** [hrkfdn/ncspot#690]
I'm intentionally ignoring the template as this is not a bug report.

Normally, Scoop uses automated package updates, so as soon as a new release is made, Scoop will have it. But this time, it didn't.

There was a commit done some days ago - https://github.com/hrkfdn/ncspot/commit/487bc0dba0acac0a57227bc090fc5d82eea0af15 - which changed the release filename suffix from `x86` to `x68`. I assume this was not intentional. 

This is why Scoop failed to update the manifest, because the URL was supposed to be https://github.com/hrkfdn/ncspot/releases/download/v0.9.4/ncspot-v0.9.4-windows-x86_64.zip while actually it is https://github.com/hrkfdn/ncspot/releases/download/v0.9.4/ncspot-v0.9.4-windows-x68_64.zip

**Comment by rashil2000** [comment]
I'd like to add that the aforementioned commit, apart from changing the name of Windows and macOS release asset names, has introduced one additional regression: ncspot used to open in a separate window before instead of the calling terminal (ref: https://github.com/hrkfdn/ncspot/issues/23#issuecomment-856575136). This was fixed by https://github.com/hrkfdn/ncspot/pull/546. By making `pancurses` optional in the above commit, this change is made non-functional.

![image](https://user-images.githubusercontent.com/46838874/147883856-c67032dc-9340-4d32-b78f-2241c6870bc1.png)

**Comment by hrkfdn** [comment]
@rashil2000 Thanks for the heads up, that's a typo indeed. I have triggered a rebuild for the Windows target with the correct filename and also fixed the `win32` feature flag. It is available here: https://github.com/hrkfdn/ncspot/releases/tag/v0.9.4

**Comment by rashil2000** [comment]
Thanks for the quick fix. I can confirm the separate-window bug is fixed.

The Scoop package will get updated within the next hour.
