### ISSUE TITLE
Add a link to the full command list in README

### ISSUE THREAD

**Issue by MrConorAE** [hrkfdn/ncspot#707]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
In README.md, there's a link to the source code where users can view the full list of 'command-line' (the Vim-style prompt) commands that can be used inside ncspot. I'd like to propose amending the link to point directly to the relevant lines, namely [at this url](https://github.com/hrkfdn/ncspot/blob/211ce66cbd66a361a6d19b292f98474a78904654/src/command.rs#L227-L265).

**Describe alternatives you've considered**
Not doing that, I guess

**Additional context**
Nope.

I would do this myself, but I don't know how to edit the file, and I'm unfamiliar with the process of pull requests.

Thanks for making ncspot, I use it daily over the official Spotify client because it's just so much faster!
~ MrConorAE

**Comment by ChaboCode** [comment]
#721 Like this?

**Comment by hrkfdn** [comment]
Hi there, thanks for your comments, I've replied in the PR:
> Thanks for the PR, but I'd prefer to not merge this. It's very technical and the link would need an update every time the line/position changed, resulting in outdated documentation.
