### ISSUE TITLE
Error message when saving songs

### ISSUE THREAD

**Issue by AtomToast** [hrkfdn/ncspot#710]
**Describe the bug**
~~I used to always search for songs to then save them from the search result view. However now all of a sudden instead of saving the song, a popup at the bottom of the window appears saying `ERROR: The command "save" is unsupported in this view`.
This definitely used to work in the past and also still works when pressing 'o' and then selecting "Save Track" from the menu~~

okay, now all of a sudden the saving seems to work, not sure what changed. However the error message still appears. Even when successfully saving.

**To Reproduce**
1. Go to the search tab (F2)
2. Search for a song you have not saved yet.
3. Select the song
4. Tap 's'
5. Look at the Error message

**Expected behavior**
The song should have saved ~~and a tick should have appeared on the entry in the search results~~ with no error message being shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/27757087/149552603-62b2167a-59b9-4532-9954-4e4938994227.png)

**System
 - OS: Arch Linux
 - Terminal: st
 - Version: 0.9.4
 - Installed from: ncspot-bin AUR package

**Backtrace/Debug log**
The instructions for this section appear outdated. The mentioned section does not exist anymore

**Additional context**
Potentially independent of this issue, saving may not work for a while when first opening the application.

**Comment by hrkfdn** [comment]
Thanks for the report, should be fixed in `main` now
