### ISSUE TITLE
cover feature not available on Windows platforms

### ISSUE THREAD

**Issue by nbgibson** [hrkfdn/ncspot#725]
**Describe the bug**
This may be user error on my part, but it appears that due to the cover feature dependency "ioctl-rs" ncspot isn't able to be compiled on Windows systems with the cover feature. Attempting to build results in the following output with other assorted nested errors:

 ```
error[E0433]: failed to resolve: could not find `unix` in `os`

use std::os::unix::io::RawFd;
  |              ^^^^ could not find `unix` in `os`
```

**To Reproduce**
Attempt to build the project on a Windows machine (assuming a working Rust install and so forth) with the following command:
`cargo build --release --no-default-features --features rodio_backend,cursive/pancurses-backend,cover`

**Expected behavior**
ncsoft compiles and outputs a binary.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Windows
 - Terminal: Powershell
 - Version: 5.1.19041.1320
 - Installed from: N/A, building from source

**Backtrace/Debug log**
N/A, can provide if neccessary.

**Additional context**
Given the description from ioctl-rs, this may be working as intended:
_[The ioctl-rs crate provides raw definitions as well as safe bindings for system ioctl calls on Unix operating systems.](https://github.com/dcuddeback/ioctl-rs)_

If so, is there an alternate path available for cover functionality on Windows?

**Comment by hrkfdn** [comment]
I don't believe this feature will work on Windows as it requires `ueberzug`.

**Comment by nbgibson** [comment]
That is unfortunate but understandable. If a workaround isn't feasible for the platform a note would be appreciated in the ReadMe.
