### ISSUE TITLE
Corrupt download

### ISSUE THREAD

**Issue by WizKid64** [hrkfdn/ncspot#727]
**Describe the bug**
The download "ncspot-v0.9.5-macos-x86_64.tar.gz" is corrupt. It will not execute. The error message is "zsh: exec format error: ./ncspo2t"

the 'file' command' reports "data", when it should report "Mach-O 64-bit executable x86_64."

**Comment by hrkfdn** [comment]
Hmm yeah, that's odd. The problem is I can't retrigger the job because that will recreate all builds and may change the hashes :|

**Comment by WizKid64** [comment]
Just tried with previous versions. Same result.

Seems like Github's os x builds are corrupt...

**Comment by hrkfdn** [comment]
Should be working again :)
