### ISSUE TITLE
Set terminal title to currently playing track

### ISSUE THREAD

**Issue by hrkfdn** [hrkfdn/ncspot#73]
Use terminal sequences to have the terminal/window title indicate the current status (track playing, paused, title, etc.).

This will probably require a change in cursive.

**Comment by aidenscott2016** [comment]
I'll have a go at this

**Comment by hrkfdn** [comment]
Needs a change in cursive, closing for now as it can't be implemented in ncspot and is not a critical feature.

**Comment by bbx0** [comment]
Just linking gyscos/cursive#380 as I was looking for the same.
