### ISSUE TITLE
Configuration option for changing the name order of a song

### ISSUE THREAD

**Issue by haukkagu** [hrkfdn/ncspot#730]
Ncspot displays the name of the artist before the name of the track for every song (e.g. "Ludwig van Beethoven - Für Elise"). This is normally just a minor annoyance for me, but when listening to albums of many authors everything becomes a cluttered mess ([example](https://i.imgur.com/TUVcbUE.png)). I prefer that the name of the track comes first instead of the name of the artist (e.g "Für Elise - Ludwig van Beethoven" instead of "Ludwig van Beethoven - Für Elise"). This is basically the norm on every other music client, including the official spotify client, so I'd assume that many other people prefer it like that as well. I think there should atleast be a configuration option for changing this (maybe an option called "track_name_first" that can be set to true or false?).

Thanks!

**Comment by hrkfdn** [comment]
Solved via #800
