### ISSUE TITLE
Move to strongly typed message passing

### ISSUE THREAD

**Issue by Herbstein** [hrkfdn/ncspot#74]
Right now the program uses a string-based message-passing system. The primary reasons for this is enabling exhaustive pattern matching, and avoiding having to box and unbox strings internally. 

The current command system (e.g. `:<command> <args>`) slots neatly into the internal messages, which is currently a big plus. But I do think having a small command-translation layer is a small price to pay for otherwise proper internal message passing.

**Comment by Herbstein** [comment]
I've been posting most things that I notice could be improved. If I start becoming annoying or a pest do let me know :)

I've been using this as my daily driver, and have been loving it. i

**Comment by hrkfdn** [comment]
Hey,

could you elaborate on this a little? What would be the benefit? Less error-prone command handling in the UI parts? I agree that would be an improvement. In the beginning, commands were passed as enums via messages, but I believe we migrated to a string based approach to allow the user to directly input commands in the prompt and enable future keybindings.

> I've been posting most things that I notice could be improved. If I start becoming annoying or a pest do let me know :)
> 
> I've been using this as my daily driver, and have been loving it. i

Oh not at all, thanks for all the feedback.

**Comment by Herbstein** [comment]
Rust has a very strong type system. I think it's a shame if we forgo it to simply throw around strings until the last minute. Instead, I propose commands become strongly typed as early as possible. For internally passed commands - like for keybinds - this would mean they are always strongly typed.

For commands you'd need a parser. It's quite a simple parser that can split on spaces. 

I'm sure there is a good reason for going away from the Enum-based system, but I personally would prefer a stronger alternative to the current implementation.

**Comment by hrkfdn** [comment]
That's a reasonable approach. Are you interested in working on this?

**Comment by hrkfdn** [comment]
Fixed via https://github.com/hrkfdn/ncspot/pull/76
