### ISSUE TITLE
More controls for the currently playing track

### ISSUE THREAD

**Issue by Herbstein** [hrkfdn/ncspot#75]
Right now there's a lot of options for opening various views for the currently selected track/item. That is useful, but being able to open those same pages for the currently playing track is a definite must imo. It'd be equivalent to clicking the song or band name in the official client. 

The ability to add a track (playing or selected) to a playlist is also pretty important.

I'm thinking there should be a common style to this. Taking the sharing as an example: an action mapped to `<key>` should happen to the currently selected, while `Shift-<key>` should happen to the currently playing song (if any). Introducing this consistency would reduce overhead of learning two keybinds to do (logically) one action.

I'm not married to the key modifier or which (currently playing or selected) takes the action without the modifier, but a standard should be applied.

**Comment by hrkfdn** [comment]
I agree with this. Shift seems like a good choice, as it logically already applies to actions that affect the currently playing track (sharing, play/pause/stop, etc.).

**Comment by Herbstein** [comment]
I think that sounds very reasonable. Keybinds can be confusing unless you use them often, so standardizing as much as possible would be awesome!

**Comment by hrkfdn** [comment]
It was pretty straight-forward to extend, good work!
