### ISSUE TITLE
failed to compile: "There is no argument `content_len`"

### ISSUE THREAD

**Issue by mozai** [hrkfdn/ncspot#754]
**Describe the bug**
Errors when compiling from `cargo install ncspot`

**To Reproduce**
1. `cargo install ncspot`

**Expected behavior**
Not sure, just following [the build instructions](https://github.com/hrkfdn/ncspot#build) from the readme.md

**Screenshots**
n/a

**System (please complete the following information):**
 - OS: Linux
 - Terminal: n/a
 - Version: 0.9.5, 2022-02-24
 - Installed from: cargo

**Backtrace/Debug log**
```
   Compiling ncspot v0.9.5
error: there is no argument named `content_len`
  --> /home/moses/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.9.5/src/ui/listview.rs:88:34
   |
88 |         log::info!("content len: {content_len}");
   |                                  ^^^^^^^^^^^^^

error: there is no argument named `loaded`
   --> /home/moses/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.9.5/src/ui/listview.rs:100:35
    |
100 |         log::info!("can paginate: {loaded}");
    |                                   ^^^^^^^^

error: failed to compile `ncspot v0.9.5`, intermediate artifacts can be found at `/tmp/cargo-installnaAovk`

Caused by:
  could not compile `ncspot` due to 2 previous errors
```

**Additional context**
* cargo 1.57.0
* rustc 1.57.0

**Comment by hrkfdn** [comment]
Hey there, you probably need to update to latest Rust: https://github.com/hrkfdn/ncspot/issues/714

**Comment by mozai** [comment]
If there's a minimum required version for tools, please say so in the documentation.

**Comment by hrkfdn** [comment]
The relevant bits are already removed: https://github.com/hrkfdn/ncspot/commit/8eebf8916668869793784a359dfec059af84195a

**Comment by Bettehem** [comment]
> If there's a minimum required version for tools, please say so in the documentation. Is there a way in cargo to detect the version of rustc and throw an error if insufficient?

In general, you should always try building using the latest stable cargo/rustc versions
