### ISSUE TITLE
error: there is no argument named `content_len`

### ISSUE THREAD

**Issue by GopherJ** [hrkfdn/ncspot#757]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Linux, macOS]
 - Terminal: [e.g. GNOME Terminal, Alacritty]
 - Version: [e.g. 0.4.0, `master` branch]
 - Installed from: [e.g. AUR, brew, cargo]

**Backtrace/Debug log**
Instructions on how to capture debug logs: https://github.com/hrkfdn/ncspot#usage

To debug crashes a backtrace is very helpful. Make sure you run a debug build of ncspot, e.g. by running the command mentioned in the link above.

**Additional context**

**Comment by GopherJ** [comment]
will enrich the content soon

**Comment by hrkfdn** [comment]
Hey there, you probably need to update to latest Rust: https://github.com/hrkfdn/ncspot/issues/714
