### ISSUE TITLE
Getting error when moving to the currently playing track in queue

### ISSUE THREAD

**Issue by jmcantrell** [hrkfdn/ncspot#759]
**Describe the bug**

Moving the cursor to the currently playing track in the queue view works, but also gives the error message:
```
ERROR: The command "move" is unsupported in this view
```
**To Reproduce**
1. Go to the queue view
2. Press `p`
3. Notice that the cursor moves to the correct track
4. However, the error above displays

**Expected behavior**
No error.

**System (please complete the following information):**
 - OS: arch linux
 - Terminal: alacritty
 - Version: main
 - Installed from: source

**Backtrace/Debug log**
Not included because log contained authorization bearer tokens. I can post sections as needed. There were no crashes.

**Additional context**
Also does not work with the latest version from the AUR.

**Comment by hrkfdn** [comment]
Thanks for the report. Should be fixed in `main`.
