### ISSUE TITLE
Notification to be under the same Id

### ISSUE THREAD

**Issue by wael444** [hrkfdn/ncspot#760]
**Is your feature request related to a problem? Please describe.**
if `notify` is enabled and say, i play a new song and another after it the notification for the old song stays.
this does not happen when the notification is set under the same ID since the notification will take over the previous if available.
![image](https://user-images.githubusercontent.com/47404953/158063235-f787f9aa-b49a-4751-9a9d-ae5509516945.png)

**Describe the solution you'd like**
set the notification to the same ID if it is possible

**Describe alternatives you've considered**
```
[ncspot]
    appname = *ncspot*
    set_stack_tag = "tag"
```
in the dunstrc.

**Comment by hrkfdn** [comment]
Hey there, the notification library I use allows setting an appname which I've set to `ncspot`. It didn't prevent duplicate notifications, but could you check if it helps with Dunst? The commit is in `main`.

**Comment by hrkfdn** [comment]
Ah, looks like I need to keep track of the previously assigned ID (as per XDG). Hope I'll have the time to work on that this week.

**Comment by hrkfdn** [comment]
Hey @wael444, I have pushed something to `main`. It works fine on Gnome Shell, could you check if it also does with Dunst?
