### ISSUE TITLE
tree or directory navigation

### ISSUE THREAD

**Issue by gurgl** [hrkfdn/ncspot#770]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Either a filebrowser type view or a tree to navigate playlists

**Describe alternatives you've considered**
See above

**Additional context**
my playlists are very much organized using hierarchies (folders in folders in...).

**Comment by hrkfdn** [comment]
Hey there, unfortunately this is not possible because the Spotify API does not expose playlist folders :(

See also: https://github.com/hrkfdn/ncspot/issues/163
