### ISSUE TITLE
Could be nice to have a easy install like apt install or wget...

### ISSUE THREAD

**Issue by FBoucher** [hrkfdn/ncspot#773]
ncspot is really cool and it would be great to have an easy wait to install it "everywhere".

Install on a none dev machine or WSL2 using apt install or wget or curl...

:)

**Comment by ilyachch** [comment]
or flatpak=)

**Comment by hrkfdn** [comment]
Hey there, I can't maintain all those packages myself, so I'm closing this issue. But if any maintainer is willing to step up that'd be very much appreciated.
