### ISSUE TITLE
Context Menu for track using spotify link in clipboard does not have the option to play the song

### ISSUE THREAD

**Issue by maximekabel** [hrkfdn/ncspot#786]
**Is your feature request related to a problem? Please describe.**
When using `Ctrl+V` to open the context menu of a track who's spotify link is in the clipboard, there is no option to play the track.

**Describe the solution you'd like**
A solution for this could be to add `Play track` option in the context menu.

**Comment by Bettehem** [comment]
I'm working on this now. If no problems arise, it could be done by the end of the day.
