### ISSUE TITLE
Allow Saving Playlists to Library

### ISSUE THREAD

**Issue by evanlihou** [hrkfdn/ncspot#791]
**Is your feature request related to a problem? Please describe.**
When I find a playlist I want to save, I need to copy the link, open up the Spotify app, and save it to my library from there. Having a shortcut or a command in the vim-like command prompt would save those extra steps

**Describe the solution you'd like**
A keyboard shortcut, command, or context-menu action to allow saving a playlist to the library. Note: Not every song individually saved, the actual playlist

I didn't see any other issues open or closed that this is a duplicate of, but if I missed one feel free to mention the original and close!

Edit: It looks like following a playlist is [already implemented](https://github.com/hrkfdn/ncspot/blob/f229dfc814c89f899e3ce1f99e80fb8d862919ca/src/model/playlist.rs#L255), just not surfaced anywhere in the UI

**Comment by Bettehem** [comment]
You can save a playlist by pressing `s` with a playlist highlighted and you can delete it by pressing `d`.

**Comment by evanlihou** [comment]
🤦  Yep that totally works, not sure how I missed that. Thank you!
