### ISSUE TITLE
Dbus interface crashes upon wrong dbus command

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#795]
**Describe the bug**
When you send a wrong command through the dbus interface, the interface disconnects with an error message inside ncspot, and it's impossible to send any more dbus commands. An example of crashing the dbus interface happens when you try to send a wrong spotify link with `playerctl --player=ncspot open <link>`. Maybe there can be a way to prevent it from crashing the entire dbus interface, as it is also used for controlling playback.

**To Reproduce**
1. Open ncspot and play any song.
2. Execute the following command in the terminal: `playerctl --player=ncspot open https://open.spotify.com/track/0Fnr9uVtG6txfh1TyIyI5s?si=b78071ab28f14094` (I know it's a wrong link, but it's the link from a spotify page, so it's possible users would use this link instead of the link of a particular song)
3. Go back to ncspot, there is an error message at the bottom, and any other playerctl messages fail because ncspot disconnected. playerctl can't control ncspot anymore either.

**Expected behavior**
The dbus interface shouldn't disconnect or crash upon receiving a wrong command. Maybe it's intended behavior that it crashes when a wrong command is entered and in that case it's my bad, but it seems like a weird behavior.

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Alacritty
 - Version: 0.9.6
 - Installed from: AUR

**Comment by hrkfdn** [comment]
Thanks for the report, fixed
