### ISSUE TITLE
Customize subcategories in library

### ISSUE THREAD

**Issue by davidbgonz** [hrkfdn/ncspot#798]
The most common way I listen to music is through playlists. It would be nice to customize the list of tabs in the library section on some of the following ways:

- Select what categories to show. I never listen to songs from the tracks section so I would like to remove it from the list.
- Reorder categories. Since I use the playlists section the most I would like that to be the first category, then order the rest by usage.
- Select the default category when starting ncspot (i.e. Playlists for me)

**Comment by hrkfdn** [comment]
Hey, I have added a new option called `library_tabs` that should help with this.
