### ISSUE TITLE
Surprising delay when playing tracks

### ISSUE THREAD

**Issue by saethlin** [hrkfdn/ncspot#8]
The official client starts playing songs immediately, so the delay in this client and lack of any immediate response from the UI gives the impression to a first-time user that the client is broken.

Has anyone looked into removing the delay entirely, or what the official client does that this client doesn't?

**Comment by hrkfdn** [comment]
Hmm, I'm not experiencing any noticeable delay. Is this with initial playback or when a next track loads after the currently playing one?

When switching between tracks, I believe the official client does some sort of crossfading.

**Comment by norcalli** [comment]
The delay is because the song is being downloaded, essentially. If you try to play multiple songs immediately after another, it will add to a longer delay, presumably because the network requests aren't being canceled.

**Comment by saethlin** [comment]
I'm seeing a delay with initial playback.

I can believe the song is being downloaded, but why doesn't the official client have the same behavior?

**Comment by keeslinp** [comment]
If I remember correctly, the official client caches the first 7 seconds or so of the songs before they are played. This is why if you lose connection and then play a song it will play for a few seconds and then stop.

**Comment by hrkfdn** [comment]
The bitrate may be at play here as well. ncspot uses 320kbps by default, Spotify uses 160kbps unless explicitly changed.

**Comment by im-n1** [comment]
+1 for sticking with 320kbs

**Comment by elganzua124** [comment]
That issue comes from librespot https://github.com/librespot-org/librespot/issues/306

**Comment by hrkfdn** [comment]
Closed because it is an upstream problem: https://github.com/librespot-org/librespot/issues/306
