### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by norcalli** [hrkfdn/ncspot#80]
I don't want to use ncspot to manage my playlists or anything, and I don't want to accidentally delete something (which I may have already done, considering I pressed `s` because I thought it was a different key). I just want it to be a simple player.

Even if there were confirmation dialogs for mutating actions, a read-only mode is a very good overall safeguard.

**Comment by E5ten** [comment]
I'd also like that

**Comment by hrkfdn** [comment]
I suppose that's an option, though I'd prefer to fix the problem of undesired mutating actions. What do you think is the main problem? `s` being save and 'unsave' at the same time? Would it help to map unsaving to a different binding, e.g. `u`, and add a confirmation dialog when a playlist is unsaved/unfollowed?

**Comment by norcalli** [comment]
@hrkfdn there will never be any combination of keyboard shortcuts that would make me feel at ease.

**Comment by hrkfdn** [comment]
A quick fix could be to modify the scopes here: https://github.com/hrkfdn/ncspot/blob/d213e8a54c009a658bd70108f732c5d7a630cc9e/src/spotify.rs#L261

They're described in depth here: https://developer.spotify.com/documentation/general/guides/scopes/

**Comment by arnauldb** [comment]
The same for me, would be nice to have a read only mode... In the meantime which keys should I never press in order not to delete/modify anything?

Thank you.

**Comment by hhsnopek** [comment]
I have a pull request which introduces a `noop` keybinding so that users can unset default keybindings if they wish. This allows for users to have a "read-only" mode, ie disabling `save` and `delete` keybindings as follows:

```toml
[keybindings]
"s" = "noop" # Disable default save keybinding
"d" = "noop" # Disable default delete keybinding
```

PR: https://github.com/hrkfdn/ncspot/pull/207

**Comment by hrkfdn** [comment]
Closing this as it can be done via `noop` bindings.
