### ISSUE TITLE
Direct pulseaudio with ncspot

### ISSUE THREAD

**Issue by j605** [hrkfdn/ncspot#81]
I compiled ncspot using, `cargo build --release --no-default-features --features pulseaudio_backend,mpris,cursive/pancurses-backend` but in the debug logs I see that it uses rodio and when running I see it is using alsa. Is there a way to force it to use pulseaudio and not alsa or alsa through rodio even though I disabled it?

Alsa causes weird issues and crashes so I want to avoid it. Audio stops at some point and I see some error thrown out although that is logged anywhere.

From the debug logs,
```
[2019-06-03][21:36:55] [librespot_playback::audio_backend::rodio] [DEBUG] Using rodio sink
```
Use of alsa was observed by looking at the mixer at CPU usage in htop which uses pulseaudio's alsa sink.

**Comment by hrkfdn** [comment]
My log confirms it uses PulseAudio:
`
[2019-06-03][21:47:55] [librespot_playback::audio_backend::pulseaudio] [DEBUG] Using PulseAudio sink
`

Have you got the PulseAudio headers installed?

**Comment by j605** [comment]
Yes `libpulse` is installed which has the headers.

**Comment by hrkfdn** [comment]
Unfortunately I don't know how to help you, as I can't reproduce this :(

**Comment by j605** [comment]
I removed the default features configuration in `Cargo.toml` and built it with `  cargo build --release --no-default-features --features pulseaudio_backend,mpris,cursive/pancurses-backend` and now it uses the `pulseaudio_backend`. 

Disabling default features does make the tests fail though,
```rs
==> Starting check()...
   Compiling cursive v0.12.0
   Compiling librespot-playback v0.1.0 (https://github.com/librespot-org/librespot.git#4e3576ba)
   Compiling librespot-connect v0.1.0 (https://github.com/librespot-org/librespot.git#4e3576ba)
   Compiling librespot v0.1.0 (https://github.com/librespot-org/librespot.git#4e3576ba)
   Compiling ncspot v0.1.0 (/home/jagan/srces/ncspot-git/src/ncspot)
error[E0599]: no function or associated item named `default` found for type `cursive::Cursive` in the current scope
   --> src/main.rs:169:32
    |
169 |     let mut cursive = Cursive::default();
    |                                ^^^^^^^ function or associated item not found in `cursive::Cursive`

error[E0599]: no function or associated item named `default` found for type `cursive::Cursive` in the current scope
  --> src/authentication.rs:12:38
   |
12 |     let mut login_cursive = Cursive::default();
   |                                      ^^^^^^^ function or associated item not found in `cursive::Cursive`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `ncspot`.

To learn more, run the command again with --verbose.
```
Is this related somehow? Anyway I am not sure if cargo is respecting my command line of ignoring default features since rodio gets pulled in. I can get this to work only by just removing it from `Cargo.toml`.
