### ISSUE TITLE
Skips through all tracks and crashes

### ISSUE THREAD

**Issue by adastx** [hrkfdn/ncspot#811]
**Describe the bug**
After logging in, ncspot cycles through every song in the Tracks pane and then crashes.

**To Reproduce**
1. Clone repo
2. Build and run ncspot
3. Log in

Or, alternatively:
1. Install through the AUR
2. Run ncspot
3. Log in
4. Play any song
5. See error

**Demonstration**
[![asciicast](https://asciinema.org/a/PjZbXxbA1LhVEQYHl3AKDaRjX.svg)](https://asciinema.org/a/PjZbXxbA1LhVEQYHl3AKDaRjX)

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Alacritty
 - Version: `main` branch
 - Installed from: AUR and cargo

**Backtrace/Debug log**
Find the debug.log and stderr.log [here](https://cloud.adast.xyz/s/Ep2JwiJ6prMaGSd) 

**Additional context**
I used ncspot some time last year and it worked perfectly fine. I have tried to use it several times since then but I keep getting this bug.

**Comment by hrkfdn** [comment]
This seems to be related: https://github.com/librespot-org/librespot/issues/972

**Comment by adastx** [comment]
Thanks for the link. Pretty weird issue but surprisingly easy to fix. 

This: https://github.com/librespot-org/librespot/issues/972#issuecomment-1059073001, is what did the trick for me.

First time I've been able to use ncspot in *months* 🥳
