### ISSUE TITLE
Common issue with symbols not properly rendering not being fixed

### ISSUE THREAD

**Issue by trashban** [hrkfdn/ncspot#815]
This issue has been mentioned previously a lot of times, and have looked at all of them which state the problem.

The solutions that the issues have reported is due to the locale not being set properly or to turn off the nerd-font

Screenshots of Issues
![image](https://user-images.githubusercontent.com/71060961/169817956-ab5cab4e-369d-490a-93d3-d371213ce1e5.png)
![image](https://user-images.githubusercontent.com/71060961/169818090-20dccc7b-6fea-47ad-9e3c-7b062db2ec1b.png)
![image](https://user-images.githubusercontent.com/71060961/169818225-12fd4cf9-3494-41a4-a6bb-038e6d774689.png)

Screenshots of locales

![image](https://user-images.githubusercontent.com/71060961/169818525-abe25774-93b4-42cb-8771-7144d06ef68c.png)

 - OS: Arch-Linux
 - Terminal: Kitty, Alacritty (Mainly kitty, switch to troubleshoot)
 - Installed from AUR

The program works great regardless, just doesn't look as nice.

**Comment by hrkfdn** [comment]
> locale: Cannot set LC_ALL to default locale: No such file or directory

Are your locales set up correctly?

**Comment by Bettehem** [comment]
Check [here](https://wiki.archlinux.org/title/Installation_guide#Localization) and [here](https://wiki.archlinux.org/title/Locale) and make sure you have your locales set correctly.

**Comment by trashban** [comment]
honestly, ive already read all of those guides and tried those guides, followed the steps to set my locale properly but the only thing that does not set whatever I do is LC_ALL. if anyone has any idea why even though ive opened the locale.conf and set it up previously and generating the config file after, that would be great but im happy to close this as its just a issue from my side.

**Comment by trashban** [comment]
![image](https://user-images.githubusercontent.com/71060961/170867705-fb220ba0-d892-416b-875f-2c8e518338cf.png)

Still using this program and seeing the font garbled makes me mad, so I re-read all the other discussions about bat symbols.
Locales are fully set up properly, `LC_ALL` is not supposed to be set regardless.

![image](https://user-images.githubusercontent.com/71060961/170867781-f45120b4-da0f-4dc6-8c7a-a2acfdce4948.png)

My terminal using Alacrity, does not work.

I have downloaded all the nerd-font along with disabling it in the config file. Also doesn't work.

At this point, I'm just really confused on why it is not working.

**Comment by hrkfdn** [comment]
Did you run `locale-gen` after uncommenting `en_US.UTF-8 UTF-8` in `/etc/locale.gen`? That error message in the screenshot of your original post seems to suggest something is missing.

**Comment by trashban** [comment]
I have. I have done it 10+ times and no, it does not work on any terminal.

**Comment by trashban** [comment]
![image](https://user-images.githubusercontent.com/71060961/171117141-e25dd77a-89e6-463a-ba52-2fb5bc697df4.png)
umm... i restarted my pc for the first time today and I use ncspot and it looks perfectly normal now?
I didn't change anything in my locales, I in fact removed one but regardless shouldn't have effected anything.
I'm not gonna complain, it looks very nice now. Thanks for trying to help. Finally, closed.

**Comment by hrkfdn** [comment]
Glad you got it sorted out!
