### ISSUE TITLE
ncspot dunst notications no longer showing album art in 9.8

### ISSUE THREAD

**Issue by jrgiacone** [hrkfdn/ncspot#816]
**Describe the bug**
After updating to 9.8 cover album art no longer shows up in dunst.

**To Reproduce**
1. Have dunst running and notifications enabled on ncspot and play a song or skip songs

**Expected behavior**
Cover art to show

**Screenshots**
![2022-05-23-21:01:55-screenshot](https://user-images.githubusercontent.com/71910145/169946368-b57e71fa-3a4b-4bfc-8689-a18c41bdd3f9.png)

**System (please complete the following information):**
 - OS: Arch Linux kernel 5.17.19
 - Terminal: Alacritty
 - Version: 5.8
 - Installed from: AUR non bin version

**Backtrace/Debug log**
Not sure how to get debug log for ncspot when installed from aur.. I tried but it cant find cargo.toml

**Additional context**
Was working prior to update:
![2022-04-02-18:49:09-screenshot](https://user-images.githubusercontent.com/71910145/169946905-f0f24d68-5aa6-4b75-bbd2-16675e73c599.png)

**Comment by hrkfdn** [comment]
I think it's because the AUR doesn't build ncspot with the `cover` feature enabled.

**Comment by Bettehem** [comment]
This is correct. You need to enable the `cover` feature in the PKGBUILD if you want to use it.
