### ISSUE TITLE
OS X installation tutorial

### ISSUE THREAD

**Issue by oliver-daniel** [hrkfdn/ncspot#82]
Hey hey,

I appreciate that if I was a little more experienced with DIY software, I could probably figure out how to get this running myself. However, I am not. If someone is willing to hold my hand and help me get this working (since I've never been able to get mpd/ncmcpp working), I would be more than happy to do a writeup of my findings.

Insofar, I've cloned the repo into /tmp and tried following the instructions re: calling the `cargo` command. However, after some minutes of downloading and compiling, it says that I am missing certain dependencies that I can't seem to find on Homebrew.

I'd be happy to supply more info if needed.

Thanks!

**Comment by hrkfdn** [comment]
I don't have access to a macOS machine myself, but if you could maybe relay the error messages/missing dependencies, someone else might be able to help? :)

**Comment by oliver-daniel** [comment]
Sorry for the delay!

Here's an early log on a fresh copy:

```
error: failed to run custom build command for `libdbus-sys v0.1.5`
process didn't exit successfully: `/private/tmp/ncspot/target/release/build/libdbus-sys-c191a05670c28744/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n" } }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by hrkfdn** [comment]
Can you try building without the `mpris` feature? For instance: `cargo build --no-default-features --features portaudio_backend`

**Comment by oliver-daniel** [comment]
It took a lot longer to break, but it did...
```
 Compiling ncspot v0.1.0 (/private/tmp/ncspot)
error[E0599]: no function or associated item named `default` found for type `cursive::Cursive` in the current scope
   --> src/main.rs:169:32
    |
169 |     let mut cursive = Cursive::default();
    |                                ^^^^^^^ function or associated item not found in `cursive::Cursive`

error[E0599]: no function or associated item named `default` found for type `cursive::Cursive` in the current scope
  --> src/authentication.rs:12:38
   |
12 |     let mut login_cursive = Cursive::default();
   |                                      ^^^^^^^ function or associated item not found in `cursive::Cursive`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `ncspot`.

To learn more, run the command again with --verbose.
```

**Comment by hrkfdn** [comment]
Right, sorry, you also need to specify a Cursive backend: `cargo run --no-default-features --features portaudio_backend,cursive/pancurses-backend`

**Comment by oliver-daniel** [comment]
Ooookay, it now compiles but doesn't give me any kind of executable to play with.

**Comment by hrkfdn** [comment]
Nothing in `target/`? What if you use `cargo run` instead (with the previously mentioned flags)?

**Comment by oliver-daniel** [comment]
Ha-ha! Looks like the magic bullet was using `cargo run build` with all aforementioned flags, and then moving `target/release/build/ncspot` into `/usr/local/build`. The executable is there and works like a charm, but is quite deeply hidden. Thanks for all the help!

**Comment by hrkfdn** [comment]
Glad it works! I'll close the issue.
