### ISSUE TITLE
Wayland: Nothing copied into the clipboard on track share

### ISSUE THREAD

**Issue by cartesius68** [hrkfdn/ncspot#830]
Pressed `X` or `Shift-X` to copy the track URL and nothing has been copied into the clipboard.

* Arch Linux
* SwayWM 1.7 or GNOME 42 (on **Wayland**)
* ncspot `commit ce6b360cba90967`
* built via `cargo build`

**Comment by hrkfdn** [comment]
Did you build with the `wayland_clipboard` feature enabled?

**Comment by jghauser** [comment]
I just realised that this is the reason why copying to clipboard didn't work for me. Would you consider enabling this option by default? Many if not most Linux systems will be on wayland nowadays.

**Comment by Bettehem** [comment]
Yeah, the `wayland_clipboard` would probably be good to be enabled by default, but iirc it wouldn't compile on Windows with that feature enabled. I'm not that experienced with Rust or Cargo, but perhaps it's possible to exclude the feature on platforms other than Linux?

**Comment by hrkfdn** [comment]
Fixed with #869
