### ISSUE TITLE
'/' search causes an error: jump unsupported in this view

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#832]
**Describe the bug**
When searching for text that's not available with '/' search, it gives an error. Shouldn't be an error as it's normal behavior :) It's like the jump error that was removed in the previous release when trying to go to another tab when there was no tab. 
See #711 

**To Reproduce**
Go to any tab and type text that's not available, and it gives a red error at the bottom, saying jump isn't supported.

**Expected behavior**
Nothing, or maybe another color message stating that the item couldn't be found.

**Screenshots**
![image](https://user-images.githubusercontent.com/48214567/173131813-fc46f88e-bd3a-4d95-833e-08c28b409ed9.png)

**System (please complete the following information):**
 - OS: Arch (btw :p) Linux (latest updates)
 - Terminal: Alacritty
 - Version: 0.9.8
 - Installed from: AUR

**Additional context**
I love ncspot :heart:

**Comment by hrkfdn** [comment]
Argh, another one of those :smile: Should be fixed in `main`. Thanks for the report!

**Comment by cyqsimon** [comment]
It's kind of an oversight on my part in #684 when I made some commands that were failing silently fail loudly instead.

I overlooked the fact that this change made `CommandResult::Consumed(None)` semantically different to `CommandResult::Ignored` (I guess this is how it should be, but I should have fixed it in the PR nonetheless), which to the end user, means that ncspot is complaining too much about trivial things.

I will try to be more thorough in the future =)

**Comment by hrkfdn** [comment]
No worries at all! 🙂
