### ISSUE TITLE
Make dependency on libxcb-* optional

### ISSUE THREAD

**Issue by maxking** [hrkfdn/ncspot#84]
I am not sure if this is already possible to do, but it would be cool to allow making dependency on X and clipboard optional in case there are users who don't really want to copy things to and from clipboard.

There are really 4 libraries I had to install on a Debian system for it to work. Atleast, it would be nice to mention this in docs somewhere?

```
sudo apt install libxcb1-dev
sudo apt install libxcb-render0-dev/testing
sudo apt install libxcb-shape0-dev/testing libxcb-xfixes0-dev/testing
```

I can send in a PR for adding the above to docs, but it would really be cool if they weren't mandatory. I don't know enough Rust yet to help fix this yet, but if this issue stays open for a while, I would end up taking it up (I am learning Rust ;-)

P.S. I know this is probably only going to be faced by a Debian user which splits packages into all these different parts.

**Comment by hrkfdn** [comment]
Hey there!

The library itself is probably already installed (unless you don't use Xorg/Wayland), these are just the development headers that you could delete afterwards.

I'd welcome a change to add a small note to the README, as this could probably help Ubuntu users as well.

I'll leave the ticket open for now, maybe I will make it optional at some point, though it is not very high priority on my list at the moment, sorry.
