### ISSUE TITLE
More complete mouse support

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#840]
**Is your feature request related to a problem? Please describe.**
Currently there are two mouse actions available: clicking at the bottom for play pause, and scrolling with the bar on the side. It would be nice if there were other options, like selecting a tab with the mouse, or playing a song with the mouse. Good mouse support would also allow new TUI users to more easily use ncspot.

**Describe the solution you'd like**
Some nice mouse additions would be:

- [x] Playing a song by clicking it
- [x] Selecting a tab by clicking it
- [x] Scrolling through tabs by scrolling on them (expected behavior for tabs)
- [x] Opening context menu by right clicking an item
- [x] Mouse support inside the context menu

**Additional context**
I know, mouse support in a TUI, I must be crazy, but sometimes the mouse is just more fun and easier 😄. Especially during active music listening, 'Vim-ing' through the library is a bit annoying. It also feels like the current mouse support is only half functional (only for things near the edges). I was looking through the code a bit and from the limited time, I noticed it may be a bit hard to implement this without some refactoring work on the UI, because there is no relative positions for Views. If this would be a welcome addition, I'd be happy to (try and) help 🙂.

**Comment by hrkfdn** [comment]
Hey @ThomasFrans, I decided to take a look at the tab area mouse handling. Feel free to have a go at the rest if you like :)

**Comment by hrkfdn** [comment]
Hey again, I have implemented a variation of this:
Left click will open an album/playlist/etc., right click will open the context menu. I've decided against playing items directly on left click as I feel like this could be undesired, i.e. as it will clear the current queue when an item is clicked accidentally. Hope this is still useful for you.
