### ISSUE TITLE
Playback doesn't switch to default audio device

### ISSUE THREAD

**Issue by jacksongoode** [hrkfdn/ncspot#846]
Playback is stuck to the device assigned on ncspot's load.

**To Reproduce**
1. Load ncspot
2. Plug in headphones (or remove)
3. ncspot still sending output to previous device

**Expected behavior**
ncspot should poll (?) or detect when an audio device has changed and reassign output stream to default device.

**System (please complete the following information):**
 - OS: macOS
 - Terminal: iTerm2
 - Version: 0.10.0
 - Installed from: brew

**Comment by hrkfdn** [comment]
I'm afraid this will have to be tackled in the librespot playback backends
