### ISSUE TITLE
Option to hide own username

### ISSUE THREAD

**Issue by hankshill** [hrkfdn/ncspot#853]
I infrequently share my full screen under a pseudonym and would like 'Library of Real Name' and 'Playlist Name * Real Name' to not be displayed in ncspot. Some users with Spotify linked to their Facebook account are currently not given the option to unlink their accounts and as such their display name will always be their real name (or at least until the unlink option is added for them).

As the name being displayed was previously implemented as a feature on #652 , perhaps this could be made an option in the config?  

The following are "work-arounds" but they don't really address the issue.
1. Just don't have ncspot open while sharing the screen. This is simple enough, but doesn't really address the issue at hand.
2. Move to a view which doesn't have the user's name displayed such as "Search" or a playlist made by another user. This provides some limited functionality of the application but is better than the previous option.
3. Migrate to a Spotify account which is not connected to Facebook. I've been considering doing this, but figured I should ask about this feature request before going through the process of transferring everything to a new account.

**Comment by sudo-jaa** [comment]
I'd be interested in contributing and this seems like a fairly simple change. Is this project accepting community PRs?
