### ISSUE TITLE
? open the help section but don' close it

### ISSUE THREAD

**Issue by dmotrio** [hrkfdn/ncspot#857]
Once opened the help section i need to quit the app to exit the help section.

**To Reproduce**
Open ncspot ancd press "?", after the help section is visible press "?"

**Expected behavior**
close the help section

**System (please complete the following information):**
 - OS:Arch linux
 - Terminal:Foot

 - Installed from: AUR the bin package

**Comment by hrkfdn** [comment]
Press backspace to dismiss views. `q` is bound to `quit` by default. See also: https://github.com/hrkfdn/ncspot#context-menus

**Comment by dmotrio** [comment]
thank you so much and sorry for my stupid question
