### ISSUE TITLE
PipeWire back-end support

### ISSUE THREAD

**Issue by ElotonSotilas** [hrkfdn/ncspot#861]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, but yes, in a way. The regular Spotify client runs on PulseAudio but supports my PipeWire setup with EasyEffects. The audio on here works perfectly fine, however I cannot apply effects from EasyEffects.

**Describe the solution you'd like**
Introduce a new PipeWire backend (preferably) or make the current PulseAudio one display in EasyEffects. Something that may help you is that it doesn't show up with any name in KMixer when I go to Applications under Output. It says it cannot identify the source.

**Describe alternatives you've considered**
Well, I don't know what to say here.

**Additional context**
![image](https://user-images.githubusercontent.com/47796718/178861071-1fd33ac3-24bc-4448-b0bc-a47fe964001a.png)

**Comment by hrkfdn** [comment]
Hey there, audio backends are implemented in librespot, so this would have to implemented there as well.
