### ISSUE TITLE
Does not play any tracks in any playlist

### ISSUE THREAD

**Issue by nloyola** [hrkfdn/ncspot#864]
**Describe the bug**
ncspot does not play any tracks in any playlist. When I select a playlist, it highlights each track and then goes to the next one without playing anything. This repeats until the last track in the playlist.

**To Reproduce**
1. select a playlist

**Expected behavior**
I would like to hear the songs in the playlist.

**System (please complete the following information):**
 - OS: Linux, Debian 11
 - Terminal: Alacritty
 - Version: 0.9.8
 - Installed from: cargo

**Backtrace/Debug log**
None

**Additional context**
I've cleared the ncspot cache, but still does not play any tracks.

**Comment by ElotonSotilas** [comment]
Have you updated to the latest version? I don't see any problems. I use 0.10 on Arch and it works fantastically.

**Comment by hrkfdn** [comment]
Hmm, without a debug log it'll be very hard to diagnose this problem, but my guess is it's related to your sound setup.

**Comment by nloyola** [comment]
I see this in the log:

```
[2022-07-14][22:30:44] [librespot_playback::player] [INFO] Loading <Hunted by a Freak> with Spotify URI <spotify:track:3LD4GOl1YpyrTDriiRLqhs>
[2022-07-14][22:30:44] [librespot_audio::fetch] [DEBUG] Downloading file dea57323a31450ef1a7ad4dc3960a922aaee5e18
[2022-07-14][22:30:44] [librespot_core::channel] [ERROR] channel error: 2 1
[2022-07-14][22:30:44] [librespot_playback::player] [ERROR] Unable to load encrypted file: ChannelError
[2022-07-14][22:30:44] [librespot_playback::player] [WARN] Skipping to next track, unable to load track <SpotifyId { id: 164574622760030272839095534886330221370, audio_type: Track }>: ()
```

If this is not enough, I can post the whole debug log.

Thanks

**Comment by nloyola** [comment]
Is it related to this issue?

https://github.com/librespot-org/librespot/issues/972

**Comment by hrkfdn** [comment]
Yeah, I think that may be it

**Comment by Bettehem** [comment]
I started having this problem too. Adding `104.199.65.124 ap-gew4.spotify.com` to `/etc/hosts` as instructed in the [librespot issue](https://github.com/librespot-org/librespot/issues/972) solved the problem.

**Comment by nloyola** [comment]
Thanks @Bettehem, the problem goes away with the change to `/etc/hosts`.

**Comment by uffer** [comment]
changing the /etc/hosts file did the trick. It was not only a problem in Denmark but in The Netherlands as well.

**Comment by hrkfdn** [comment]
Cool, closing this one then. Maybe we should add it to the documentation at some point 🤔 it keeps coming up more and more often.

**Comment by eyenx** [comment]
Switzerland here. Same issue. Same solution. `/etc/hosts` entry did the trick

**Comment by hrkfdn** [comment]
Looks like the workaround will be incorporated in librespot soon: https://github.com/librespot-org/librespot/pull/1026

**Comment by midtoad** [comment]
Same problem with ncspot today in MacOS terminal , and Ubuntu or Fedora running in UTM. :-(
