### ISSUE TITLE
Add application name under pulseaudio

### ISSUE THREAD

**Issue by vlasakm** [hrkfdn/ncspot#871]
**Is your feature request related to a problem? Please describe.**

`ncspot` since upgrade to `librespot` 0.4.0 has an empty name under pulseaudio:

![2022-07-20-181107](https://user-images.githubusercontent.com/9497885/180047228-24492ee2-bc2a-4890-bacb-e31e06700190.png)

Before:

![2022-07-20-194416](https://user-images.githubusercontent.com/9497885/180048094-5d1f1577-559e-4bab-ba6f-94c98849fa55.png)

This is due to [this change in `librespot`](https://github.com/librespot-org/librespot/pull/976) as anounced in the [changelog](https://github.com/librespot-org/librespot/blob/9385dc840fe010d69e8d8ec952554c42926eedfe/CHANGELOG.md?plain=1#L49-L51). The default for the application name is now [an empty string](https://github.com/librespot-org/librespot/blob/9385dc840fe010d69e8d8ec952554c42926eedfe/playback/src/audio_backend/pulseaudio.rs#L57-L58).

**Describe the solution you'd like**

Set e.g. `ncspot` as a name using the same way `librespot` the binary does it now:

https://github.com/librespot-org/librespot/blob/9385dc840fe010d69e8d8ec952554c42926eedfe/src/main.rs#L1135-L1170

This has the benefit that it allows user overrides, which was the idea AFAICT.

**Describe alternatives you've considered**

[I tried contacting upstream](https://github.com/librespot-org/librespot/pull/976#discussion_r925816710), no fallback will be provided by `librespot`, the library uses should use own logic.

**Comment by hrkfdn** [comment]
Hey @vlasakm, thanks for the report. I have pushed 7b2c1ba to `main` which should set the application name. Let me know if it works :)

**Comment by vlasakm** [comment]
Perfect! Thank you very much @hrkfdn!

![2022-07-21-205644](https://user-images.githubusercontent.com/9497885/180294797-1b5544e0-8d7b-47d0-a8d6-07ce95300ca7.png)

**Comment by hrkfdn** [comment]
Hooray, glad it works :)
