### ISSUE TITLE
Cleaner notifications

### ISSUE THREAD

**Issue by joaopauloalbq** [hrkfdn/ncspot#874]
**Is your feature request related to a problem? Please describe.**
The information are too clustered in the body of the notification.

**Describe the solution you'd like**
Put the song name as the notification title and the rest of the information in the body. Making song and artist identification easier (and nicer IMO).

**Describe alternatives you've considered**
A configurable notification is an alternative. Something like:
```
[notification]
title = "{song}"
body = "{artist} - {album}"
```

**Additional context**
![Screenshot_20220721_130958](https://user-images.githubusercontent.com/9905202/180263293-0e956c0c-2778-4f7f-9190-a5f26047e71b.png)

**Comment by hrkfdn** [comment]
Solved via #893
