### ISSUE TITLE
Status Bar Reflecting Track Formatting Rules

### ISSUE THREAD

**Issue by nbgibson** [hrkfdn/ncspot#877]
**Is your feature request related to a problem? Please describe.**
The recent addition of track formatting rules is a welcome addition, but currently the "Now Playing" status bar at the bottom of the program adheres to the default "Artist - Track Name" layout. It would be nice if it would also draw from the [formatting rules set for the main interface](https://github.com/hrkfdn/ncspot#track-formatting). 

**Describe the solution you'd like**
Ideally the logic used to draw the status bar info would draw from the rules set by the user in their config files within reason. I could see arguments for having different layouts from the main interface so it may be necessary to have a separate config section to control this data.

**Describe alternatives you've considered**
"Ignoring it", "Dealing with it", "Getting a life", [and the usual suspects.](https://en.wikipedia.org/wiki/Five_stages_of_grief).

**Comment by hrkfdn** [comment]
Hey, I have added a `statusbar_format` config option that allows you to set the track formatting in the status bar
