### ISSUE TITLE
How to configure librespot options?

### ISSUE THREAD

**Issue by Katzenwerfer** [hrkfdn/ncspot#882]
I've had some issues with the apresolve.spotify.com access point, which cause the issue mentioned in #811.

On the librespot thread about the issue (ibrespot-org/librespot#972](https://github.com/librespot-org/librespot/issues/972), a workaround to it is mentioned. Simply blocking the URL in the system's hosts file, so that librespot fallbacks to using ap.spotify.com, works. There is also a built-in option (`ap-port`) that allows you to specify the port to connect on the main access point, where if it fails to do so it fallbacks to ap.spotify.com.

I wonder if there is a way to configure that parameter in ncspot so that I don't have to entirely block that connection in my system's hosts file.

Thanks in advance.

**Comment by hrkfdn** [comment]
Hey! There's a fix in librespot 0.4.2 which I'll upgrade to and release with soon: https://github.com/librespot-org/librespot/releases/tag/v0.4.2

Would that help in your case?

**Comment by Katzenwerfer** [comment]
Will update and check if that solves it

**Comment by Katzenwerfer** [comment]
It seems like it works.
Will be closing the issue now.
