### ISSUE TITLE
album_column=false has no effect

### ISSUE THREAD

**Issue by eulerfan271** [hrkfdn/ncspot#884]
Despite setting `album_column=false` in the config file, the album column still appears, the same as if `album_column=true` is set.

Platform/build details, in case useful:
Arch, installed with `ncspot-git` in the AUR on July 27

Thanks!

**Comment by Bettehem** [comment]
Hi, you should use the new `[track_format]` configuration option, as it has replaced the old `album_column` option.\
Look here for instructions: https://github.com/hrkfdn/ncspot#track-formatting

**Comment by eulerfan271** [comment]
Ah, not sure how I missed that.  Thank you!
