### ISSUE TITLE
Should work with media keys

### ISSUE THREAD

**Issue by andrewhalle** [hrkfdn/ncspot#9]
Official client responds to media keys (play/pause, fast foward, reverse) even when the window doesn't have focus, ideally the same thing could be done here.

**Comment by Herbstein** [comment]
This is IMO a must if the program should be completely useful in daily life

**Comment by hrkfdn** [comment]
Indeed, added to the list.

**Comment by andrewhalle** [comment]
Been looking into this a bit. It seems like hooking into global keyboard events is highly display server/operating system specific, so perhaps this should be a compile-time feature like pulse/port audio. In X11, the function to call is [XGrabKey](https://tronche.com/gui/x/xlib/input/XGrabKey.html). I'm sure something similar exists in Cocoa for mac.

**Comment by hrkfdn** [comment]
On Linux we probably want to catch the media-keys via DBUS or directly go for MPRIS for further desktop integration.

**Comment by andrewhalle** [comment]
That makes sense. Should be optional though to support environments without DBUS (like running directly on the virtual terminal, which currently works)

**Comment by norcalli** [comment]
Yeah, the preferred way to do this is usually to register with DBUS on linux through MPRIS. I currently have my buttons mapped to mpris commands.

**Comment by im-n1** [comment]
I dont think its the best idea to force register keys. Instead of that I would go for some kind of listening for certain commands or even the Dbus.

The thing here is I dont want to start play music when I hit pause media key while watching a movie in smplayer for example.

**Comment by hrkfdn** [comment]
This is taken care of thanks to @KoffeinFlummi, at least on dbus systems.

**Comment by Bettehem** [comment]
I think this is an issue with macOS, not ncspot. You could assign a keyboard shortcut to your desired dbus command using something like [iCanHazShortcut](https://github.com/deseven/icanhazshortcut) to create custom keyboard shortcuts on macOS.

**Comment by tonglil** [comment]
Would appreciate if anyone has found out how to control `ncspot` w/ media keys on macos to share.

I can use BTT to call a command in the terminal, but unsure what that is right now - what needs to be sent with `dbus-send`?

**Comment by deed02392** [comment]
You need to send an MPRIS compatible command over dbus. I made a shell script I called from Raycast script like this:

```sh
#!/bin/bash

# @raycast.schemaVersion 1
# @raycast.title Play/Pause for ncspot
# @raycast.mode silent

# @raycast.icon 🎧

# Documentation:
# @raycast.description Play/Pause for ncspot via dbus
# @raycast.author George Hafiz

/opt/brew/bin/dbus-send \
  --print-reply \
  --dest=org.mpris.MediaPlayer2.ncspot \
  /org/mpris/MediaPlayer2 \
  org.mpris.MediaPlayer2.Player.PlayPause \
  && echo "ncspot play/pause"

```

**Comment by Vainyards** [comment]
> You need to send an MPRIS compatible command over dbus. I made a Raycast script like this:
> 
> ```shell
> #!/bin/bash
> 
> # @raycast.schemaVersion 1
> # @raycast.title Play/Pause for ncspot
> # @raycast.mode silent
> 
> # @raycast.icon 🎧
> 
> # Documentation:
> # @raycast.description Play/Pause for ncspot via dbus
> # @raycast.author George Hafiz
> 
> /opt/brew/bin/dbus-send \
>   --print-reply \
>   --dest=org.mpris.MediaPlayer2.ncspot \
>   /org/mpris/MediaPlayer2 \
>   org.mpris.MediaPlayer2.Player.PlayPause \
>   && echo "ncspot play/pause"
> ```

How have you set up Mpris and dsub on macos?! 

What else am I missing in my setup? :P

**Comment by deed02392** [comment]
```
brew install dbus
```

Then depending on your Mac (intel/Apple silicon) the command above will work as-is, or you might need to adjust the path to `/opt/homebrew` or something.

**Comment by canisli** [comment]
> ```
> brew install dbus
> ```
> 
> Then depending on your Mac (intel/Apple silicon) the command above will work as-is, or you might need to adjust the path to `/opt/homebrew` or something.

Upon adjusting the path in your script to `whereis dbus-send`, I'm getting a dbus error: ```Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.ncspot was not provided by any .service files``` 
Did you encounter this as well on macOS? I am using dbus as a brew service. Thanks

**Comment by deed02392** [comment]
That issue sounds like your version of ncspot doesn't have dbus support. It looks like that is still the correct name:
https://github.com/hrkfdn/ncspot/blob/bd80670345f7d31f660caf4fe8c60e4fa8e7f9b1/src/mpris.rs#L503
Unfortunately I'm not using ncspot anymore.

**Comment by Eun** [comment]
You could also using the IPC: https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#remote-control-ipc

**Comment by lukebarone** [comment]
Is there a way to get this going with WSL and tmux? I don't see any sockets created for IPC. I'm having to use the Windows .exe binary to get it working (which is still great, but really want the global keys, even if I have to program it myself).

Could we get more CLI options, such as `ncspot.exe playpause`?

**Comment by deed02392** [comment]
@lukebarone check if the windows binary is compiled with IPC, if not then maybe you need to build it yourself

**Comment by pemato** [comment]
If you have to use DBus, after v1.0, the correct way is:
```sh
NCSPOT_PID=$( pidof ncspot )  
if [ -n $NCSPOT_PID ]; then
  dbus-send --print-reply \  
    --dest="org.mpris.MediaPlayer2.ncspot.instance$NCSPOT_PID" \                                                        
      /org/mpris/MediaPlayer2 \                         
      org.mpris.MediaPlayer2.Player.PlayPause >/dev/null  
fi
```

**Comment by kyteague** [comment]
Here's a [Hammerspoon](https://www.hammerspoon.org) script for anyone interested.

```lua
local KEY_COMMAND_MAP = {
	PLAY = "playpause",
	FAST = "next",
	REWIND = "previous",
}

local handle = io.popen("id -u")
local uid = handle:read("*l")
handle:close()
local ncspot_sock_path = string.format("/tmp/ncspot-%s/ncspot.sock", uid)

local function ncspot_command(cmd)
	local sh = string.format([[echo "%s" | nc -U %s]], cmd, ncspot_sock_path)
	hs.execute(sh, true)
end

local tap = hs.eventtap.new({ hs.eventtap.event.types.systemDefined }, function(e)
	local s = e:systemKey()
	local cmd = KEY_COMMAND_MAP[s.key]
	if not cmd or not s.down then
		return false
	end

	ncspot_command(cmd)
	return true
end)

tap:start()
```

**Comment by kmatt** [comment]
This is a command example when using iCanHazShortcut on macOS, or anything that can call a shell script:

`echo "playpause" | nc -U $(ncspot info | awk '/USER_RUNTIME_PATH/ {print $2}')/ncspot.sock`
