### ISSUE TITLE
[Mouse Support] Scrolling should move the view, not the focus

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#918]
**Is your feature request related to a problem? Please describe.**
For mouse scrolling, it would make more sense to use `scroller.scroll_{up,down}(usize)` instead of the current method of moving the focus. It's also nice to be able to keep the focus at the same place when scrolling with the mouse.

**Describe the solution you'd like**
Changing the mouse events for scrolling in a `ListView` to use `Scroller::scroll_{up,down}` methods.

**Describe alternatives you've considered**
Maybe the current situation is the wanted behavior, which is also fine of course :slightly_smiling_face: I just feel like for the mouse, this approach would make more sense. 

(Sorry for all the mouse related issues :smile:)

**Comment by hrkfdn** [comment]
Thanks for the report, makes total sense :)
