### ISSUE TITLE
[UX/UI consistency] Refactoring ListItem and the models to make contextmenu implementation more consistent

### ISSUE THREAD

**Issue by ThomasFrans** [hrkfdn/ncspot#922]
**Is your feature request related to a problem? Please describe.**
Currently there are no good context menus for ListItems under Artists, Playlists, Podcasts and Browse. Having context menus for them would allow the user to perform actions like saving and deleting those items from the context menu. Those actions are already possible to perform with the keyboard, but right now they aren't offered in the context menus consistently. The song context menu has an entry to save/unsave songs, while none of the other ListItems have this option. This is just like the mouse support an attempt to make the UX more consistent with what's already offered.

**Solutions**
There should either be specific context menus for items (not preferred), or items should somehow be distinguishable so the context menu can decide what options to show for a specific item.

They could be distinguished either based on the type of the item (album, playlist, playable...) or on the actions that can be performed on them, so the contextmenu doesn't have to be altered when new items are added (not that new items will be added soon, but it may be the more correct solution).

- Like that, every saveable item would show a save/unsave option in the context menu. 
- Every item that has artists associated to it could show an artists option.
- Every item that can be played could show options for adding the item to the queue.
- Every item that can be shared could show a share button.
...

**Additional context**
This is again just a suggestion. I wanted to ask for ideas about the feature and the implementation first before trying to make a PR.

**Comment by hrkfdn** [comment]
Fixed by #923
