### ISSUE TITLE
Feature - Dump now playing information to text file and update it upon track changes

### ISSUE THREAD

**Issue by instinctualjealousy** [hrkfdn/ncspot#924]
**Is your feature request related to a problem? Please describe.**
I wouldn't say it's a "problem". I would just like to get the now-playing information out of ncspot for OBS usage.
I am a Windows user, so I don't believe there is currently any notification method for me to intercept.

A weird workaround for myself involves using `statusbar_format` with my preferred formatting string, and capturing the ncspot window with OBS. I then crop out the visible song area, process it a bit for my needs and add a little rightward gradient fade on the extent of visible track name to make it look less chopped-off. It would be preferable to have an actual updating text file though, as with the text source I'd have source extents determined by the text length- something that isn't possible with a crude solution like mine.

**Describe the solution you'd like**
I imagine a config.toml setting to enable/disable dumping the currently playing song information to a text file and updating it with each track change.
Better than that, further configuration with `album`, `artists`, `title` variables (perhaps more?) and the ability to add general text around and in-between those variables- every bit as configurable as `statusbar_format` or other track formatting fields.

**Comment by paulmiddelkoop** [comment]
I also would like to get access to Now playing information. I'm on Mac and used SpotMenu to display the current song in the menu bar. Would be really nice if we somehow got this information out of ncspot ,so we can create extensions for displaying this information in terminal status bars en OS menu bars.

**Comment by hrkfdn** [comment]
So I have 1-2 ideas for this:

- Create a named pipe that programs can read from. ncspot will write status changes into this pipe as JSON. I guess this wouldn't really work on Windows, though.
- Allow configuration of an event handler similar to [how librespot](https://github.com/librespot-org/librespot/wiki/Events) has it. The handler can either read from `stdin` (JSON) or environment variables.

Do you have any preferences/opinions? Also, if you use Linux you can use the MPRIS interface to access the status already.

**Comment by Bettehem** [comment]
You may be able to use MPRIS on macOS too if you install and set up dbus using homebrew. Here you can find a comment relating to this: https://github.com/hrkfdn/ncspot/issues/585#issuecomment-1286279322

**Comment by paulmiddelkoop** [comment]
I think MPRIS is probably the best solution for now.
