### ISSUE TITLE
Navigation Issue

### ISSUE THREAD

**Issue by mattyrc** [hrkfdn/ncspot#95]
I seem to be stuck in the Library screen and can't access Queue or Search. F1 - F4 keys don't seem to do anything when first launching ncspot.  I can still toggle between the Tracks/Albums/Artist/Playlist tabs in Library.

After playing a track or playlist, the F1 - F4 keys only bring up the Show artist/Show album/Share dialog.

ncspot was installed with the latest aur/ncspot-git package with yay. I'm using the default config.

OS: Arch
Kernal: 5.3.4-arch

**Comment by hrkfdn** [comment]
Do F-keys work for you guys in other terminal applications? Which terminal do you use?

**Comment by rjdevs7** [comment]
Using URXVT (rxvt-unicode). F keys work in kitty terminal.

**Comment by hrkfdn** [comment]
I'm guessing this is an issue with the terminal setup, unless F-keys work in other terminal applications using urxvt. Could be the `TERM` variable or other urxvt settings. Are you using tmux? It works fine with urxvt, here.

**Comment by mattyrc** [comment]
I just checked with urxvt and the F-keys do work correctly with that terminal for me. Termite is what was giving me trouble.

**Comment by rjdevs7** [comment]
I resolved my issue with urxvt by setting the VC Keymap using `localectl set-keymap --no-convert us`

I appreciate the quick response. Really liking the app!

**Comment by hrkfdn** [comment]
Okay, thanks for the feedback guys! I'd like to close this then as it's not really a bug and rather terminal emulator related.
