### ISSUE TITLE
Save album

### ISSUE THREAD

**Issue by mr-majkel** [hrkfdn/ncspot#964]
**Is your feature request related to a problem? Please describe.**
I don't see a way to add a particular album to library. In the official gui client, you can click the heart icon on the album view to save the album (**without** saving all the songs to the "liked" playlist).

**Describe the solution you'd like**
A context menu item for a song - "save album". The album is then added to library (but songs are not added to liked songs).

**Describe alternatives you've considered**
Alternative might be adding special context menu for search results items with an option to save a particular entry to the library. The search results are already grouped by "levels": songs, albums, playlists, etc. In those views, if one goes to any tab, selects an entry, there is a dedicated context menu for adding it to the user's library.

**Comment by Bettehem** [comment]
You can use `s` to save an item to your library. Works with tracks, albums, artists etc. But having an option to save an album from the context menu could be a good addition too

**Comment by mr-majkel** [comment]
Thanks @Bettehem! I couldn't find this information in readme. It says `s` is for saving currently playing track (as it is mentioned only for playback section). Feel free to close the issue.
