### ISSUE TITLE
Saving Playlist hangs sometimes (reproducable)

### ISSUE THREAD

**Issue by KarlZeilhofer** [hrkfdn/ncspot#99]
Hi, 

I tried to save a playlist with some hundreds songs. It freezes. 

Attached is the logfile, where I load a successfully saved playlist, add all songs of an artist and then I try to save the new queue to a new playlist. Then it hangs. 

I hope, this could be fixed. 
Greets, Karl
[log.txt.zip](https://github.com/hrkfdn/ncspot/files/3720816/log.txt.zip)

**Comment by hrkfdn** [comment]
Pushed a fix. Let me know if that solves it :)

**Comment by KarlZeilhofer** [comment]
Yep, it works now. Very awesome, that you fix such things within a day. 
I've now saved a playlist with 660 songs without any problems.
