### ISSUE TITLE
Flatpak publishing

### ISSUE THREAD

**Issue by thorpelawrence** [hrkfdn/ncspot#997]
Hi there, I saw in #172 & #773 that you wouldn't be looking to maintain a Flatpak package - I have created one for my own use, and planned to publish to Flathub, most likely I will set it up to automatically track the latest tagged releases.

The reason for raising the issue is that [Flathub prefer package to be controlled by their authors](https://github.com/flathub/flathub/wiki/App-Submission). Although, I definitely understand if you are not able to maintain this yourself, so just wanted to confirm again that you would be happy to have the app published there?

I made a few changes to the copy from the README, which hopefully are ok, to better match the publishing format/guidelines, the working repo is https://github.com/thorpelawrence/flathub/tree/io.github.hrkfdn.ncspot and draft PR is https://github.com/flathub/flathub/pull/3681.

It would mean also having the app appear in the software store of devices using Flatpak, for example:

![image](https://user-images.githubusercontent.com/9198615/204112905-c0051a2a-af2f-4ea8-9047-51543dbb696e.png)

**Comment by hrkfdn** [comment]
Thanks a lot, looks good to me and I appreciate that you're doing this! :)

**Comment by hrkfdn** [comment]
I'll also happily add a link to the README once it's merged and added to Flathub

**Comment by thorpelawrence** [comment]
Hey, it's just been added to Flathub :) https://flathub.org/apps/details/io.github.hrkfdn.ncspot

**Comment by hrkfdn** [comment]
Super cool! I've added a link in the README.

**Comment by thorpelawrence** [comment]
Great, thanks! Appreciate all your work on this project
